--For each column  add round(,2) 
--For each column  add round(,2). Give me file sql for download.

SELECT
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (100)  AND D.RIND NOT IN ('CD','-') THEN  D.RIND ELSE NULL END) AS CAP_SR,
    MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END) AS CAEM_ACT,
    
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('900') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('900') THEN D.COL1 ELSE NULL END)
    END AS RIND_900,
    
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('910') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('910') THEN D.COL1 ELSE NULL END)
    END AS RIND_910,
    
      CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('920') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('920') THEN D.COL1 ELSE NULL END)
    END AS RIND_920,
    
          CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('930') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('930') THEN D.COL1 ELSE NULL END)
    END AS RIND_930,
    
    
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('940') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('940') THEN D.COL1 ELSE NULL END)
    END AS RIND_940,
    
          CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('950') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('950') THEN D.COL1 ELSE NULL END)
    END AS RIND_950,
    
           CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('960') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('960') THEN D.COL1 ELSE NULL END)
    END AS RIND_960,
    
    
               CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('970') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('970') THEN D.COL1 ELSE NULL END)
    END AS RIND_970,
    
    
              CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('980') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1214) AND D.RIND IN ('980') THEN D.COL1 ELSE NULL END)
    END AS RIND_980
FROM
    -- CIS2.VW_DATA_ALL_COEF D 
      CIS2.VW_DATA_ALL D
  --R
INNER JOIN
    CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = :pPERIOADA
    AND D.CUATM_FULL LIKE '%' || :pCOD_CUATM || ';%'
    AND D.CAPITOL IN (1214,100,1129)
    AND D.CUIIO IN (
    
SELECT 
DISTINCT D.CUIIO 
FROM
(
SELECT DISTINCT
  D.CUIIO,
  D.RIND,
  SUM(D.COL1) AS COL1

FROM
  CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
 
   D.CAPITOL IN (100)
  AND D.FORM IN (64)
  AND D.RIND IN ('1','5','6')  

GROUP BY 
  D.CUIIO,
  D.RIND
  
  HAVING 
  NVAL(SUM(D.COL1)) > 0
  ) D 


    )
GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2
ORDER BY
    D.CUIIO