SELECT
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (100)  AND D.RIND NOT IN ('CD','-') THEN  D.RIND ELSE NULL END) AS CAP_SR,
    MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END) AS CAEM_ACT,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN D.COL1 ELSE NULL END)
    END AS RIND_320_COL1,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN D.COL2 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN D.COL2 ELSE NULL END)
    END AS RIND_320_COL2,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN D.COL1 ELSE NULL END)
    END AS RIND_330_COL1,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN D.COL2 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN D.COL2 ELSE NULL END)
    END AS RIND_330_COL2,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN D.COL1 ELSE NULL END)
    END AS RIND_340_COL1,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN D.COL2 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN D.COL2 ELSE NULL END)
    END AS RIND_340_COL2,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('350') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('350') THEN D.COL1 ELSE NULL END)
    END AS RIND_350_COL1,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('350') THEN D.COL2 ELSE NULL END) = 0 THEN NULL
         ELSE SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('350') THEN D.COL2 ELSE NULL END)
    END AS RIND_350_COL2
FROM
    CIS2.VW_DATA_ALL_COEF D
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = :pPERIOADA
    AND D.CAPITOL IN (1126, 1129,100)
    
    AND D.CUIIO IN (
    
SELECT 
DISTINCT D.CUIIO 
FROM
(
SELECT DISTINCT
  D.CUIIO,
  D.RIND,
  SUM(D.COL1) AS COL1

FROM
  CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
 
   D.CAPITOL IN (100)
  AND D.FORM IN (64)
  AND D.RIND IN ('1','5','6')  

GROUP BY 
  D.CUIIO,
  D.RIND
  
  HAVING 
  NVAL(SUM(D.COL1)) > 0
  ) D 


    )
    
GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2
ORDER BY
    D.CUIIO