UPDATE CIS2.MD_RIND
SET RIND = SUBSTR(RIND, 1, 1) || '0' || SUBSTR(RIND, 2)
WHERE CAPITOL = 1049
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
  AND RIND LIKE '1%'
  AND LENGTH(RIND) > 3
  AND SUBSTR(RIND, 2, 1) <> '0';
  
  
  SELECT RIND,
       SUBSTR(RIND, 1, 1) || '0' || SUBSTR(RIND, 2) AS NEW_RIND
FROM CIS2.MD_RIND
WHERE CAPITOL = 1049
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
  AND RIND LIKE '1%'
  AND LENGTH(RIND) > 3
  AND SUBSTR(RIND, 2, 1) <> '0';