SELECT
    D.ID_MD,
    SUBSTR(D.RIND, 1, 30) AS COD,
    D.DENUMIRE,
    D.RIND,
    CASE
        WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN
            REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
        ELSE
            REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
    END AS RIND_MOD
FROM CIS2.MD_RIND D
WHERE D.CAPITOL = 1049
  AND D.CAPITOL_VERS = 2015
  AND D.STATUT = '1'
  AND D.RIND LIKE '3%'
  AND LENGTH(D.RIND) > 3
  AND SUBSTR(D.RIND, 2, 1) <> '0'
ORDER BY D.ORDINE;