INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL51
)
------------------------------------------------------------------------------------


  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
           
  '0'  AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,

   CUIIO AS NR_ROW,   
   ROWNUM AS ORDINE, 
  '0000000000000000000' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW, 
   COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL51
    
FROM
(

    SELECT
        D.CUIIO, 
        R.DENUMIRE,
        SUBSTR(D.CAEM2,2,4) AS COL1,
        D.CUATM AS COL2,
        D.CFP AS COL3,
        MAX(D.PACHET) AS COL4,        
        
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL5, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('11') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL6, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('12') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL7,  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('12') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL8, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('14') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL9, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('15') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL10,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('16') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL11, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('17') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL12, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('18') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL13,  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('19') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL14, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('20') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL15, 
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('21') AND D.CAPITOL IN (1217) THEN D.COL1 END)) AS COL16,
  MAX(CASE WHEN D.RIND IN ('21.1') AND D.CAPITOL IN (1217) THEN D.COL31 END) AS COL51

        
    FROM CIS2.VW_DATA_ALL D

    INNER JOIN (
        SELECT CUIIO, MAX(CUIIO_VERS) AS CUIIO_VERS
        FROM CIS2.RENIM
        WHERE CUIIO_VERS <= :pPERIOADA
        GROUP BY CUIIO
    ) TR
        ON TR.CUIIO = D.CUIIO

    INNER JOIN CIS2.RENIM R  ON R.CUIIO = TR.CUIIO  AND R.CUIIO_VERS = TR.CUIIO_VERS   

    WHERE
        D.PERIOADA = :pPERIOADA
        AND D.FORM = :pFORM
        AND D.FORM_VERS = :pFORM_VERS
        AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
        AND D.FORM = 78  
        AND D.CAPITOL IN (1217)     
        AND :pID_MDTABLE = :pID_MDTABLE 
  
   GROUP BY  D.CFP, D.CUIIO, R.DENUMIRE, D.CUATM,  SUBSTR(D.CAEM2,2,4)
   ORDER BY  D.CUIIO, D.CUATM
  )
