SELECT
  CASE WHEN 
    CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('860') THEN D.COL1 ELSE 0 END )) = 0 
    
  THEN 'Introduceti rind 860'
  
  WHEN
    CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('835') THEN D.COL1 ELSE 0 END)) = 0
    
  THEN 'Introduceti rind 835' END AS REZULTAT
  
FROM
 CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA IN(:PERIOADA)      ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND  
  D.FORM    IN(5) AND
  D.CAPITOL IN (309) AND 
  D.RIND IN('860','835')
  
  
HAVING
 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('860') THEN D.COL1 ELSE 0 END)) = 0 AND
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('835') THEN D.COL1 ELSE 0 END)) > 0 ) OR
  
 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('860') THEN D.COL1 ELSE 0 END)) > 0 AND
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('835') THEN D.COL1 ELSE 0 END)) = 0 )