SELECT DISTINCT 
 nval(SUM(CASE WHEN D.RIND IN('810') THEN  D.COL1 ELSE 0 END))||' <> '||

( nval(SUM(CASE WHEN D.RIND IN('811') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('812') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('816') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('818') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('819') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('820') THEN D.COL1 ELSE 0 END)))
  
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D            
                                       


WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (5)  AND
  D.CAPITOL in (310)

HAVING
 nval(SUM(CASE WHEN D.RIND IN('810') THEN  D.COL1 ELSE 0 END)) <>

( nval(SUM(CASE WHEN D.RIND IN('811') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('812') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('816') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('818') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('819') THEN D.COL1 ELSE 0 END))+
  nval(SUM(CASE WHEN D.RIND IN('820') THEN D.COL1 ELSE 0 END)))