SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  R.CUIIO AS NR_SECTIE,
  R.CUIIO||'-'||MAX(R.DENUMIRE) AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
    RD.RIND||'~'||SUM(ROWNUM) AS NR_ROW,
   RD.ORDINE AS ORDINE,
  '111111' AS DECIMAL_POS,
  REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'&nbsp;'),'&'),'nbsp') AS NUME_ROW, 
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL1 ELSE NULL END)) AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL2 ELSE NULL END)) AS COL4,
   NULL  AS  COL5,
   NULL  AS  COL6

 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
              
                INNER JOIN MD_RIND RD ON D.ID_MD = RD.ID_MD  
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (312)                         AND 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
  
  AND RD.RIND_VERS >= 1068  
  AND RD.RIND NOT IN ('999') 
   
      
       
GROUP BY 
  R.CUIIO,

  RD.RIND,
  RD.ORDINE,
  RD.DENUMIRE
  
  ORDER BY
  R.CUIIO, 
  RD.ORDINE