
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  R.CUIIO AS NR_SECTIE,
  R.CUIIO||'-'||R.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
  '111' AS DECIMAL_POS,
   R.NUME_ROW,  
   R.COL1,
   R.COL2,
   R.COL3
 FROM
 (
SELECT 
L.CUIIO,
L.DENUMIRE,
L.RIND,
L.ORDINE,
L.NUME_ROW,
SUM(L.COL1) AS COL1,
SUM(R.COL1) AS COL2,
SUM(RR.COL1) AS COL3
FROM

(
SELECT
   R.CUIIO,
   R.DENUMIRE,
   RD.RIND,
   RD.ORDINE AS ORDINE,
   REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'&nbsp;'),'&'),'nbsp') AS NUME_ROW,  
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL1 ELSE NULL END)) AS COL1
  
 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN MD_RIND RD ON D.ID_MD=RD.ID_MD  
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (309)                         AND 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY 
  R.CUIIO,
  R.DENUMIRE, 
  RD.RIND,
  RD.ORDINE,
  RD.DENUMIRE
  
  ORDER BY
  R.CUIIO,
  RD.RIND,
  RD.ORDINE
  ) L  LEFT JOIN (
  
  SELECT
   R.CUIIO,
   R.DENUMIRE,
   RD.RIND,
   RD.ORDINE AS ORDINE,
   REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'&nbsp;'),'&'),'nbsp') AS NUME_ROW,  
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN D.COL1 ELSE NULL END)) AS COL1
  
 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN MD_RIND RD ON D.ID_MD=RD.ID_MD  
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (309)                         AND 
  D.PERIOADA IN (:pPERIOADA-1) AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY 
  R.CUIIO,
  R.DENUMIRE, 
  RD.RIND,
  RD.ORDINE,
  RD.DENUMIRE
  ) R ON R.CUIIO = L.CUIIO AND R.RIND = L.RIND
  
  LEFT JOIN (
  
  SELECT
   R.CUIIO,
   R.DENUMIRE,
   RD.RIND,
   RD.ORDINE AS ORDINE,
   REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'&nbsp;'),'&'),'nbsp') AS NUME_ROW,  
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN D.COL1 ELSE NULL END)) AS COL1
  
 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN MD_RIND RD ON D.ID_MD=RD.ID_MD  
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (309)                         AND 
  D.PERIOADA IN (:pPERIOADA-4) AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY 
  R.CUIIO,
  R.DENUMIRE, 
  RD.RIND,
  RD.ORDINE,
  RD.DENUMIRE
  ) RR ON RR.CUIIO = L.CUIIO AND RR.RIND = L.RIND
  
  
  
  
  GROUP BY
L.CUIIO,
L.DENUMIRE,
L.RIND,
L.ORDINE,
L.NUME_ROW

ORDER BY
  L.CUIIO,
  L.RIND,
  L.ORDINE
  ) R