INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
 -- ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2
)


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   TO_NUMBER(RD.RIND) AS NR_ROW,
   RD.ORDINE ORDINE,
   RD.DENUMIRE AS NUME_ROW, 
   ROUND(NVAL(SUM(D.COL1)),0) AS COL1,
   ROUND(NVAL(SUM(D.COL2)),0) AS COL2
 
  
 

 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN VW_CL_CUATM  C ON (C.CODUL = R.CUATM AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%')                  
                INNER JOIN MD_RIND RD ON D.ID_MD = RD.ID_MD 
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (1221)                         AND 
  D.PERIOADA=:pPERIOADA AND 
  C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'
      
       
GROUP BY 
RD.RIND, 
RD.DENUMIRE,
RD.ORDINE


ORDER BY 
RD.ORDINE

