INSERT INTO  CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10,  COL11, COL12, COL13,  COL14, COL15, COL16, COL17
    )

-- Modifica sql - apare eroarea ORA-01476: divisor is equal to zero



SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,

    ROUND(SUM(CASE WHEN MR.RIND IN ('115') THEN D.COL3 END), 0) || '~' || SUM(ROWNUM) AS NR_ROW,
    CC.CODUL AS ORDINE,
    '02002002002002002' AS DECIMAL_POS,
    CC.DENUMIRE AS NUME_ROW,

    ROUND(SUM(CASE WHEN MR.RIND IN ('115') THEN D.COL4 END), 0) AS COL1,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('115') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('115') THEN D.COL3 END), 0),
        2),
    0) AS COL2,

    ROUND(SUM(CASE WHEN MR.RIND IN ('010') THEN D.COL3 END), 0) AS COL3,
    ROUND(SUM(CASE WHEN MR.RIND IN ('010') THEN D.COL4 END), 0) AS COL4,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('010') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('010') THEN D.COL3 END), 0),
        2),
    0) AS COL5,

    ROUND(SUM(CASE WHEN MR.RIND IN ('020') THEN D.COL3 END), 0) AS COL6,
    ROUND(SUM(CASE WHEN MR.RIND IN ('020') THEN D.COL4 END), 0) AS COL7,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('020') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('020') THEN D.COL3 END), 0),
        2),
    0) AS COL8,

    ROUND(SUM(CASE WHEN MR.RIND IN ('035') THEN D.COL3 END), 0) AS COL9,
    ROUND(SUM(CASE WHEN MR.RIND IN ('035') THEN D.COL4 END), 0) AS COL10,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('035') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('035') THEN D.COL3 END), 0),
        2),
    0) AS COL11,

    ROUND(SUM(CASE WHEN MR.RIND IN ('065') THEN D.COL3 END), 0) AS COL12,
    ROUND(SUM(CASE WHEN MR.RIND IN ('065') THEN D.COL4 END), 0) AS COL13,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('065') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('065') THEN D.COL3 END), 0),
        2),
    0) AS COL14,

    ROUND(SUM(CASE WHEN MR.RIND IN ('100') THEN D.COL3 END), 0) AS COL15,
    ROUND(SUM(CASE WHEN MR.RIND IN ('100') THEN D.COL4 END), 0) AS COL16,

    NVL(
        ROUND(
            SUM(CASE WHEN MR.RIND IN ('100') THEN D.COL4 END) /
            NULLIF(SUM(CASE WHEN MR.RIND IN ('100') THEN D.COL3 END), 0),
        2),
    0) AS COL17

FROM VW_DATA_ALL_GC D
INNER JOIN MD_RIND MR
    ON D.ID_MD = MR.ID_MD
INNER JOIN CIS2.VW_CL_CUATM C
    ON D.CUATM = C.CODUL
INNER JOIN CIS2.VW_CL_CUATM CC
    ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'
   AND CC.PRGS IN ('2')

WHERE
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM = :pFORM
    AND D.FORM_VERS = :pFORM_VERS
    AND (:pID_MDTABLE = :pID_MDTABLE)
    AND D.CUATM_FULL LIKE '%' || :pCOD_CUATM || ';%'
    AND D.FORM IN (58)
    AND MR.CAPITOL IN (417)

GROUP BY
    CC.CODUL,
    CC.DENUMIRE,
    CC.FULL_CODE;
  