SELECT 
  
 MAX(CASE WHEN D.RIND IN ('4') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END) AS LICHIDARE, 
 TO_DATE('31.12'||EXTRACT(YEAR FROM SYSDATE-365),'DD.MM.YYYY') AS TERMEN, 
 TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') AS COLB,
--

 'Data sfirsitului periadei de raportare nu este corecta'  AS REZULTAT
  
FROM
  CIS2.VW_DATA_ALL_FR D  
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (59)  --AND  D.CUIIO NOT IN  (41101919, 41086545, 399159, 40476416, 40737437, 41126823 ) 
  
HAVING
(
MAX(CASE WHEN D.RIND IN ('4') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END)=1 AND 
(TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') = TO_DATE('31.12'||EXTRACT(YEAR FROM SYSDATE-365),'DD.MM.YYYY') )
)

OR
(
MAX(CASE WHEN D.RIND IN ('4') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END) IS NULL AND 
(TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') <> TO_DATE('31.12'||EXTRACT(YEAR FROM SYSDATE-365),'DD.MM.YYYY') ))