SELECT
    'Tab.1.2 Rd.2174 COL1=' || CIS2.NVAL(SUM(CASE
        WHEN D.CAPITOL = 381 AND D.RIND = '2174' THEN D.COL1
        ELSE 0
    END)) AS REZULTAT
FROM CIS2.VW_DATA_ALL D
WHERE
    (D.PERIOADA = :PERIOADA) AND
    (D.CUIIO = :CUIIO) AND
    (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1) AND
    (D.FORM = :FORM) AND
    (D.FORM_VERS = :FORM_VERS) AND
    (:CAPITOL = :CAPITOL OR :CAPITOL <> :CAPITOL) AND
    (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
    (D.ID_MD = :ID_MD OR :ID_MD = -1) AND
    D.FORM IN (33) 
    --AND
--    D.CAPITOL = 381 AND
--    D.RIND = '2174'
HAVING
    
    CIS2.NVAL(SUM(CASE
        WHEN D.CAPITOL = 1201 AND D.RIND = '01' THEN D.COL1
        ELSE 0
    END)) <>  0
    AND 
    (CIS2.NVAL(SUM(CASE
        WHEN D.CAPITOL = 381 AND D.RIND = '2174' THEN D.COL1
        ELSE 0
    END)) <= 0
    OR
    CIS2.NVAL(SUM(CASE
        WHEN D.CAPITOL = 381 AND D.RIND = '2174' THEN D.COL1
        ELSE 0
    END)) > 120)
    
    