CREATE OR REPLACE FORCE VIEW USER_BANCU.F_XML_FORMS_24_agr

AS

SELECT 
  L.FORMID,
  L.CUIIO,
  D.DESCRIPTION,
  L.STATUS,
  L.FORM_TYPE,
  L.DATA_REG,
  L.CHECK_CONFIRM,
  L.MESAJ,
  L.PROCESSING_MESSAGE 
 
    FROM  USER_EREPORTING.F_XML_FORMS L INNER JOIN USER_EREPORTING.F_XML_FORMS_STATUS D  ON L.STATUS = D.COD_STATUS
          WHERE
          1=1  
          AND  DATA_REG >= TO_DATE('09/28/2025 00:00:', 'MM/DD/YYYY HH24:MI:SS')
        --  AND STATUS  =  '5'  
          AND   FORM_TYPE IN  ('5-con_22') 

          AND CUIIO NOT IN  (13706)


 ORDER BY 
-- 
DATA_REG DESC 