SELECT 
  L.FORMID,
  L.CUIIO,
  D.DESCRIPTION,
  L.STATUS,
  L.FORM_TYPE,
  L.DATA_REG,
  L.CHECK_CONFIRM,
  L.MESAJ,
  L.PROCESSING_MESSAGE 
 
    FROM  USER_EREPORTING.F_XML_FORMS L INNER JOIN USER_EREPORTING.F_XML_FORMS_STATUS D  ON L.STATUS = D.COD_STATUS
          WHERE
          1=1  
          AND  DATA_REG >= TO_DATE('05/01/2026 00:00:', 'MM/DD/YYYY HH24:MI:SS')
         -- AND STATUS  =  '2'  
          AND   FORM_TYPE IN  ('3-agr')
          
          AND L.CUIIO IN (
          4498267, 355554
          )