SELECT
CC.CODUL,
CC.DENUMIRE,
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1  THEN D.CUIIO END) AS COL2
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    CUIIO_VERS,

    MAX(CASE WHEN RIND = '1.1.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN RIND = '1.1.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    SUM(COL1) AS COL1

  FROM CIS2.VW_DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND RIND IN ('1.1.1','1.1.2')
    AND CAEM2 NOT LIKE 'A%'
--    AND CUIIO = 458963
  GROUP BY 
    CUIIO,
    CUIIO_VERS

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
  
            INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.VW_CL_CUATM CC ON CC.FULL_CODE LIKE '%'||CC.CODUL||';%'   
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2')
  AND D.CAEM2 NOT LIKE 'A%'
  AND D.CUIIO = 458963
  
  AND CC.CODUL IN ('0000000')
  
  
  GROUP BY
  CC.CODUL,
  CC.DENUMIRE