
SELECT 
NR_ROW,
NUME_ROW,
SUM(COL2) + SUM(COL3) + SUM(COL4) AS COL1,
SUM(COL2)  AS COL2, 
SUM(COL3)  AS COL3, 
SUM(COL4)  AS COL4 

FROM
(
SELECT
CC.NR_ROW,
CC.NUME_ROW,
--COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1  AND ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   THEN D.CUIIO END) +
--COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1  AND ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   THEN D.CUIIO END) +
--COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2','1.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND (DD.has_112 + DD.has_111) = 2  AND NVAL(D.COL1) = 1  AND (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') THEN D.CUIIO END)
-- AS COL1,
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1  
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  

THEN D.CUIIO END) AS COL2,
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1 
 AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL3,
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2','1.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND (DD.has_112 + DD.has_111) = 2  AND NVAL(D.COL1) = 1  
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END)
 AS COL4
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    CUIIO_VERS,

    MAX(CASE WHEN RIND = '1.1.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN RIND = '1.1.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    SUM(COL1) AS COL1

  FROM CIS2.VW_DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND RIND IN ('1.1.1','1.1.2')
    AND CAEM2 NOT LIKE 'A%'
--    AND CUIIO = 458963
  GROUP BY 
    CUIIO,
    CUIIO_VERS

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
  
            INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
            

            
            CROSS JOIN (
            SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE  FROM  DUAL UNION  
            SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '2' AS ORDINE   FROM  DUAL
            ) CC
               
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2')
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  
  --AND CC.CODUL IN ('0000000')
  
  
  GROUP BY
  CC.NR_ROW,
  CC.NUME_ROW
  )
  
  GROUP BY 
  NR_ROW,
  NUME_ROW