SELECT
    D.CUIIO,
    D.CAPITOL,
    D.RIND,
    D.ID_MD,
    NULLIF(SUM(D.COL1), 0) AS COL1,
    NULLIF(SUM(D.COL2), 0) AS COL2,
    NULLIF(SUM(D.COL3), 0) AS COL3,
    MAX(D.COL31) AS COL31
FROM CIS2.VW_DATA_ALL D
WHERE D.CUIIO = 458963
  AND D.PERIOADA = 2015
--  AND D.CAPITOL_DEN = 'CAP. A'
GROUP BY
    D.CUIIO,
    D.CAPITOL,
    D.RIND,
    D.ID_MD
HAVING NULLIF(SUM(D.COL1), 0) IS NOT NULL
    OR NULLIF(SUM(D.COL2), 0) IS NOT NULL
    OR NULLIF(SUM(D.COL3), 0) IS NOT NULL
    OR NULLIF(TRIM(MAX(D.COL31)), '') IS NOT NULL
ORDER BY D.RIND;