SELECT *
FROM (
    SELECT
        D.CUIIO,
        D.CAPITOL,
        D.RIND,
        D.ID_MD,
        NULLIF(SUM(D.COL1), 0) AS COL1,
        NULLIF(SUM(D.COL2), 0) AS COL2,
        NULLIF(SUM(D.COL3), 0) AS COL3,
        MAX(D.COL31) AS COL31
    FROM STAT.VW_DATA_ALL D
    WHERE D.T_XML_FORM_ID = 16712535
      AND D.CUIIO = 41188607
      AND D.PERIOADA = 2014
    --  AND D.CAPITOL_DEN = 'CAP. A'
    GROUP BY
        D.CUIIO,
        D.CAPITOL,
        D.RIND,
        D.ID_MD
)
WHERE COL1 IS NOT NULL
   OR COL2 IS NOT NULL
   OR COL3 IS NOT NULL
   OR NULLIF(TRIM(COL31), '') IS NOT NULL
ORDER BY RIND;