--INSERT INTO CIS2.MD_RIND
--(
--ID_MD,
--  FORM,   
--  FORM_VERS,
--  CAPITOL,
--  CAPITOL_VERS,
--  RIND,
--  RIND_VERS,
--  DENUMIRE,
--  DECIMAL_POS,
--  COL_ACTIV,
--  ORDINE,
--  DATA_REG,
--  STATUT,
--  DINAMIC
--)

SELECT 
  ID_MD,
  FORM,   
  FORM_VERS,
  1202 CAPITOL,
  CAPITOL_VERS,
  '23'||SUBSTR(RIND,3,3)||TO_CHAR(rownum )  RIND,
  --SUBSTR(RIND,1,4)||'-'||TO_CHAR(rownum + 31) RIND,
  RIND_VERS,
  DENUMIRE,
  DECIMAL_POS,
  COL_ACTIV,
  TO_NUMBER(TO_CHAR(rownum + 183)) ORDINE,
  SYSDATE DATA_REG,
  STATUT,
  DINAMIC       
FROM
(
SELECT 
  ID_MD,
  FORM,   
  FORM_VERS,
  CAPITOL,
  CAPITOL_VERS,
  RIND,
  --SUBSTR(RIND,1,4)||'-'||TO_CHAR(rownum + 31) RIND,
  RIND_VERS,
  DENUMIRE,
  DECIMAL_POS,
  COL_ACTIV,
  ORDINE,
  DATA_REG,
  STATUT,
  DINAMIC       
FROM CIS2.MD_RIND

WHERE 

capitol=1196 AND capitol_vers=2015
AND STATUT = '1'
AND ORDINE BETWEEN  1 AND 60 

ORDER BY 
ORDINE
)