SELECT L.CUIIO,
       R.CUIIO R_CUIIO,
       R.CUIIO_VERS CUIIO_VERS  
   FROM USER_BANCU.CALINCU_63 L  LEFT JOIN USER_BANCU.VW_MAX_RENIM_CIS2 R ON R.CUIIO = L.CUIIO 
   
        WHERE 
        
            R.CUIIO IS  NULL