INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,COL2,COL3,COL4,COL5
)
--------------------------------------------------------------------------------
  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  ORDINE_CFOJ AS NR_SECTIE,
  CFOJ_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RIND||'~'||ORDINE AS NR_ROW,
  ORDINE,
  CASE WHEN RIND BETWEEN 1301 AND 1319 THEN '11000' ELSE '00000' END AS DECIMAL_POS,
 -- DENUMIRE AS NUME_ROW,
  REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(DENUMIRE,'<br>'),'nbsp'),'&;'),'<b>'),'</b>') AS DENUMIRE,
  CASE WHEN RIND BETWEEN 1301 AND 1319 THEN ROUND(COL1,1) ELSE ROUND(COL1,0) END AS COL1,
  CASE WHEN RIND BETWEEN 1301 AND 1319 THEN ROUND(COL2,1) ELSE ROUND(COL2,0) END AS COL2,
  ROUND(COL3,0) AS COL3,
  ROUND(COL4,0) AS COL4,
  ROUND(COL5,0) AS COL5
FROM
(
SELECT
  A.CFOJ_DENUMIRE||' ('||A.CFOJ||')' AS CFOJ_DENUMIRE,
  A.ORDINE_CFOJ,
  A.RIND,
  A.DENUMIRE,
  A.ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4,
  B.COL5
FROM
(SELECT
  A.ID_MD,
  A.RIND, 
  A.DENUMIRE,
  A.ORDINE,
  TR.CFOJ_DENUMIRE AS CFOJ_DENUMIRE,
  TR.ORDINE AS ORDINE_CFOJ,
  TR.CFOJ
FROM
(SELECT
  R.ID_MD,
  R.RIND,  
  R.DENUMIRE,
  R.ORDINE
FROM 
  CIS2.MD_RIND R      
      INNER JOIN 
          (
            SELECT R.RIND, MAX(R.RIND_VERS) AS RIND_VERS
            FROM CIS2.MD_RIND R 
            WHERE R.RIND_VERS <= :pPERIOADA AND  R.FORM IN (45) AND  R.CAPITOL IN (399)
            GROUP BY R.RIND
          ) TR ON (TR.RIND = R.RIND AND TR.RIND_VERS = R.RIND_VERS AND R.STATUT<>3)
WHERE
  R.FORM IN (45) AND
  R.CAPITOL IN (399) --AND R.RIND IN ('1240')
  GROUP BY 
  R.ID_MD,
  R.RIND, 
  R.DENUMIRE,
  R.ORDINE
) A
  CROSS JOIN 
  (
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899+684+685+686+965' AS CFOJ, 'Total categoriile de gospodarii' AS CFOJ_DENUMIRE, 1 AS ORDINE FROM DUAL UNION
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899+684+685' AS CFOJ, 'Intreprinderi agricole si GT (de fermier) cu terenuri agricole de 10 ha si peste' AS CFOJ_DENUMIRE, 2 AS ORDINE FROM DUAL UNION
SELECT '500+530+540+541+550+590+690+880+890+684' AS CFOJ, 'Intreprinderi agricole si GT (de fermier) cu terenuri agricole de 50 ha si peste' AS CFOJ_DENUMIRE, 3 AS ORDINE FROM DUAL UNION
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899' AS CFOJ, 'Intreprinderi agricole' AS CFOJ_DENUMIRE, 4 AS ORDINE FROM DUAL UNION
SELECT '684+685' AS CFOJ, 'Gospodariile taranesti (de fermier) inregistrate cu suprafata terenurilor de 10 ha si peste' AS CFOJ_DENUMIRE, 5 AS ORDINE FROM DUAL UNION
SELECT '684' AS CFOJ, 'Gospodariile taranesti (de fermier) inregistrate cu suprafata terenurilor de 50 ha si peste' AS CFOJ_DENUMIRE, 6 AS ORDINE FROM DUAL UNION
SELECT '685' AS CFOJ, 'Gospodariile taranesti (de fermier) cu terenuri agricole de la 10 pina la 50 ha' AS CFOJ_DENUMIRE, 7 AS ORDINE FROM DUAL UNION
SELECT '684+685+686+965' AS CFOJ, 'Sector individual' AS CFOJ_DENUMIRE, 8 AS ORDINE FROM DUAL UNION
SELECT '684+685+686' AS CFOJ, 'Gospodariile taranesti (de fermier)' AS CFOJ_DENUMIRE, 9 AS ORDINE FROM DUAL UNION
SELECT '686' AS CFOJ, 'Gospodarii taranesti (de fermier) cu suprafata terenurilor pina la 10 ha' AS CFOJ_DENUMIRE, 10 AS ORDINE FROM DUAL UNION
SELECT '685+686' AS CFOJ, 'Gospodariile taranesti (de fermier) cu terenuri agricole mai putin 50 ha' AS CFOJ_DENUMIRE, 11 AS ORDINE FROM DUAL UNION
SELECT '500+530+540+541+550+590+690+880+890+684+685+686' AS CFOJ, 'Intreprinderi agricole si gospodarii taranesti (de fermier)' AS CFOJ_DENUMIRE, 12 AS ORDINE FROM DUAL UNION
SELECT '965' AS CFOJ, 'Gospodarii auxiliare ale populatiei' AS CFOJ_DENUMIRE, 13 AS ORDINE FROM DUAL
  ) TR
) A
LEFT JOIN
(
SELECT
  TR.CFOJ_DENUMIRE AS CFOJ_DENUMIRE,
  TR.ORDINE AS ORDINE_CFOJ,
  TR.CFOJ,
  D.ID_MD,
--  R.RIND,
--  REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(R.DENUMIRE,'<br>'),'nbsp'),'&;'),'<b>'),'</b>') AS DENUMIRE,
--  R.ORDINE,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' THEN D.COL1 END) AS COL1,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' THEN D.COL2 END) AS COL2,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' THEN D.COL3 END) AS COL3,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' THEN D.COL4 END) AS COL4,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' THEN D.COL5 END) AS COL5
FROM 
  CIS2.VW_DATA_ALL D
  CROSS JOIN 
  (
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899+684+685+686+965' AS CFOJ, 'Total categoriile de gospodarii' AS CFOJ_DENUMIRE, 1 AS ORDINE FROM DUAL UNION
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899+684+685' AS CFOJ, 'Intreprinderi agricole si GT (de fermier) cu terenuri agricole de 10 ha si peste' AS CFOJ_DENUMIRE, 2 AS ORDINE FROM DUAL UNION
SELECT '500+530+540+541+550+590+690+880+890+684' AS CFOJ, 'Intreprinderi agricole si GT (de fermier) cu terenuri agricole de 50 ha si peste' AS CFOJ_DENUMIRE, 3 AS ORDINE FROM DUAL UNION
SELECT '500+510+520+530+540+541+560+580+590+620+690+870+880+890+899' AS CFOJ, 'Intreprinderi agricole' AS CFOJ_DENUMIRE, 4 AS ORDINE FROM DUAL UNION
SELECT '684+685' AS CFOJ, 'Gospodariile taranesti (de fermier) inregistrate cu suprafata terenurilor de 10 ha si peste' AS CFOJ_DENUMIRE, 5 AS ORDINE FROM DUAL UNION
SELECT '684' AS CFOJ, 'Gospodariile taranesti (de fermier) inregistrate cu suprafata terenurilor de 50 ha si peste' AS CFOJ_DENUMIRE, 6 AS ORDINE FROM DUAL UNION
SELECT '685' AS CFOJ, 'Gospodariile taranesti (de fermier) cu terenuri agricole de la 10 pina la 50 ha' AS CFOJ_DENUMIRE, 7 AS ORDINE FROM DUAL UNION
SELECT '684+685+686+965' AS CFOJ, 'Sector individual' AS CFOJ_DENUMIRE, 8 AS ORDINE FROM DUAL UNION
SELECT '684+685+686' AS CFOJ, 'Gospodariile taranesti (de fermier)' AS CFOJ_DENUMIRE, 9 AS ORDINE FROM DUAL UNION
SELECT '686' AS CFOJ, 'Gospodarii taranesti (de fermier) cu suprafata terenurilor pina la 10 ha' AS CFOJ_DENUMIRE, 10 AS ORDINE FROM DUAL UNION
SELECT '685+686' AS CFOJ, 'Gospodariile taranesti (de fermier) cu terenuri agricole mai putin 50 ha' AS CFOJ_DENUMIRE, 11 AS ORDINE FROM DUAL UNION
SELECT '500+530+540+541+550+590+690+880+890+684+685+686' AS CFOJ, 'Intreprinderi agricole si gospodarii taranesti (de fermier)' AS CFOJ_DENUMIRE, 12 AS ORDINE FROM DUAL UNION
SELECT '965' AS CFOJ, 'Gospodarii auxiliare ale populatiei' AS CFOJ_DENUMIRE, 13 AS ORDINE FROM DUAL
  ) TR
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399)
GROUP BY
  TR.CFOJ,
  TR.CFOJ_DENUMIRE,
  TR.ORDINE,
  D.ID_MD
ORDER BY
  TR.ORDINE
) B ON (A.ID_MD=B.ID_MD AND A.CFOJ=B.CFOJ)
ORDER BY
  A.ORDINE
)

ORDER BY NR_SECTIE, NR_ROW