SELECT  
    L.CUIIO,
    L.DENUMIRE,
    L.CUATM,
    L.CAEM2,
    RR.CAEM_ASA,
    RR.R150_COL1,
    CASE WHEN RR.R200_210_COL1 = 0 THEN NULL ELSE RR.R200_210_COL1 END R200_210_COL1,
    ROUND(RR1.COL1,1)  RSF1,
    ROUND(RR2.COL1,1)  RSFPrescurtat,    
    ROUND(RR1.COL2,1)  RSF1_R080,
    ROUND(RR2.COL2,1)  RSFPrescurtat_080    
        
        FROM USER_BANCU.VW_KATALOG_ASA_2013 L 
                    LEFT JOIN USER_BANCU.VW_ASA_24 RR ON RR.CUIIO = L.CUIIO
                    LEFT JOIN    USER_BANCU.VW_RSF1 RR1 ON RR1.CUIIO = L.CUIIO
                    LEFT JOIN    USER_BANCU.VW_REFPRESCURTAT RR2 ON RR2.CUIIO = L.CUIIO