SELECT  
DISTINCT D.CUIIO,
SUM(D.COL14) AS COL14
  
FROM 
  CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS) 
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  D.FORM = 40   AND 
  D.CAPITOL IN 1022 AND 
  D.RIND IN ('19') 

  
GROUP BY
D.CUIIO

ORDER BY
SUM(D.COL14)