SELECT 
    D.ANUL AS ANUL,
    D.CUIIO  AS CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2,
    SUM(D.COL3) AS COL3,
    SUM(D.COL4) AS COL4,
    SUM(D.COL5) AS COL5,
    SUM(D.COL6) AS COL6,
    SUM(D.COL7) AS COL7,
    SUM(D.COL8) AS COL8,
    SUM(D.COL9) AS COL9,
    SUM(D.COL10) AS COL10
      



    
    
FROM   
    CIS2.VW_DATA_ALL D    
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
    D.FORM IN (50)
    AND D.PERIOADA = 2014
   
    AND D.CAPITOL IN (1059) 
    
    AND D.RIND IN ('02')
    
    
    GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2