SELECT L.*,R.*
FROM USER_BANCU.VW_ASA_C4R400 L LEFT JOIN USER_BANCU.VW_RSF_2024 R ON R.CUIIO = L.CUIIO;




CREATE OR REPLACE FORCE VIEW USER_BANCU.VW_ASA_C4R400

AS

SELECT 
    D.ANUL AS ANUL,
    D.CUIIO  AS CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (100)  AND D.RIND NOT IN ('CD','-') THEN D.RIND ELSE NULL END) AS CAP_SR,
    ROUND(MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END), 2) AS CAEM_ACT,

    ROUND(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN D.COL3 ELSE NULL END), 2) AS RIND_400_COL1,
    ROUND(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN D.COL4 ELSE NULL END), 2) AS RIND_400_COL2
    
    
FROM   
    CIS2.VW_DATA_ALL D    
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = 2013
   
    AND D.CAPITOL IN (1127, 1129, 100) 
    AND D.CUIIO IN (
        SELECT DISTINCT D.CUIIO 
        FROM (
            SELECT DISTINCT
                D.CUIIO,
                D.RIND,
                SUM(D.COL1) AS COL1
            FROM CIS2.VW_DATA_ALL D
            WHERE D.PERIOADA = 2013
              AND D.CAPITOL IN (100)
              AND D.FORM IN (64)
              AND D.RIND IN ('1','5','6')  
            GROUP BY D.CUIIO, D.RIND
            HAVING NVAL(SUM(D.COL1)) > 0
        ) D
    )
GROUP BY 
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2;
