--
--CREATE  VIEW VW_DATA_ALL_CAP_5
--
--AS 

SELECT
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    MAX(CASE WHEN D.CAPITOL IN (1128) THEN D.COL33 END ) CUATM_LOC,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (1128) THEN D.COL37 END ) CAEM2_LOC,

    D.RIND,
    ROUND(SUM(CASE WHEN D.CAPITOL IN (1128) THEN D.COL8 END ),2) AS COL1,
    ROUND(SUM(CASE WHEN D.CAPITOL IN (1128) THEN D.COL9 END),2) AS COL2,
    ROUND(SUM(CASE WHEN D.CAPITOL IN (1128) THEN D.COL10 END),2) AS COL3
    
   

FROM
    CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = 2014

    AND D.CAPITOL IN (1128)
  --  AND D.CUIIO = 41302575

    
GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,

    R.CAEM2,
    D.RIND
ORDER BY
    D.CUIIO,
    D.RIND
    
