-- Rounded to 2 decimals on numeric output columns
SELECT
    ROUND(D.ANUL, 2) AS ANUL,
    ROUND(D.CUIIO, 2) AS CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (100)  AND D.RIND NOT IN ('CD','-') THEN D.RIND ELSE NULL END) AS CAP_SR,
    ROUND(MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END), 2) AS CAEM_ACT,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_200,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('210') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('210') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_210,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_220,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('221') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('221') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_221,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('222') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('222') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_222,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_240,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('241') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('241') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_241,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('242') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('242') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_242,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('243') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('243') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_243,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('260') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('260') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_260,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('270') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('270') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_270,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('280') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('280') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_280,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_290,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('291') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('291') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_291,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2911') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2911') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2911,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2912') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2912') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2912,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('292') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('292') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_292,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('293') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('293') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_293,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2931') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2931') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2931,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('295') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('295') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_295,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('296') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('296') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_296,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2961') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2961') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2961,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2962') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2962') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2962,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('297') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('297') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_297,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('300') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('300') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_300,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('305') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('305') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_305,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('310') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('310') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_310,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('311') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('311') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_311,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('312') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('312') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_312
FROM
    CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = :pPERIOADA
    AND D.CUATM_FULL LIKE '%' || :pCOD_CUATM || ';%'
    AND D.CAPITOL IN (1125, 1129, 100)
    AND D.CUIIO IN (
        SELECT DISTINCT D.CUIIO 
        FROM (
            SELECT DISTINCT
                D.CUIIO,
                D.RIND,
                SUM(D.COL1) AS COL1
            FROM CIS2.VW_DATA_ALL D
            WHERE (D.PERIOADA = :PERIOADA)
              AND D.CAPITOL IN (100)
              AND D.FORM IN (64)
              AND D.RIND IN ('1','5','6')  
            GROUP BY D.CUIIO, D.RIND
            HAVING NVAL(SUM(D.COL1)) > 0
        ) D
    )
GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2
ORDER BY
    D.CUIIO;
