SELECT 
   D.CUIIO AS CUIIO,
    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN D.COL4 ELSE NULL END) AS RIND_400_COL2
    
    

FROM   
    CIS2.VW_DATA_ALL_COEF D    
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = :pPERIOADA
    AND D.CUATM_FULL LIKE '%' || :pCOD_CUATM || ';%'
    AND D.CAPITOL IN (1127) 

GROUP BY 

    D.CUIIO

