SELECT DISTINCT 


 'RIND 300 - '||SUM(CASE WHEN  D.CAPITOL IN (1018) AND D.RIND IN ('300') THEN CIS2.NVAL(D.COL1) ELSE 0 END)  
 ||' minute '
 
      

 AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
 
WHERE
  (D.PERIOADA =:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <>  :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (19)  

 
HAVING
SUM(CASE WHEN  D.CAPITOL IN (1018) AND D.RIND IN ('300') THEN CIS2.NVAL(D.COL1) ELSE 0 END) <= 0 
OR 
SUM(CASE WHEN  D.CAPITOL IN (1018) AND D.RIND IN ('300') THEN CIS2.NVAL(D.COL1) ELSE 0 END) > 120
  