SELECT DISTINCT
    --D.CUIIO ||''||
    
    'Rind.501 = ('||
   CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('501') THEN CIS2.NVAL(D.COL1) ELSE NULL END)) 
  ||') sau ' || 'Rind.502 = ('||
  
   CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('502') THEN CIS2.NVAL(D.COL1) ELSE NULL END))
 || ') e marcat  atunci Rînd 250 > 0  -  dar Rînd 250 = ('||  
 CIS2.NVAL(CIS2.NVAL(SUM(CASE WHEN D.RIND IN('250') THEN CIS2.NVAL(D.COL1) ELSE 0 END))) ||')'
 
AS REZULTAT
  FROM
  CIS2.VW_DATA_ALL_TEMP D INNER JOIN
  (
    SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
    WHERE P.PERIOADA = :PERIOADA 
    UNION   
   SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
   WHERE T.PERIOADA = :PERIOADA
   
  ) P ON(D.PERIOADA=P.PERIOADA)
WHERE
  (:PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO               ) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (:FORM = :FORM               ) AND
  (:FORM_VERS=:FORM_VERS        ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND 
  (D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('20.1016.501')
  OR
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('20.1016.502')
  OR  
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('19.1018.250')
  )
--  GROUP BY
--  D.CUIIO
  
  HAVING

 (
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('501') THEN CIS2.NVAL(D.COL1) ELSE NULL END) ) > 0
 AND
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('502') THEN CIS2.NVAL(D.COL1) ELSE NULL END) ) = 0
 AND 
 CIS2.NVAL(CIS2.NVAL(SUM(CASE WHEN D.RIND IN('250') THEN CIS2.NVAL(D.COL1) ELSE 0 END))) = 0
 )
 OR 
 (
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('501') THEN CIS2.NVAL(D.COL1) ELSE NULL END) ) = 0
 AND
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (20) AND D.RIND IN('502') THEN CIS2.NVAL(D.COL1) ELSE NULL END) ) > 0
 AND 
 CIS2.NVAL(CIS2.NVAL(SUM(CASE WHEN D.RIND IN('250') THEN CIS2.NVAL(D.COL1) ELSE 0 END))) = 0
 )