--INSERT INTO TABLE_OUT
--(
--
--PERIOADA,
--FORM,
--FORM_VERS,
--ID_MDTABLE,
--COD_CUATM,
--NR_SECTIE,
--NUME_SECTIE,
--NR_SECTIE1,
--NUME_SECTIE1,
--NR_SECTIE2,
--NUME_SECTIE2,
--NR_ROW,
--ORDINE,
--DECIMAL_POS,
--NUME_ROW
--
--)

SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_TABLE,
  :pCOD_CUATM AS COD_CUATM,

  VB.FULL_CODE AS NR_SECTIE,
  VB.CUATM_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,

  VB.COL1||'~'||VB.FULL_CODE||'~'||VB.ORDINE||ROWNUM||VB.DENUMIRE AS NR_ROW,
  VB.ORDINE,
  '0' AS DECIMAL_POS,
  VB.DENUMIRE AS NUME_ROW

FROM
(
SELECT
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
  SUM(CASE WHEN DD.R601_1 IS NOT NULL THEN DD.R601_1 ELSE NULL END) AS COL1,
  NULLIF(
    ROUND(
      NVL(SUM(DD.R601_1) / NULLIF(SUM(DD.RCNT), 0), 0)
    , 0)
  , 0) AS COL2
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.RIND,
  D.ID_MD,
  D.CAPITOL,
  CIS2.NVAL(D.COL1) AS COL1
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010) AND
  D.RIND IN ('1','2','3','4','5','6')
) A
INNER JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.RIND,
  D.ID_MD,
  D.CAPITOL,
  CIS2.NVAL(D.COL1) AS COL1
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010) AND
  D.RIND NOT IN ('00','--','1','2','3','4','5','6')
) B ON (A.CUIIO = B.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM = C.CODUL)
INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  SUM(CASE WHEN D.RIND IN ('700') AND CIS2.NVAL(D.COL1) <> 0 THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0 THEN 1 ELSE 0 END) AS RCNT
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (:pID_MDTABLE = :pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
GROUP BY
  D.CUIIO,
  D.CUATM
) DD ON (D.CUIIO = DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D
CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000') AND
  D.ID_MDTABLE = 14612
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM = D.CUATM)
GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE

UNION

SELECT
  A.CUATM AS CUATM,
  A.FULL_CODE AS FULL_CODE,
  A.CUATM_DENUMIRE AS CUATM_DENUMIRE,
  A.DENUMIRE AS DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) AS ORDINE,
  B.COL1,
  B.COL2
FROM
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  B.RIND AS RIND_D,
  A.RIND AS RIND_S,
  B.ID_MD AS ID_MD_D,
  A.ID_MD AS ID_MD_S,
  B.CAPITOL,
  A.DENUMIRE,
  T.ORDINE
FROM
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND IN ('1','2','3','4','5','6')
) A
CROSS JOIN
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B
CROSS JOIN CIS2.VW_CL_CUATM C
INNER JOIN
(
SELECT
  ORDINE,
  RIND
FROM CIS2.MD_RIND_OUT
WHERE ID_MDTABLE = 14630
) T ON (T.RIND = B.RIND)
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
ORDER BY
  T.ORDINE,
  B.RIND,
  A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CUATM,
  SUM(CASE WHEN DD.R601_1 IS NOT NULL THEN DD.R601_1 ELSE NULL END) AS COL1,
  NULLIF(
    ROUND(
      NVL(SUM(DD.R601_1) / NULLIF(SUM(DD.RCNT), 0), 0)
    , 0)
  , 0) AS COL2
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.RIND,
  D.ID_MD,
  D.CAPITOL,
  CIS2.NVAL(D.COL1) AS COL1
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010) AND
  D.RIND IN ('1','2','3','4','5','6')
) A
INNER JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.RIND,
  D.ID_MD,
  D.CAPITOL,
  CIS2.NVAL(D.COL1) AS COL1
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1010) AND
  D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B ON (A.CUIIO = B.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM = C.CODUL)
INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  SUM(CASE WHEN D.RIND IN ('700') AND CIS2.NVAL(D.COL1) <> 0 THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0 THEN 1 ELSE 0 END) AS RCNT
FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA = :pPERIOADA) AND
  (:pID_MDTABLE = :pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
GROUP BY
  D.CUIIO,
  D.CUATM
) DD ON (D.CUIIO = DD.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM = C.CODUL)
INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (
  A.RIND_S = B.RIND_S AND
  A.RIND_D = B.RIND_D AND
  A.ID_MD_S = B.ID_MD_S AND
  A.ID_MD_D = B.ID_MD_D AND
  A.CUATM = B.CUATM
)

) VB

ORDER BY
  VB.FULL_CODE,
  VB.ORDINE
