 INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
    
     CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5, COL6, COL7
    )


SELECT
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,   
  
  FF.FULL_CODE AS NR_SECTIE,                                                         
  FF.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   --FF.COL2||'~'||FF.ORDINE AS NR_ROW,
    CASE WHEN INSTR(TO_CHAR(FF.COL2)||'~'||ROWNUM,'.',1) = 1 THEN 0||FF.COL2||'~'||ROWNUM ELSE FF.COL2||'~'||ROWNUM END AS NR_ROW,
   FF.ORDINE AS ORDINE,
  '0001111' AS DECIMAL_POS,
   FF.DENUMIRE AS NUME_ROW,
   FF.COL3  AS COL1,
   FF.COL4  AS COL2,
   FF.COL5  AS COL3,
   FF.COL6  AS COL4,
   FF.COL7  AS COL5,
   FF.COL8  AS COL6,
   FF.COL9  AS COL7
FROM
(
SELECT 
  VB.CUATM            AS CUATM,
  VB.FULL_CODE        AS FULL_CODE,
  VB.CUATM_DENUMIRE   AS CUATM_DENUMIRE,
  VB.DENUMIRE         AS DENUMIRE,
  VB.ORDINE           AS ORDINE, 
  VB.COL1             AS  COL1,    
  VB.COL2             AS  COL2,
  VB.COL3             AS  COL3,
  VB.COL4             AS  COL4,
  VB.COL5             AS  COL5,
  ROUND(VB.COL4    /  CIS2.NOZERO(VB.COL2),1)               AS  COL6,
  ROUND(VB.COL5    /  CIS2.NOZERO(VB.COL3),1)               AS  COL7,
  ROUND((VB.COL2   +  VB.COL4) / CIS2.NOZERO(VB.COL2),1)     AS  COL8,
  ROUND((VB.COL3   +  VB.COL5) / CIS2.NOZERO(VB.COL3),1)     AS  COL9  
FROM (
SELECT
  T.CUATM             AS CUATM,
  T.FULL_CODE         AS FULL_CODE,
  T.CUATM_DENUMIRE    AS CUATM_DENUMIRE,
  T.DENUMIRE          AS DENUMIRE,
  T.ORDINE            AS ORDINE, 
  ROUND(SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S  ELSE NULL END),1) AS COL1,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R000_1  + DD.R000_3 + DD.R000_5) ELSE NULL END),1) AS COL2,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R999_1  + DD.R999_3 + DD.R999_5) ELSE NULL END),1) AS COL3,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R000_2  + DD.R000_4 + DD.R000_6) ELSE NULL END),1) AS COL4,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R999_2  + DD.R999_4 + DD.R999_6) ELSE NULL END),1) AS COL5
  FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
     CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA -1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
      
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') 
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA -1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
      
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(
  SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R000_1,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R000_3,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL5) ELSE NULL END) AS R000_5,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R999_1,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R999_3,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL5) ELSE NULL END) AS R999_5,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R999_2,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R999_4,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R999_6
  
FROM
  CIS2.VW_DATA_ALL D
  
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND  
  (:pFORM =:pFORM) AND
  (:pFORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  D.CAPITOL IN (1017)
    
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D


  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  D.ID_MDTABLE = 14612 
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
  --D.RIND_S
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
ORDER BY
  T.FULL_CODE,
  T.ORDINE
  ) 
  VB 
   
  
  UNION 
  
  
  SELECT
  A.CUATM                         AS  CUATM,
  A.FULL_CODE                     AS  FULL_CODE,
  A.CUATM_DENUMIRE                AS  CUATM_DENUMIRE,
  A.DENUMIRE                      AS  DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S)         AS  ORDINE,
  B.COL1                          AS  COL1,
  B.COL2                          AS  COL2,
  B.COL3                          AS  COL3,
  B.COL4                          AS  COL4,
  B.COL5                          AS  COL5,
  ROUND(B.COL4/CIS2.NOZERO(B.COL2),1)               AS  COL6,
  ROUND(B.COL5/CIS2.NOZERO(B.COL3),1)               AS  COL7,
  ROUND((B.COL2+B.COL4)/CIS2.NOZERO(B.COL2),1)      AS  COL8,
  ROUND((B.COL3+B.COL5)/CIS2.NOZERO(B.COL3),1)      AS  COL9  
FROM
(
SELECT
         C.CODUL AS CUATM,
         C.FULL_CODE,
        C.DENUMIRE AS CUATM_DENUMIRE,    
        B.RIND AS RIND_D,
  A.RIND AS RIND_S,
  B.ID_MD AS ID_MD_D,
  A.ID_MD AS ID_MD_S,
  B.CAPITOL,
  A.DENUMIRE,
  T.ORDINE
FROM
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND IN ('1','2','3','4','5','6')
) A
CROSS JOIN
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B
CROSS JOIN CIS2.VW_CL_CUATM C
INNER JOIN
(
SELECT
  ORDINE,
  RIND
FROM CIS2.MD_RIND_OUT
WHERE ID_MDTABLE = 14630
) T ON (T.RIND = B.RIND)
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
ORDER BY
  T.ORDINE,
  B.RIND,
  A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CUATM,
  ROUND(SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S  ELSE NULL END),1) AS COL1,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R000_1  + DD.R000_3 + DD.R000_5)   ELSE NULL END),1) AS COL2,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R999_1  + DD.R999_3 + DD.R999_5)   ELSE NULL END),1) AS COL3,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R000_2  + DD.R000_4 + DD.R000_6)   ELSE NULL END),1) AS COL4,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R999_2  + DD.R999_4 + DD.R999_6)   ELSE NULL END),1) AS COL5,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R000_2 +  DD.R000_4  + DD.R000_6) /  (CIS2.NOZERO(DD.R000_1  + DD.R000_3 + DD.R000_5)) ELSE NULL END),1) AS COL6,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN (DD.R999_2  + DD.R999_4 + DD.R999_6) /  (CIS2.NOZERO(DD.R999_1  + DD.R999_3  + DD.R999_5))  ELSE NULL END),1) AS COL7,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN ((DD.R000_1 + DD.R000_3+DD.R000_5) + (DD.R000_2 + DD.R000_4 + DD.R000_6))   /   (CIS2.NOZERO(DD.R000_1 + DD.R000_3+DD.R000_5)) ELSE NULL END),1) AS COL8,
  ROUND(SUM(CASE WHEN DD.CAPITOL IN (1017) THEN ((DD.R999_1 + DD.R999_3+DD.R999_5) + (DD.R999_2 + DD.R999_4 + DD.R999_6))  /  (CIS2.NOZERO(DD.R999_1 + DD.R999_3+DD.R999_5))  ELSE NULL END),1) AS COL9

FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  C.CODUL AS CUATM,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
       CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA -1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') 
       
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
       CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA -1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
            
) B ON (A.CUIIO=B.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL)
--INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  C.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R000_1,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R000_3,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL5) ELSE NULL END) AS R000_5,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R999_1,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R999_3,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL5) ELSE NULL END) AS R999_5,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN D.RIND IN ('000') THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R999_2,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R999_4,
  SUM(CASE WHEN D.RIND IN ('999') THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R999_6
  
  
FROM
   CIS2.VW_DATA_ALL D
 
WHERE
   (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND  
    (:pFORM =:pFORM) AND
    (:pFORM_VERS =:pFORM_VERS) AND 
    (:pID_MDTABLE =:pID_MDTABLE) AND
    (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
     D.FORM IN (19) AND
     D.CAPITOL IN (1017)
   
GROUP BY
  D.CUIIO,
  D.CUATM,
  D.CAPITOL
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CUATM=B.CUATM)
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL
--ORDER BY
--  A.CUATM,
--  ORDINE

    ) FF

  
 
  
  