 INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
    
     CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2
    )

SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
     NR_SECTIE,
     NUME_SECTIE,
     NR_SECTIE1,
     NUME_SECTIE1,
     NR_SECTIE2,
     NUME_SECTIE2, 
--     NR_ROW,
     SUM(CASE
    WHEN INSTR(D.NR_ROW, '~') > 0
        THEN SUBSTR(D.NR_ROW, 1, INSTR(D.NR_ROW, '~') - 1)
    ELSE D.NR_ROW
END)||'~'||ORDINE AS NR_ROW,
     ORDINE,
     DECIMAL_POS,
     NUME_ROW,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2



FROM CIS2.TABLE_OUT D


WHERE 
D.ID_MDTABLE = 14955 AND 
--D.PERIOADA IN (:pPERIOADA) AND 
 (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND  
 D.FORM = (:pFORM)  AND 

  (D.COD_CUATM LIKE '%'||:pCOD_CUATM||'%') 

GROUP BY 
NR_SECTIE,
     NUME_SECTIE,
     NR_SECTIE1,
     NUME_SECTIE1,
     NR_SECTIE2,
     NUME_SECTIE2, 
  --   NR_ROW,
     ORDINE,
     DECIMAL_POS,
     NUME_ROW

ORDER BY
NR_SECTIE, 
ORDINE

    
    

