SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
     CIS2.DATA_ALL D
        
         INNER JOIN
         (
 
   
           SELECT P.PERIOADA - 1  PERIOADA FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
        INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
        INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
      
    WHERE
      D.FORM IN (20) AND
      MR.CAPITOL IN (1010) AND
      MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      AND  D.CUIIO IN (5921029)