


INSERT INTO TABLE_OUT
(   
    PERIOADA,
    FORM,
    FORM_VERS,
    ID_MDTABLE,
    COD_CUATM,
    NR_SECTIE,
    NUME_SECTIE,
    NR_SECTIE1,
    NUME_SECTIE1,
    NR_SECTIE2,
    NUME_SECTIE2,
    NR_ROW,
    ORDINE,
    DECIMAL_POS,
    NUME_ROW,
    COL1, COL2, COL3
    --, COL4
)


SELECT   
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   A.CUATM_CODUL AS NR_SECTIE,
   A.CUATM_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  ROUND(A.COL1,0)||'~'||A.RIND AS NR_ROW,
  A.ORDINE  AS ORDINE,
  '011' AS DECIMAL_POS,
  A.DENUMIRE AS NUME_ROW,
  ROUND(A.COL2,0) AS COL1,
  ROUND(A.COL3,1) AS COL2,
  ROUND(A.COL4,1) AS COL3
  --ROUND(A.COL4,1) AS COL4
FROM
(
SELECT
  CC.CODUL AS CUATM_CODUL,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.RIND,
  A.DENUMIRE,
  A.ORDINE,
  SUM(A.COL1+A.COL3+A.COL5) AS COL1,
  SUM(A.COL2+A.COL4+A.COL6) AS COL2,
  CIS2.NVAL(SUM(A.COL2+A.COL4+A.COL6))/CIS2.NOZERO(SUM(A.COL1+A.COL3+A.COL5)) AS COL3,
  CIS2.NVAL(SUM(A.COL1+A.COL2+A.COL3+A.COL4+A.COL5+A.COL6))/CIS2.NOZERO(SUM(A.COL1+A.COL3+A.COL5)) AS COL4
FROM
(
SELECT
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE,
  D.CUATM,
  SUM(CIS2.NVAL(D.COL1)) AS COL1,
  SUM(CIS2.NVAL(D.COL2)) AS COL2,
  SUM(CIS2.NVAL(D.COL3)) AS COL3,
  SUM(CIS2.NVAL(D.COL4)) AS COL4,
  SUM(CIS2.NVAL(D.COL5)) AS COL5,
  SUM(CIS2.NVAL(D.COL6)) AS COL6
FROM
 CIS2.VW_DATA_ALL D 
 INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD=D.ID_MD) -- AND MR.FORM=D.FORM AND MR.FORM_VERS=D.FORM_VERS AND MR.CAPITOL=D.CAPITOL AND MR.CAPITOL_VERS=D.CAPITOL_VERS AND MR.RIND=D.RIND AND MR.RIND_VERS=D.RIND_VERS) 
WHERE
  ( D.PERIOADA =:pPERIOADA) AND 
  ( MR.FORM =:pFORM) AND
  ( MR.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  MR.FORM IN (19) AND
  MR.CAPITOL IN (1017)
GROUP BY 
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE,
  D.CUATM
ORDER BY 
  MR.ORDINE
) A
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  CC.CODUL,
  CC.DENUMIRE,
  A.RIND,
  A.DENUMIRE,
  A.ORDINE
ORDER BY
  A.ORDINE
) A

    ORDER BY A.CUATM_CODUL 
    
    

