SELECT 
D.CUIIO,
SUM(CASE WHEN D.RIND IN ('010') THEN D.COL1 ELSE NULL END ) RSF_010_COL3,
SUM(CASE WHEN D.RIND IN ('010') THEN D.COL2 ELSE NULL END ) RSF_010_COL4,
SUM(CASE WHEN D.RIND IN ('040') THEN D.COL1 ELSE NULL END ) RSF_040_COL3,
SUM(CASE WHEN D.RIND IN ('040') THEN D.COL2 ELSE NULL END ) RSF_040_COL4
FROM
       CIS2.VW_DATA_ALL_FR D             
WHERE 
  D.FORM IN (57)           AND 
  D.CAPITOL_VERS  <= :pPERIOADA AND         
  D.CAPITOL IN (1092) AND
  D.FORM_VERS = 2009  AND 
  D.FORM = 57 AND
  D.PERIOADA IN (:pPERIOADA) AND 
  D.RIND IN ('010','040')
  --AND D.CUIIO = 297922
  GROUP BY
  D.CUIIO
  
  
