INSERT INTO TABLE_OUT
(

PERIOADA,
FORM,
FORM_VERS,
ID_MDTABLE,
COD_CUATM,
NR_SECTIE,
NUME_SECTIE,
NR_SECTIE1,
NUME_SECTIE1,
NR_SECTIE2,
NUME_SECTIE2,
NR_ROW,
ORDINE,
DECIMAL_POS,
NUME_ROW

)

SELECT
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,   
  
  VB.FULL_CODE AS NR_SECTIE,                                                         
  VB.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  VB.COL2||'~'||VB.ORDINE AS NR_ROW,
  VB.ORDINE,
  '00' AS DECIMAL_POS,
  VB.DENUMIRE AS NUME_ROW
  
FROM  
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM               AS CUATM,
  T.FULL_CODE           AS FULL_CODE,
  T.CUATM_DENUMIRE      AS CUATM_DENUMIRE,
  T.DENUMIRE            AS DENUMIRE,
  T.ORDINE              AS ORDINE,
--  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S ELSE  NULL END) AS COL1,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R501_1 ELSE NULL END) AS COL2,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R502_1 ELSE NULL END) AS COL3,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R503_1 ELSE NULL END) AS COL4,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R504_1 ELSE NULL END) AS COL5,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R505_1 ELSE NULL END) AS COL6,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R506_1 ELSE NULL END) AS COL7,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R507_1 ELSE NULL END) AS COL8,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R508_1 ELSE NULL END) AS COL9,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R509_1 ELSE NULL END) AS COL10,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R510_1 ELSE NULL END) AS COL11,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R511_1 ELSE NULL END) AS COL12,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R512_1 ELSE NULL END) AS COL13,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R513_1 ELSE NULL END) AS COL14,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R514_1 ELSE NULL END) AS COL15,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R515_1 ELSE NULL END) AS COL16,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R516_1 ELSE NULL END) AS COL17,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R517_1 ELSE NULL END) AS COL18,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R518_1 ELSE NULL END) AS COL19,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R519_1 ELSE NULL END) AS COL20,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R520_1 ELSE NULL END) AS COL21,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R521_1 ELSE NULL END) AS COL22,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R522_1 ELSE NULL END) AS COL23
    SUM(CASE WHEN D.COL1_S IS NOT NULL  THEN D.COL1_S ELSE NULL END)             AS COL1,
    ROUND(SUM(DD.R601_1)/SUM(CIS2.NOZERO(DD.RCNT)),0)                            AS COL2  
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
--        INNER JOIN
--         (
--           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
--           WHERE P.PERIOADA = :pPERIOADA 
--    
--           UNION   
--   
--           SELECT P.PERIOADA  FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
--           WHERE T.PERIOADA = :pPERIOADA
--   
--        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
     (D.PERIOADA =:pPERIOADA) AND   
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
--      INNER JOIN
--         (
--           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
--           WHERE P.PERIOADA = :pPERIOADA 
--    
--           UNION   
--   
--           SELECT P.PERIOADA  FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
--           WHERE T.PERIOADA = :pPERIOADA
--   
--        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
      (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(

SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN 1 ELSE 0 END) AS RCNT
--  SUM(CASE WHEN D.RIND IN ('501') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R501_1,
--  SUM(CASE WHEN D.RIND IN ('502') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R502_1,
--  SUM(CASE WHEN D.RIND IN ('503') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R503_1,
--  SUM(CASE WHEN D.RIND IN ('504') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R504_1,
--  SUM(CASE WHEN D.RIND IN ('505') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R505_1,
--  SUM(CASE WHEN D.RIND IN ('506') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R506_1,
--  SUM(CASE WHEN D.RIND IN ('507') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R507_1,
--  SUM(CASE WHEN D.RIND IN ('508') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R508_1,
--  SUM(CASE WHEN D.RIND IN ('509') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R509_1,
--  SUM(CASE WHEN D.RIND IN ('510') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R510_1,
--  SUM(CASE WHEN D.RIND IN ('511') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R511_1,
--  SUM(CASE WHEN D.RIND IN ('512') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R512_1,
--  SUM(CASE WHEN D.RIND IN ('513') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R513_1,
--  SUM(CASE WHEN D.RIND IN ('514') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R514_1,
--  SUM(CASE WHEN D.RIND IN ('515') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R515_1,
--  SUM(CASE WHEN D.RIND IN ('516') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R516_1,
--  SUM(CASE WHEN D.RIND IN ('517') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R517_1,
--  SUM(CASE WHEN D.RIND IN ('518') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R518_1,
--  SUM(CASE WHEN D.RIND IN ('519') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R519_1,
--  SUM(CASE WHEN D.RIND IN ('520') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R520_1,
--  SUM(CASE WHEN D.RIND IN ('521') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R521_1,
--  SUM(CASE WHEN D.RIND IN ('522') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R522_1
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM


) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D
--(SELECT 'TOTAL' AS DENUMIRE,                                      '100'   AS ORDINE, '101-102-103-104-105-106-107-108-109-110-111-112-113.1-113.2-113.3-113.4-113.5' AS RIND FROM DUAL UNION
--SELECT 'Hoteluri si moteluri' AS DENUMIRE,                       '100.1' AS ORDINE, '101-102-103'  AS RIND FROM DUAL UNION
--SELECT 'Hoteluri' AS DENUMIRE,                                   '101'   AS ORDINE, '101' AS RIND FROM DUAL UNION
--SELECT 'Hoteluri de tip apartament' AS DENUMIRE,                 '102'   AS ORDINE, '102' AS RIND FROM DUAL UNION
--SELECT 'Moteluri' AS DENUMIRE,                                   '103'   AS ORDINE, '103' AS RIND FROM DUAL UNION
--SELECT 'Camine pentru vizitatori' AS DENUMIRE,                   '104' AS ORDINE,   '113.4' AS RIND FROM DUAL UNION
--SELECT 'Pensiuni turistice si agroturistice - total' AS DENUMIRE,'105' AS ORDINE,   '106-107' AS RIND FROM DUAL UNION  
--SELECT 'Pensiuni turistice.' AS DENUMIRE,                        '106'   AS ORDINE, '106' AS RIND FROM DUAL UNION  
--SELECT 'Pensiuni agroturistice.' AS DENUMIRE,                    '107'   AS ORDINE, '107' AS RIND FROM DUAL UNION  
--
--SELECT 'Structuri de intremare' AS DENUMIRE,                     '108'   AS ORDINE, '113.1-113.2-113.3' AS RIND FROM DUAL UNION 
--SELECT 'Sanatorii'              AS DENUMIRE,                     '109' AS ORDINE,   '113.1'  AS RIND FROM DUAL UNION 
--SELECT 'Pensiuni  de tratament' AS DENUMIRE,                     '110' AS ORDINE,   '113.2'  AS RIND FROM DUAL UNION 
--SELECT 'Alte structiri de intremare' AS DENUMIRE,                '111' AS ORDINE,   '113.3'  AS RIND FROM DUAL UNION
--SELECT 'Structuri de odihna' AS DENUMIRE,                        '112'   AS ORDINE, '104-105-108-109' AS RIND FROM DUAL UNION
--SELECT 'Vila turistica'      AS DENUMIRE,                        '113' AS ORDINE,   '104'    AS RIND FROM DUAL UNION
--SELECT 'Bungalou'            AS DENUMIRE,                        '114'   AS ORDINE, '105'    AS RIND FROM DUAL UNION
--SELECT 'Sate de vacanta si alte structuri' AS DENUMIRE,          '115' AS ORDINE,   '109'  AS RIND FROM DUAL UNION
--SELECT 'Camping'                           AS DENUMIRE,          '116' AS ORDINE,   '108'    AS RIND FROM DUAL UNION
--SELECT 'Tabere de vacanta'                 AS DENUMIRE,          '117' AS ORDINE,   '110'    AS RIND FROM DUAL 
--ORDER BY ORDINE
--) D
  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  
 AND 
  D.ID_MDTABLE = 14612 



  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE,
--  T.ORDINE
    UNION 
SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CUATM                                                                        AS CUATM,
  A.FULL_CODE                                                                    AS FULL_CODE,
  A.CUATM_DENUMIRE                                                               AS CUATM_DENUMIRE,
  A.DENUMIRE                                                                     AS DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S )                                                       AS ORDINE ,
--  A.RIND_D||'.'||A.RIND_S ORDINE,
  B.COL1,
  B.COL2
--  B.COL3,
--  B.COL4,
--  B.COL5,
--  B.COL6,
--  B.COL7,
--  B.COL8,
--  B.COL9,
--  B.COL10,
--  B.COL11,
--  B.COL12,
--  B.COL13,
--  B.COL14,
--  B.COL15,
--  B.COL16,
--  B.COL17,
--  B.COL18,
--  B.COL19,
--  B.COL20,
--  B.COL21,
--  B.COL22,
--  B.COL23
FROM
(
SELECT
      C.CODUL AS CUATM,
      C.FULL_CODE,
      C.DENUMIRE AS CUATM_DENUMIRE,
      B.RIND AS RIND_D,
      A.RIND AS RIND_S,
      B.ID_MD AS ID_MD_D,
      A.ID_MD AS ID_MD_S,
      B.CAPITOL,
      A.DENUMIRE,
      T.ORDINE
    FROM
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R 
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND IN ('1','2','3','4','5','6')
    ) A
    CROSS JOIN
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')

    ) B
    CROSS JOIN CIS2.VW_CL_CUATM C
    INNER JOIN
(
--SELECT '101'   AS ORDINE, '101' AS RIND FROM DUAL UNION
--SELECT '102'   AS ORDINE, '102' AS RIND FROM DUAL UNION
--SELECT '103'   AS ORDINE, '103' AS RIND FROM DUAL UNION
--SELECT '104' AS ORDINE,   '113.4' AS RIND FROM DUAL UNION
--SELECT '106'   AS ORDINE, '106' AS RIND FROM DUAL UNION  
--SELECT '107'   AS ORDINE, '107' AS RIND FROM DUAL UNION  
--
--SELECT '109' AS ORDINE,   '113.1'  AS RIND FROM DUAL UNION 
--SELECT '110' AS ORDINE,   '113.2'  AS RIND FROM DUAL UNION 
--SELECT '111' AS ORDINE,   '113.3'  AS RIND FROM DUAL UNION
--SELECT '113' AS ORDINE,   '104'    AS RIND FROM DUAL UNION
--SELECT '114'   AS ORDINE, '105'    AS RIND FROM DUAL UNION
--SELECT '115' AS ORDINE,   '109'  AS RIND FROM DUAL UNION
--SELECT '116' AS ORDINE,   '108'    AS RIND FROM DUAL UNION
--SELECT '117' AS ORDINE,   '110'    AS RIND FROM DUAL 
--ORDER BY ORDINE
SELECT 
              ORDINE,
              RIND
              
            FROM CIS2.MD_RIND_OUT
            
            WHERE 
            
            ID_MDTABLE = 14630 
) T ON (T.RIND = B.RIND) 
    WHERE
      C.PRGS IN (2) AND
      C.CODUL NOT IN ('9800000')
    ORDER BY
      T.ORDINE,
      B.RIND,
      A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CUATM,
  
--  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S ELSE  NULL END) AS COL1,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R501_1 ELSE NULL END) AS COL2,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R502_1 ELSE NULL END) AS COL3,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R503_1 ELSE NULL END) AS COL4,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R504_1 ELSE NULL END) AS COL5,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R505_1 ELSE NULL END) AS COL6,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R506_1 ELSE NULL END) AS COL7,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R507_1 ELSE NULL END) AS COL8,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R508_1 ELSE NULL END) AS COL9,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R509_1 ELSE NULL END) AS COL10,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R510_1 ELSE NULL END) AS COL11,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R511_1 ELSE NULL END) AS COL12,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R512_1 ELSE NULL END) AS COL13,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R513_1 ELSE NULL END) AS COL14,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R514_1 ELSE NULL END) AS COL15,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R515_1 ELSE NULL END) AS COL16,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R516_1 ELSE NULL END) AS COL17,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R517_1 ELSE NULL END) AS COL18,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R518_1 ELSE NULL END) AS COL19,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R519_1 ELSE NULL END) AS COL20,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R520_1 ELSE NULL END) AS COL21,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R521_1 ELSE NULL END) AS COL22,
--  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R522_1 ELSE NULL END) AS COL23

    SUM(CASE WHEN D.COL1_S IS NOT NULL  THEN D.COL1_S ELSE NULL END) AS COL1,
    ROUND(SUM(DD.R601_1)/SUM(CIS2.NOZERO(DD.RCNT)),0) AS COL2
  
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
--      INNER JOIN
--         (
--           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
--           WHERE P.PERIOADA = :pPERIOADA 
--    
--           UNION   
--   
--           SELECT P.PERIOADA  FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
--           WHERE T.PERIOADA = :pPERIOADA
--   
--        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
--      INNER JOIN
--         (
--           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
--           WHERE P.PERIOADA = :pPERIOADA 
--    
--           UNION   
--   
--           SELECT P.PERIOADA  FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
--           WHERE T.PERIOADA = :pPERIOADA
--   
--        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
       (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B ON (A.CUIIO=B.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL)
INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN 1 ELSE 0 END) AS RCNT

--  SUM(CASE WHEN D.RIND IN ('501') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R501_1,
--  SUM(CASE WHEN D.RIND IN ('502') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R502_1,
--  SUM(CASE WHEN D.RIND IN ('503') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R503_1,
--  SUM(CASE WHEN D.RIND IN ('504') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R504_1,
--  SUM(CASE WHEN D.RIND IN ('505') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R505_1,
--  SUM(CASE WHEN D.RIND IN ('506') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R506_1,
--  SUM(CASE WHEN D.RIND IN ('507') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R507_1,
--  SUM(CASE WHEN D.RIND IN ('508') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R508_1,
--  SUM(CASE WHEN D.RIND IN ('509') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R509_1,
--  SUM(CASE WHEN D.RIND IN ('510') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R510_1,
--  SUM(CASE WHEN D.RIND IN ('511') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R511_1,
--  SUM(CASE WHEN D.RIND IN ('512') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R512_1,
--  SUM(CASE WHEN D.RIND IN ('513') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R513_1,
--  SUM(CASE WHEN D.RIND IN ('514') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R514_1,
--  SUM(CASE WHEN D.RIND IN ('515') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R515_1,
--  SUM(CASE WHEN D.RIND IN ('516') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R516_1,
--  SUM(CASE WHEN D.RIND IN ('517') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R517_1,
--  SUM(CASE WHEN D.RIND IN ('518') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R518_1,
--  SUM(CASE WHEN D.RIND IN ('519') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R519_1,
--  SUM(CASE WHEN D.RIND IN ('520') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R520_1,
--  SUM(CASE WHEN D.RIND IN ('521') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R521_1,
--  SUM(CASE WHEN D.RIND IN ('522') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R522_1
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CUATM=B.CUATM) 
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL

) VB 
    ORDER BY 
    VB.FULL_CODE,
    VB.ORDINE   