INSERT INTO TABLE_OUT
(

PERIOADA,
FORM,
FORM_VERS,
ID_MDTABLE,
COD_CUATM,
NR_SECTIE,
NUME_SECTIE,
NR_SECTIE1,
NUME_SECTIE1,
NR_SECTIE2,
NUME_SECTIE2,
NR_ROW,
ORDINE,
DECIMAL_POS,
NUME_ROW

)


SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_TABLE,
:pCOD_CUATM AS COD_CUATM,
'0' AS NR_SECTIE,
'0' AS NUME_SECTIE,
'0'  AS NR_SECTIE1,
'0'  AS NUME_SECTIE1,
'0'  AS NR_SECTIE2,
'0'  AS NUME_SECTIE2,
 -- VB.COL2||'~'|| VB.ORDINE AS NR_ROW,
  VB.COL1||'~'||VB.ORDINE||ROWNUM||VB.DENUMIRE AS NR_ROW,
 VB.ORDINE,
 '0' AS DECIMAL_POS,
 VB.DENUMIRE AS NUME_ROW
-- ROUND(VB.COL2,1)  AS  COL1,
-- ROUND(VB.COL3,1)  AS  COL2

FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
--  T.CUATM,
--  T.FULL_CODE,
--  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
  SUM(CASE WHEN DD.R601_1 IS NOT NULL  THEN DD.R601_1 ELSE NULL END) AS COL1,
--  ROUND(SUM(DD.R601_1)/SUM(DD.RCNT),0) AS COL2

NULLIF(
  ROUND(
    NVL(SUM(DD.R601_1) / NULLIF(SUM(DD.RCNT), 0), 0)
  , 0)
, 0) AS COL2
  
--  SUM(CASE WHEN DD.R601_1 IS NOT NULL THEN DD.R601_1/CIS2.NOZERO(DD.RCNT) ELSE NULL END) AS COL2
  
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R202_1 ELSE NULL END) AS COL3,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R203_1 ELSE NULL END) AS COL4,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R204_1 ELSE NULL END) AS COL5,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R205_1 ELSE NULL END) AS COL6,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_3 ELSE NULL END) AS COL7,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R206_1 ELSE NULL END) AS COL8,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R207_1 ELSE NULL END) AS COL9
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
 -- CC.CODUL AS CUATM,
  --CC.DENUMIRE AS CUATM_DENUMIRE,
  --A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
    --  D.CUATM,
      D.RIND,
      D.ID_MD,
    --  D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
   --   AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      --D.CUATM,
      D.RIND,
      D.ID_MD,
   --   D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
     -- AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO
--  CC.CODUL,
--  CC.DENUMIRE,
 -- A.CAPITOL
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
 -- D.CUATM,
--  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('700') AND CIS2.NVAL(D.COL1) <> 0  THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN 1 ELSE 0 END) AS RCNT
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
 -- AND D.CUIIO = 458868
GROUP BY
  D.CUIIO
 -- D.CAPITOL
--  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
--  C.CODUL AS CUATM,
--  C.FULL_CODE,
--  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D
  WHERE
   
  D.ID_MDTABLE = 14612 
) T ON (T.RIND LIKE '%'||D.RIND_D||'%') -- AND T.CUATM=D.CUATM)

GROUP BY
  T.DENUMIRE,
  T.ORDINE
  
 -- ORDER BY T.FULL_CODE
 
-- ORDER BY 
--    T.ORDINE
    UNION 
SELECT
  A.DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) ORDINE,
--  A.RIND_D||'.'||A.RIND_S ORDINE,
  B.COL1,
  B.COL2
FROM
(
SELECT
      B.RIND AS RIND_D,
      A.RIND AS RIND_S,
      B.ID_MD AS ID_MD_D,
      A.ID_MD AS ID_MD_S,
      B.CAPITOL,
      A.DENUMIRE,
      T.ORDINE
    FROM
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R 
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND IN ('1','2','3','4','5','6')
    ) A
    CROSS JOIN
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')

    ) B
  --  CROSS JOIN CIS2.VW_CL_CUATM C
    INNER JOIN
(
    SELECT 
              ORDINE,
              RIND
              
            FROM CIS2.MD_RIND_OUT
            
            WHERE 
            
            ID_MDTABLE = 14630 

) T ON (T.RIND = B.RIND) 
    ORDER BY
      T.ORDINE,
      B.RIND,
      A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  --CC.CODUL AS CUATM,
  SUM(CASE WHEN DD.R601_1 IS NOT NULL  THEN DD.R601_1 ELSE NULL END) AS COL1,
--  ROUND(SUM(DD.R601_1)/SUM(CIS2.NOZERO(DD.RCNT)),0) AS COL2
NULLIF(
  ROUND(
    NVL(SUM(DD.R601_1) / NULLIF(SUM(DD.RCNT), 0), 0)
  , 0)
, 0) AS COL2
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  --CC.CODUL AS CUATM,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    WHERE
      (D.PERIOADA =:pPERIOADA) AND 
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
    --  AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    WHERE
      (D.PERIOADA =:pPERIOADA) AND 
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
    --  AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  --CC.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
 -- D.CUATM,
--  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('700') AND CIS2.NVAL(D.COL1) <> 0  THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R601_1,
  SUM(CASE WHEN D.RIND IN ('601') AND CIS2.NVAL(D.COL1) <> 0  THEN 1 ELSE 0 END) AS RCNT
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1016)
 -- AND D.CUIIO = 458868
GROUP BY
  D.CUIIO
 -- D.CAPITOL
--  D.CUATM
) DD ON (D.CUIIO=DD.CUIIO)
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D
  --CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D)


--ORDER BY 
-- ORDINE


        ) VB 
 
 ORDER BY VB.ORDINE 

