SELECT 
DISTINCT 
CUIIO,
MAX(CASE WHEN RIND IN ('6') AND CAPITOL = 1091 THEN COL1 ELSE NULL END ) NM_S,
MAX(CASE WHEN RIND IN ('10') AND CAPITOL = 1091 THEN COL1 ELSE NULL END ) NM_SCRIPT,
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1093 THEN COL1 ELSE NULL END ) COL1,
NULL AS COL2  

FROM CIS2.VW_DATA_ALL_FR
WHERE
FORM = 57
--AND CUIIO =  20454236 
AND PERIOADA = 2013

--AND CAPITOL = 1091

GROUP BY 
CUIIO

HAVING 

MAX(CASE WHEN RIND IN ('6') AND CAPITOL = 1091 THEN COL1 ELSE NULL END ) IS NOT NULL 
OR 
MAX(CASE WHEN RIND IN ('10') AND CAPITOL = 1091 THEN COL1 ELSE NULL END ) IS NOT NULL 
OR 
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1093 THEN COL1 ELSE NULL END )IS NOT NULL 
