SELECT 
DISTINCT 
CUIIO,

MAX(CASE WHEN RIND IN ('6') THEN COL1 ELSE NULL END ) COL1,
MAX(CASE WHEN RIND IN ('10') THEN COL1 ELSE NULL END ) COL2  

FROM CIS2.VW_DATA_ALL_FR
WHERE
FORM = 57
AND CUIIO =  20454236 
AND PERIOADA = 2014

AND CAPITOL = 1091

GROUP BY
CUIIO
