SELECT 
DISTINCT 
CUIIO,
MAX(CASE WHEN RIND IN ('3') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) NM_S,
MAX(CASE WHEN RIND IN ('10') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) NM_SCRIPT,
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1120 THEN COL1 ELSE NULL END ) COL1,
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1121 THEN COL1 ELSE NULL END ) COL2,
MAX(CASE WHEN RIND IN ('3') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) NM_PG,
MAX(CASE WHEN RIND IN ('5') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) NM_PP    

FROM CIS2.VW_DATA_ALL_FR
WHERE
FORM = 63
--AND CUIIO =  5523 
AND PERIOADA = 2013



GROUP BY 
CUIIO

HAVING 
--
MAX(CASE WHEN RIND IN ('3') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) IS NOT NULL 
OR 
MAX(CASE WHEN RIND IN ('10') AND CAPITOL = 1119 THEN COL1 ELSE NULL END ) IS NOT NULL 
OR 
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1120 THEN COL1 ELSE NULL END ) IS NOT NULL 
OR 
MAX(CASE WHEN RIND IN ('010') AND CAPITOL = 1121 THEN COL1 ELSE NULL END ) IS NOT NULL