SELECT
    D.CUIIO,
    D.CUIIO_VERS,
    SUM(CASE WHEN D.RIND IN ('1.3.1')  THEN COL1 ELSE 0 END) AS R1_3_1,
    SUM(CASE WHEN D.RIND IN ('1.3.2')  THEN COL1 ELSE 0 END) AS R1_3_2 
  FROM CIS2.VW_DATA_ALL D
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND 
    D.RIND IN ('1.3.1','1.3.2')
  GROUP BY 
    D.CUIIO,
    D.CUIIO_VERS