SELECT
    D.CUIIO,
    R.IDNO,
    R.CUATM,
    R.DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('1.7.1')  THEN COL1 ELSE 0 END) AS R_1_7_1_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.1')  THEN COL2 ELSE 0 END) AS R_1_7_1_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.2')  THEN COL1 ELSE 0 END) AS R_1_7_2_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.2')  THEN COL2 ELSE 0 END) AS R_1_7_2_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.3')  THEN COL1 ELSE 0 END) AS R_1_7_3_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.3')  THEN COL2 ELSE 0 END) AS R_1_7_3_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.4')  THEN COL1 ELSE 0 END) AS R_1_7_4_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.4')  THEN COL2 ELSE 0 END) AS R_1_7_4_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.5')  THEN COL1 ELSE 0 END) AS R_1_7_5_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.5')  THEN COL2 ELSE 0 END) AS R_1_7_5_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.6')  THEN COL1 ELSE 0 END) AS R_1_7_6_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.6')  THEN COL2 ELSE 0 END) AS R_1_7_6_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.7.7')  THEN COL1 ELSE 0 END) AS R_1_7_7_C1,
    SUM(CASE WHEN D.RIND IN ('1.7.7')  THEN COL2 ELSE 0 END) AS R_1_7_7_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.8.1')  THEN COL1 ELSE 0 END) AS R_1_8_1_C1,
    SUM(CASE WHEN D.RIND IN ('1.8.1')  THEN COL2 ELSE 0 END) AS R_1_8_1_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.8.2')  THEN COL1 ELSE 0 END) AS R_1_8_2_C1,
    SUM(CASE WHEN D.RIND IN ('1.8.2')  THEN COL2 ELSE 0 END) AS R_1_8_2_C2,
    
    SUM(CASE WHEN D.RIND IN ('1.8.3')  THEN COL1 ELSE 0 END) AS R_1_8_3_C1,
    SUM(CASE WHEN D.RIND IN ('1.8.3')  THEN COL2 ELSE 0 END) AS R_1_8_3_C2
    
    
      
  FROM CIS2.VW_DATA_ALL D inner join CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
                          inner join CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM   
                            
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
   
  
  --  AND D.CUIIO = 400053
  GROUP BY 
  D.CUIIO,
    R.IDNO,
    R.CUATM,
    R.DENUMIRE
    
    ORDER BY 
    R.CUATM