SELECT
    D.CUIIO,
    R.IDNO,
    R.CUATM,
    R.DENUMIRE,
    BS.CIF_IT CIF_IT,
    BS.PERS_IT PERS_IT, 
    MAX(CASE WHEN D.CAPITOL = 100 AND D.RIND NOT IN ('ER','-')THEN D.RIND  END) AS CAP_SR,
    
    
    
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.1')  THEN D.COL1 ELSE 0 END) AS R_1_7_1_C1,
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.2')  THEN D.COL1 ELSE 0 END) AS R_1_7_2_C1,
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.3')  THEN D.COL1 ELSE 0 END) AS R_1_7_3_C1,
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.4')  THEN D.COL1 ELSE 0 END) AS R_1_7_4_C1,
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.5')  THEN D.COL1 ELSE 0 END) AS R_1_7_5_C1,
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.6')  THEN D.COL1 ELSE 0 END) AS R_1_7_6_C1,
    
    
    SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.7')  THEN D.COL1 ELSE 0 END) AS R_1_7_7_C1
    
    
    
    
    
    
      
  FROM CIS2.VW_DATA_ALL D inner join CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
                          inner join CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM   
                          LEFT JOIN CIS2.X_BAZA_SONDAJ BS ON (D.CUIIO=BS.CUIIO AND BS.ANUL=2025)     
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
   
  
--AND D.RIND LIKE  ('1.7%')
  GROUP BY 
    D.CUIIO,
    R.IDNO,
    R.CUATM,
    R.DENUMIRE,
    BS.CIF_IT,
    BS.PERS_IT
   
    HAVING
    
    (NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.1')  THEN COL1 ELSE 0 END)) > 0
    OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.2')  THEN COL1 ELSE 0 END)) > 0
    OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.3')  THEN COL1 ELSE 0 END)) > 0
        OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.4')  THEN COL1 ELSE 0 END)) > 0
        OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.5')  THEN COL1 ELSE 0 END)) > 0
        OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.6')  THEN COL1 ELSE 0 END)) > 0
        OR 
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND IN ('1.7.7')  THEN COL1 ELSE 0 END)) > 0
    )
    
    AND 
    
    (NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND LIKE  ('1.1%')  THEN COL1 ELSE 0 END)) = 0
    AND  
    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND LIKE  ('1.5%')  THEN COL1 ELSE 0 END)) = 0
--    AND  
--    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND LIKE  ('1.3%')  THEN COL1 ELSE 0 END)) = 0
--    AND  
--    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND LIKE  ('1.4%')  THEN COL1 ELSE 0 END)) = 0
--    AND  
--    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND NOT IN ('1.7.5')  THEN COL1 ELSE 0 END)) = 0
--    AND  
--    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND NOT IN ('1.7.6')  THEN COL1 ELSE 0 END)) = 0
--        OR 
--    NVAL(SUM(CASE WHEN D.CAPITOL = 1040 AND D.RIND NOT IN ('1.7.7')  THEN COL1 ELSE 0 END)) = 0
     )
    
     
    ORDER BY 
    R.CUATM