INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3
  
)


SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
'0' AS  NR_SECTIE,
'0' AS  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2,
 NR_ROW ||'~'||CNT NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3

FROM

(
SELECT 
ROWNUM CNT,
CASE WHEN (D.COL2 + D.COL3 + D.COL4) = 0 THEN NULL ELSE (D.COL2 + D.COL3 + D.COL4)  END NR_ROW,
D.ORDINE,
'0000' AS DECIMAL_POS, 
D.NUME_ROW,
CASE WHEN (D.COL2) = 0 THEN NULL ELSE (D.COL2) END   AS COL1,
CASE WHEN (D.COL3) = 0 THEN NULL ELSE (D.COL3) END   AS COL2,
CASE WHEN (D.COL4) = 0 THEN NULL ELSE (D.COL4) END   AS COL3

FROM 
(
SELECT 
 
TR.ORDINE  AS NR_ROW,
TR.ORDINE  AS ORDINE,
 TR.RIND_DENUMIRE AS NUME_ROW,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.2') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL3,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1','1.1.2') AND (DD.has_112 + DD.has_111) = 2 AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) 
   AS COL4
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
  ---------------------------------------------------------
  INNER JOIN (
  SELECT
    CUIIO,
    CUIIO_VERS,

    MAX(CASE WHEN RIND = '1.1.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN RIND = '1.1.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    SUM(COL1) AS COL1

  FROM CIS2.VW_DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND RIND IN ('1.1.1','1.1.2')
    AND CAEM2 NOT LIKE 'A%'
--    AND CUIIO = 458963
  GROUP BY 
    CUIIO,
    CUIIO_VERS

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
  ------------------------------------------------------------  
            
  
            INNER JOIN (
            
SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') 




) C ON C.CODUL = D.CAEM2

CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
    SELECT 2 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
    SELECT 3 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
    SELECT 4 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
    SELECT 5 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL UNION  
    SELECT 6 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' AS ORDINE FROM DUAL UNION  
    SELECT 7 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ' AS RIND_DENUMIRE, '7' AS ORDINE FROM DUAL UNION  
    SELECT 8 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G' AS RIND, 'Comert cu ridicata ' AS RIND_DENUMIRE, '8' AS ORDINE FROM DUAL UNION  
    SELECT 9 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H' AS RIND, 'Transport si depozitare ' AS RIND_DENUMIRE, '9' AS ORDINE FROM DUAL UNION  
    SELECT 10 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J' AS RIND, 'Informatii si comunicatii' AS RIND_DENUMIRE, '10' AS ORDINE FROM DUAL UNION  
    SELECT 11 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K' AS RIND, 'Activitati  financiare si asigurari' AS RIND_DENUMIRE, '11' AS ORDINE FROM DUAL UNION  
    SELECT 12 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71' AS RIND, 'Activitati de arhitectura si inginerie' AS RIND_DENUMIRE, '12' AS ORDINE FROM DUAL UNION  
    SELECT 13 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72' AS RIND, 'Activitati de cercetare dezvoltare' AS RIND_DENUMIRE, '13' AS ORDINE FROM DUAL UNION  
    SELECT 14 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73' AS RIND, 'Publicitate si activitati de studiere a pietei' AS RIND_DENUMIRE, '14' AS ORDINE FROM DUAL   
    

  ) TR
            
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.RIND IN ('1.1.1','1.1.2')
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

--  A.CAEM2
ORDER BY
  TR.NR_TABLE,
  TR.ORDINE
  )  D
  
  )