SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2,
  DD.has_111,
  DD.has_112
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    CUIIO_VERS,

    MAX(CASE WHEN RIND = '1.1.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN RIND = '1.1.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    SUM(COL1) AS COL1

  FROM CIS2.VW_DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND RIND IN ('1.1.1','1.1.2')
    AND CAEM2 NOT LIKE 'A%'
--    AND CUIIO = 458963
  GROUP BY 
    CUIIO,
    CUIIO_VERS

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2','1.2.1','1.2.2')
  AND D.CAEM2 NOT LIKE 'A%'
  AND D.CUIIO = 458963