SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
COL1 + COL2 + COL3 AS COL1,
COL1 AS COL2,
COL2 AS COL3,
COL3 AS COL4,

COL4 + COL5 + COL6 AS COL5,
COL4 AS COL6,
COL5 AS COL7,
COL6 AS COL8,

COL10 + COL11 + COL12 AS COL10,
COL10 AS COL11,
COL11 AS COL12,
COL12 AS COL13,

COL13 + COL14 + COL15 AS COL14,
COL13 AS COL15,
COL14 AS COL16,
COL15 AS COL17







FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL1,0) AS COL1,
  ROUND(A.COL2,0) AS COL2,
  ROUND(A.COL3,0) AS COL3,
  
  ROUND(A.COL4,0) AS COL4,
  ROUND(A.COL5,0) AS COL5,
  ROUND(A.COL6,0) AS COL6,
  
  ROUND(A.COL7,0) AS COL7,
  ROUND(A.COL8,0) AS COL8,
  ROUND(A.COL9,0) AS COL9,
  
  ROUND(A.COL10,0) AS COL10,
  ROUND(A.COL11,0) AS COL11,
  ROUND(A.COL12,0) AS COL12,
  
  ROUND(A.COL13,0) AS COL13,
  ROUND(A.COL14,0) AS COL14,
  ROUND(A.COL15,0) AS COL15
 
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2') AND NVAL(A.COL1) = 1  AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 =0    )    AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN A.RIND LIKE ('1.5.%')  AND NVAL(A.COL1) = 1  AND (A.has_112 +   A.has_111 = 0  )  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  THEN A.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(A.COL1) = 1 

 AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 > 0)  AND  (A.has_112 + A.has_111 > 0)  
 AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  THEN A.CUIIO END) AS COL3,
  
  
  --------------------------------------------------------
  
    COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2') AND NVAL(A.COL1) = 1  
    AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 =0    )    
    AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
    AND CU.FULL_CODE  LIKE '%'||'1111111'||';%' 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL4,
 
  COUNT(DISTINCT CASE WHEN A.RIND LIKE ('1.5.%')  AND NVAL(A.COL1) = 1  AND (A.has_112 +   A.has_111 = 0  )  
  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )
  AND CU.FULL_CODE  LIKE '%'||'1111111'||';%'    
  THEN A.CUIIO END) AS COL5,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(A.COL1) = 1 

 AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 > 0)  AND  (A.has_112 + A.has_111 > 0)  
 AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  AND CU.FULL_CODE  LIKE '%'||'1111111'||';%' 
  THEN A.CUIIO END) AS COL6,
  
  
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2') AND NVAL(A.COL1) = 1  
    AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 =0    )    
    AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
    AND CU.FULL_CODE  LIKE '%'||'2222222'||';%' 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL7,
 
  COUNT(DISTINCT CASE WHEN A.RIND LIKE ('1.5.%')  AND NVAL(A.COL1) = 1  AND (A.has_112 +   A.has_111 = 0  )  
  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )
  AND CU.FULL_CODE  LIKE '%'||'2222222'||';%'    
  THEN A.CUIIO END) AS COL8,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(A.COL1) = 1 

 AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 > 0)  AND  (A.has_112 + A.has_111 > 0)  
 AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  AND CU.FULL_CODE  LIKE '%'||'2222222'||';%' 
  THEN A.CUIIO END) AS COL9,
  
  
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2') AND NVAL(A.COL1) = 1  
    AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 =0    )    
    AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
    AND CU.FULL_CODE  LIKE '%'||'3333333'||';%' 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL10,
 
  COUNT(DISTINCT CASE WHEN A.RIND LIKE ('1.5.%')  AND NVAL(A.COL1) = 1  AND (A.has_112 +   A.has_111 = 0  )  
  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )
  AND CU.FULL_CODE  LIKE '%'||'3333333'||';%'    
  THEN A.CUIIO END) AS COL11,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(A.COL1) = 1 

 AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 > 0)  AND  (A.has_112 + A.has_111 > 0)  
 AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  AND CU.FULL_CODE  LIKE '%'||'3333333'||';%' 
  THEN A.CUIIO END) AS COL12,
  
  
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2') AND NVAL(A.COL1) = 1  
    AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 =0    )    
    AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
    AND CU.FULL_CODE  LIKE '%'||'9600000'||';%' 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL13,
 
  COUNT(DISTINCT CASE WHEN A.RIND LIKE ('1.5.%')  AND NVAL(A.COL1) = 1  AND (A.has_112 +   A.has_111 = 0  )  
  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )
  AND CU.FULL_CODE  LIKE '%'||'9600000'||';%'    
  THEN A.CUIIO END) AS COL14,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(A.COL1) = 1 

 AND (A.has_151 + A.has_152 + A.has_153 + A.has_154 + A.has_155 + A.has_156 + A.has_157 > 0)  AND  (A.has_112 + A.has_111 > 0)  
 AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL) 
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
  AND CU.FULL_CODE  LIKE '%'||'9600000'||';%' 
  THEN A.CUIIO END) AS COL15
  
  --------------------------------------------
  
  
 
  
FROM
(
SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2,
  DD.has_111,
  DD.has_112,
  DD.has_151,
  DD.has_152,
  DD.has_153,
  DD.has_154,
  DD.has_155,
  DD.has_156,
  DD.has_157
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    CUIIO_VERS,

    MAX(CASE WHEN RIND = '1.1.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN RIND = '1.1.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    MAX(CASE WHEN RIND = '1.5.1' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_151,
    MAX(CASE WHEN RIND = '1.5.2' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_152,
    MAX(CASE WHEN RIND = '1.5.3' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_153,
    MAX(CASE WHEN RIND = '1.5.4' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_154,
    MAX(CASE WHEN RIND = '1.5.5' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_155,
    MAX(CASE WHEN RIND = '1.5.6' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_156,
    MAX(CASE WHEN RIND = '1.5.7' AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_157,
    SUM(COL1) AS COL1

  FROM CIS2.VW_DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND 
    
    (RIND LIKE ('1.1.%') OR RIND LIKE ('1.5.%')) 
    
    
    AND CAEM2 NOT LIKE 'A%'
   -- AND CUIIO = 458963
  GROUP BY 
    CUIIO,
    CUIIO_VERS

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  (D.RIND LIKE ('1.1.%') OR D.RIND LIKE ('1.5.%')) 
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 400053
  
) A LEFT JOIN
 
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  INNER JOIN  CIS2.VW_CL_CUATM  CU ON CU.CODUL = A.CUATM
  INNER JOIN (SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') ) C ON C.CODUL = A.CAEM2
  CROSS JOIN 
(

   
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
 --   SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '2' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '3' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '4' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '5' AS ORDINE  , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '6' AS ORDINE, 'B+C+D+E' AS RIND_C  FROM DUAL UNION
  --  SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '7' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '8' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '9' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '10' AS ORDINE  , 'B+C+D+E' AS RIND_C FROM DUAL UNION 
    
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '11' AS ORDINE, 'H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
   -- SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '12' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE,  0 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '13' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '14' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '15' AS ORDINE  , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL
    
  ) TR
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

) A

  
 )
 
 
 ORDER BY
 TO_NUMBER(ORDINE) 
 