
SELECT
        TR.NR_TABLE,
        TR.TABLE_DENUMIRE,
        TR.RIND_DENUMIRE,
        TR.ORDINE,
        TR.RIND,
        COL4 AS COL1,
        NVAL(COL1) + NVAL(COL2) + NVAL(COL3)  AS COL2,
        COL1 AS COL3,
        COL2 AS COL4,
        COL3 AS COL5
        FROM
(
SELECT
        TR.NR_TABLE,
        TR.TABLE_DENUMIRE,
        TR.RIND_DENUMIRE,
        TR.ORDINE,
        TR.RIND,
        SUM(CASE WHEN ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
             AND (TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL1 ELSE NULL END ) AS COL1,
      SUM(CASE WHEN ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
             AND (TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL2 ELSE NULL END ) AS COL2,
       SUM(CASE WHEN ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
             AND (TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL3 ELSE NULL END ) AS COL3,
    COUNT(DISTINCT CASE WHEN ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
             AND (TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND_C LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.CUIIO  ELSE NULL END ) AS COL4
FROM
(
SELECT
        D.CUIIO,
        D.CAEM2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL1) / 100,1) AS COL1,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL2) / 100,1) AS COL2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL3) / 100,1) AS COL3
        
        
        FROM
        
(
SELECT
        D.CUIIO,
        D.CAEM2,
        SUM(CASE WHEN D.RIND = '1.3.1' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL1,
        SUM(CASE WHEN D.RIND = '1.3.2' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL2,
        SUM(CASE WHEN D.RIND = '1.3.3' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL3
     FROM 
        CIS2.VW_DATA_ALL D
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM     IN (:pFORM) AND 
        D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
        D.RIND IN ('1.3.1','1.3.2','1.3.3') AND
        D.CAEM2 NOT LIKE 'A%'
      --  AND D.CUIIO = 40585950

GROUP BY 
D.CUIIO,
D.CAEM2

) D  LEFT JOIN (
SELECT 
DISTINCT CUIIO,
COL2
FROM 
(
SELECT 
   DISTINCT D.CUIIO,
   SUM(D.COL2) AS COL2 
   FROM CIS2.DATA_ALL_FR D
   WHERE
   D.FORM = 57 
 -- AND D.CUIIO =  40585950
AND D.PERIOADA = 2013
AND D.FORM_VERS = 2009
AND D.ID_MD IN (62206)   --62206
GROUP BY 
D.CUIIO
HAVING 
SUM(D.COL2) IS NOT NULL 
UNION 
SELECT 
DISTINCT D.CUIIO,
SUM(D.COL2) AS COL2 
FROM CIS2.VW_DATA_ALL_FR D
WHERE
D.FORM = 63 
-- AND D.CUIIO =  5523 
AND D.PERIOADA = 2013
--AND D.capitol= 1121  
AND D.ID_MD IN (61891) -- 61891
GROUP BY 
D.CUIIO
HAVING
SUM(D.COL2) IS NOT NULL 
)
) DD ON DD.CUIIO = D.CUIIO
 

GROUP BY
 D.CUIIO,
 D.CAEM2
) D
 
     INNER JOIN (
        SELECT CODUL, FULL_CODE 
        FROM CIS2.VW_CL_CAEM2
        WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') 
           OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
      ) C ON C.CODUL = D.CAEM2
        
       LEFT JOIN CIS2.X_BAZA_SONDAJ BS ON (D.CUIIO=BS.CUIIO AND BS.ANUL=2025)  
       
       CROSS JOIN 
      (
        SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
      --  SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',        '2',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 0, 49, NULL, '10-49 salariati',       '3',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',      '4',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','5','B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Industrie - total','6',  'B+C+D+E' FROM DUAL UNION
     --   SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '7',  'B+C+D+E' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 0, 49, NULL, '10-49 salariati',     '8',  'B+C+D+E' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '9',  'B+C+D+E' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati', '10','B+C+D+E' FROM DUAL UNION 
        SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Servicii - total', '11','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
     --   SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '12','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 0, 49, NULL, '10-49 salariati',     '13','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '14','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
        SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','15','H+J+K+G46+M71+M72+M73' FROM DUAL
      ) TR
      
      
       GROUP BY
        TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND
        
        ) TR
        
     