SELECT
  3 AS NR_TABLE, 
  ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
  RIND_DENUMIRE,
  ORDINE,
  RIND,
        COL4 AS COL1,
        NVAL(COL1) + NVAL(COL2) + NVAL(COL3)  AS COL2,
        COL1 AS COL3,
        COL2 AS COL4,
        COL3 AS COL5
        FROM
(
SELECT
    NUME_ROW AS RIND_DENUMIRE,
  NR_ROW AS ORDINE,
  CS_CUATM AS RIND,
        SUM(CASE WHEN 
             C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%'
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  
             
             THEN  D.COL1 ELSE NULL END ) AS COL1,
             
      SUM(CASE WHEN 
              
              C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
              
              
              THEN D.COL2 ELSE NULL END ) AS COL2,
       SUM(CASE WHEN 
              
              C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%'  
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
              
              
              THEN D.COL3 ELSE NULL END ) AS COL3,
    COUNT(DISTINCT CASE WHEN 
              
              C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
              
              
              THEN D.CUIIO  ELSE NULL END ) AS COL4
FROM
(
SELECT
        D.CUIIO,
        D.CUATM,
        D.CAEM2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL1) / 100,1) AS COL1,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL2) / 100,1) AS COL2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL3) / 100,1) AS COL3
        
        
        FROM
        
(
SELECT
        D.CUIIO,
        D.CUATM,
        D.CAEM2,
        SUM(CASE WHEN D.RIND = '1.3.1' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL1,
        SUM(CASE WHEN D.RIND = '1.3.2' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL2,
        SUM(CASE WHEN D.RIND = '1.3.3' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL3
     FROM 
        CIS2.VW_DATA_ALL D
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM     IN (:pFORM) AND 
        D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
        D.RIND IN ('1.3.1','1.3.2','1.3.3') AND
        D.CAEM2 NOT LIKE 'A%'
      --  AND D.CUIIO = 40585950

GROUP BY 
D.CUIIO,
D.CUATM,
D.CAEM2

) D  LEFT JOIN (
SELECT 
DISTINCT CUIIO,
COL2
FROM 
(
SELECT 
   DISTINCT D.CUIIO,
   SUM(D.COL2) AS COL2 
   FROM CIS2.DATA_ALL_FR D
   WHERE
   D.FORM = 57 
 -- AND D.CUIIO =  40585950
AND D.PERIOADA = 2013
AND D.FORM_VERS = 2009
AND D.ID_MD IN (62206)   --62206
GROUP BY 
D.CUIIO
HAVING 
SUM(D.COL2) IS NOT NULL 
UNION 
SELECT 
DISTINCT D.CUIIO,
SUM(D.COL2) AS COL2 
FROM CIS2.VW_DATA_ALL_FR D
WHERE
D.FORM = 63 
-- AND D.CUIIO =  5523 
AND D.PERIOADA = 2013
--AND D.capitol= 1121  
AND D.ID_MD IN (61891) -- 61891
GROUP BY 
D.CUIIO
HAVING
SUM(D.COL2) IS NOT NULL 
)
) DD ON DD.CUIIO = D.CUIIO
 

GROUP BY
 D.CUIIO,
 D.CUATM,
 D.CAEM2
) D
 
     
         INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
        
       
       CROSS JOIN 
      (
        SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE  FROM  DUAL UNION  
            SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '2' AS ORDINE   FROM  DUAL UNION
            SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '3' AS ORDINE   FROM  DUAL UNION 
            SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '4' AS ORDINE   FROM  DUAL UNION
            SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '5' AS ORDINE   FROM  DUAL UNION
            SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '6' AS ORDINE   FROM   DUAL UNION 
            
            SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '7' AS ORDINE  FROM  DUAL UNION  
            SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '8' AS ORDINE   FROM  DUAL UNION
            SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '9' AS ORDINE   FROM  DUAL UNION 
            SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '10' AS ORDINE   FROM  DUAL UNION
            SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '11' AS ORDINE   FROM  DUAL UNION
            SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '12' AS ORDINE   FROM   DUAL UNION
            
            SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '13' AS ORDINE  FROM  DUAL UNION  
            SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '14' AS ORDINE   FROM  DUAL UNION
            SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '15' AS ORDINE   FROM  DUAL UNION 
            SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '16' AS ORDINE   FROM  DUAL UNION
            SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '17' AS ORDINE   FROM  DUAL UNION
            SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '18' AS ORDINE   FROM   DUAL 
            
      ) CC
      
      
       GROUP BY
          CC.NR_ROW,
  CC.NUME_ROW,
  CC.ORDINE,
  CC.CS_CUATM
        
        ) T
       