SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
COL1, COL2,COL3,COL4
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND((A.COL1 + A.COL2 + A.COL3),0) AS COL1,
  ROUND(A.COL1,0) AS COL2,
  ROUND(A.COL2,0) AS COL3,
  ROUND(A.COL3,0) AS COL4
 
FROM
(
SELECT 
 
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1','1.1.2') AND NVAL(D.COL1)  >=  1  AND (DD.has_151 + DD.has_152 + DD.has_153 + DD.has_154 + DD.has_155 + DD.has_156 + DD.has_157 =0    )  
  AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN D.RIND LIKE ('1.5.%')  AND NVAL(D.COL1) >= 1  AND (DD.has_112 + DD.has_111 = 0  ) AND 
   ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(D.COL1) >= 1  
  
  AND (DD.has_151 + DD.has_152 + DD.has_153 + DD.has_154 + DD.has_155 + DD.has_156 + DD.has_157 > 0)  AND  (DD.has_112 + DD.has_111 > 0)
  AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) 
   AS COL3
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
  ---------------------------------------------------------
  INNER JOIN (
  
  SELECT
  D.ANUL,
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2,
  DD.has_111,
  DD.has_112,
  DD.has_151,
  DD.has_152,
  DD.has_153,
  DD.has_154,
  DD.has_155,
  DD.has_156,
  DD.has_157
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    MAX(CUIIO_VERS) CUIIO_VERS,

    MAX(CASE WHEN ID_MD = 83509 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN ID_MD = 83504 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    MAX(CASE WHEN ID_MD = 83532 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_151,
    MAX(CASE WHEN ID_MD = 83533 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_152,
    MAX(CASE WHEN ID_MD = 83534 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_153,
    MAX(CASE WHEN ID_MD = 83535 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_154,
    MAX(CASE WHEN ID_MD = 83536 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_155,
    MAX(CASE WHEN ID_MD = 83537 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_156,
    MAX(CASE WHEN ID_MD = 83538 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_157
    

  FROM CIS2.DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND 
    ID_MD IN (83509,83504,83532,83533,83534,83535,83536,83537,83538)
     
    
    
 
  GROUP BY 
    CUIIO
  
    

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 400053
  

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
  ------------------------------------------------------------  
            
  
            INNER JOIN (
            
SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') 




) C ON C.CODUL = D.CAEM2

CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, 1 AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'B Industria extractiva B00=B05+B06+B07+B08+B09' AS RIND_DENUMIRE, 2 AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '05' AS RIND, 'B05   Extractia carbunelui superior si inferior' AS RIND_DENUMIRE, 3 AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '06' AS RIND, 'B06   Extractia petrolului brut si a gazelor naturale' AS RIND_DENUMIRE, 4 AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '07' AS RIND, 'B07   Extractia minereurilor metalifere' AS RIND_DENUMIRE, 5 AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '08' AS RIND, 'B08   Alte activitati extractive' AS RIND_DENUMIRE, 6 AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '09' AS RIND, 'B09   Activitati de servicii anexe extractiei' AS RIND_DENUMIRE, 7 AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'C Industria prelucratoare' AS RIND_DENUMIRE, 9 AS ORDINE FROM DUAL UNION   
       
    
   
    

  ) TR
            
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
 (D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')) 
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  GROUP BY
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

--  A.CAEM2
ORDER BY
  TR.NR_TABLE,
  TO_NUMBER(TR.ORDINE)
  )  A
  
  ) 