SELECT
        TO_NUMBER(TR.NR_TABLE) NR_TABLE,
        TR.TABLE_DENUMIRE,
        TR.RIND_DENUMIRE,
        TO_NUMBER(TR.ORDINE) ORDINE,
        TR.RIND,
        COL4 AS COL1,
        NVAL(COL1) + NVAL(COL2) + NVAL(COL3)  AS COL2,
        COL1 AS COL3,
        COL2 AS COL4,
        COL3 AS COL5
        FROM
(
SELECT
        TR.NR_TABLE,
        TR.TABLE_DENUMIRE,
        TR.RIND_DENUMIRE,
        TR.ORDINE,
        TR.RIND,
        SUM(CASE WHEN 
             (TR.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL1 ELSE NULL END ) AS COL1,
             
      SUM(CASE WHEN 
              (TR.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL2 ELSE NULL END ) AS COL2,
       SUM(CASE WHEN 
              (TR.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.COL3 ELSE NULL END ) AS COL3,
    COUNT(DISTINCT CASE WHEN 
              (TR.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%') THEN D.CUIIO  ELSE NULL END ) AS COL4
FROM
(
SELECT
        D.CUIIO,
        D.CAEM2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL1) / 100,1) AS COL1,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL2) / 100,1) AS COL2,
        ROUND(SUM(DD.COL2) / 1000 * SUM(D.COL3) / 100,1) AS COL3
        
        
        FROM
        
(
SELECT
        D.CUIIO,
        D.CAEM2,
        SUM(CASE WHEN D.RIND = '1.3.1' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL1,
        SUM(CASE WHEN D.RIND = '1.3.2' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL2,
        SUM(CASE WHEN D.RIND = '1.3.3' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL3
     FROM 
        CIS2.VW_DATA_ALL D
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM     IN (:pFORM) AND 
        D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
        D.RIND IN ('1.3.1','1.3.2','1.3.3') AND
        D.CAEM2 NOT LIKE 'A%'
      --  AND D.CUIIO = 40585950

GROUP BY 
D.CUIIO,
D.CAEM2

) D  LEFT JOIN (
SELECT 
DISTINCT CUIIO,
COL2
FROM 
(
SELECT 
   DISTINCT D.CUIIO,
   SUM(D.COL2) AS COL2 
   FROM CIS2.DATA_ALL_FR D
   WHERE
   D.FORM = 57 
 -- AND D.CUIIO =  40585950
AND D.PERIOADA = 2013
AND D.FORM_VERS = 2009
AND D.ID_MD IN (62206)   --62206
GROUP BY 
D.CUIIO
HAVING 
SUM(D.COL2) IS NOT NULL 
UNION 
SELECT 
DISTINCT D.CUIIO,
SUM(D.COL2) AS COL2 
FROM CIS2.VW_DATA_ALL_FR D
WHERE
D.FORM = 63 
-- AND D.CUIIO =  5523 
AND D.PERIOADA = 2013
--AND D.capitol= 1121  
AND D.ID_MD IN (61891) -- 61891
GROUP BY 
D.CUIIO
HAVING
SUM(D.COL2) IS NOT NULL 
)
) DD ON DD.CUIIO = D.CUIIO
 

GROUP BY
 D.CUIIO,
 D.CAEM2
) D
 
     INNER JOIN (
        SELECT CODUL, FULL_CODE 
        FROM CIS2.VW_CL_CAEM2
        WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') 
           OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
      ) C ON C.CODUL = D.CAEM2
        
        
       
       CROSS JOIN 
      (
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ' AS RIND_DENUMIRE, '7' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G' AS RIND, 'Comert cu ridicata ' AS RIND_DENUMIRE, '8' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H' AS RIND, 'Transport si depozitare ' AS RIND_DENUMIRE, '9' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J' AS RIND, 'Informatii si comunicatii' AS RIND_DENUMIRE, '10' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K' AS RIND, 'Activitati  financiare si asigurari' AS RIND_DENUMIRE, '11' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71' AS RIND, 'Activitati de arhitectura si inginerie' AS RIND_DENUMIRE, '12' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72' AS RIND, 'Activitati de cercetare dezvoltare' AS RIND_DENUMIRE, '13' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73' AS RIND, 'Publicitate si activitati de studiere a pietei' AS RIND_DENUMIRE, '14' AS ORDINE FROM DUAL   
      ) TR
      
      
       GROUP BY
        TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND
        
        ) TR
       