DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW  NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5,
    DF.COL6
    
  

   
FROM 
(


--------------------------------------------------------------------------------
  
SELECT
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,   
  
  VB.FULL_CODE AS NR_SECTIE,                                                         
  VB.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
VB.COL1||'~'||VB.ORDINE||'~'||VB.FULL_CODE AS NR_ROW,
  VB.ORDINE,
  '000000' AS DECIMAL_POS,
  VB.DENUMIRE AS NUME_ROW,
--  DENUMIRE,
--  ORDINE,
--  COL1,
  VB.COL2 AS COL1,
  VB.COL3 AS COL2,
  VB.COL4 AS COL3,
  VB.COL5 AS COL4,
  VB.COL6 AS COL5,
  VB.COL7 AS COL6
 
FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CFP,
  T.FULL_CODE,
  T.CFP_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
 -- SUM(CASE WHEN D.CAPITOL IN (1010) THEN D.COL1_S ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN  DD.CNT  ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R202_2 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R203_2 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R204_2 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R205_2 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R516_1 ELSE NULL END) AS COL7
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_3 ELSE NULL END) AS COL7,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R206_1 ELSE NULL END) AS COL8,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R207_1 ELSE NULL END) AS COL9
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
     (D.PERIOADA =:pPERIOADA) AND 
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       --  AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
      (D.PERIOADA =:pPERIOADA) AND   
      (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')
       --  AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CFP C ON  (C.CODUL=A.CFP)
  INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CFP,
  D.CAPITOL,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') AND CIS2.NVAL(D.COL2) > 0 THEN 1 END) AS CNT,  
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R201_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R201_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R201_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R202_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R202_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R202_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R203_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R203_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R203_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R204_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R204_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R204_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R205_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R205_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R205_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R206_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R206_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R206_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R207_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R207_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R207_3,
  
  SUM(CASE WHEN D.CAPITOL IN (1016) AND D.RIND IN ('516') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R516_1
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1011,1016)
 --  AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CFP
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CFP,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM CIS2.MD_RIND_OUT D


  CROSS JOIN CIS2.VW_CL_CFP C
WHERE

  D.ID_MDTABLE = 14612 
  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CFP=D.CFP)

GROUP BY
  T.CFP,
  T.FULL_CODE,
  T.CFP_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE
  
UNION

SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CFP,
  A.FULL_CODE,
  A.CFP_DENUMIRE,
  A.DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) ORDINE,
--  A.RIND_D||'.'||A.RIND_S ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4,
  B.COL5,
  B.COL6,
  B.COL7
--  B.COL8,
--  B.COL9
FROM
(
SELECT
      C.CODUL AS CFP,
      C.FULL_CODE,
      C.DENUMIRE AS CFP_DENUMIRE, 
      B.RIND AS RIND_D,
      A.RIND AS RIND_S,
      B.ID_MD AS ID_MD_D,
      A.ID_MD AS ID_MD_S,
      B.CAPITOL,
      A.DENUMIRE,
      T.ORDINE
    FROM
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R 
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND IN ('1','2','3','4','5','6')
    ) A
    CROSS JOIN
    (
    SELECT
      R.RIND,
      R.DENUMIRE,
      R.ID_MD,
      R.CAPITOL,
      ROWNUM
    FROM
      CIS2.MD_RIND R
    WHERE
      R.FORM IN (20) AND
      R.CAPITOL IN (1010) AND
      R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')

    ) B
    CROSS JOIN CIS2.VW_CL_CFP C
    INNER JOIN
(
SELECT 
       D.ORDINE,
       D.RIND
       
       FROM CIS2.MD_RIND_OUT D
             
            WHERE 
   
      D.ID_MDTABLE = 14630



) T ON (T.RIND = B.RIND) 

    ORDER BY
      T.ORDINE,
      B.RIND,
      A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CFP,
  --SUM(CASE WHEN D.CAPITOL IN (1010) THEN D.COL1_S ELSE NULL END) AS COL1,
   SUM(CASE WHEN DD.CAPITOL IN (1011) THEN  DD.CNT  ELSE NULL END) AS COL1,
  
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R201_2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R202_2 ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R203_2 ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R204_2 ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R205_2 ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1016) THEN DD.R516_1 ELSE NULL END) AS COL7
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R206_1 ELSE NULL END) AS COL8,
--  SUM(CASE WHEN DD.CAPITOL IN (1011) THEN DD.R207_1 ELSE NULL END) AS COL9
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  C.CODUL AS CFP,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
    
    WHERE
      (D.PERIOADA =:pPERIOADA) AND   
     (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
     --    AND D.CUIIO = 458868
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CFP,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
    WHERE
    
     (D.PERIOADA =:pPERIOADA) AND   
    (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
      --   AND D.CUIIO = 458868
) B ON (A.CUIIO=B.CUIIO)
INNER JOIN CIS2.VW_CL_CFP C ON (A.CFP=C.CODUL)
--INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  C.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CFP,
  D.CAPITOL,
  SUM(CASE WHEN  D.CAPITOL IN (1011) AND D.RIND IN ('201') AND CIS2.NVAL(D.COL2) > 0 THEN 1 END) AS CNT,  
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R201_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R201_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('201') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R201_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R202_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R202_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('202') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R202_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R203_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R203_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('203') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R203_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R204_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R204_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('204') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R204_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R205_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R205_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('205') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R205_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R206_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R206_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('206') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R206_3,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R207_1,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL2) ELSE 0 END) AS R207_2,
  SUM(CASE WHEN D.CAPITOL IN (1011) AND D.RIND IN ('207') THEN CIS2.NVAL(D.COL3) ELSE 0 END) AS R207_3,
  SUM(CASE WHEN D.CAPITOL IN (1016) AND D.RIND IN ('516') THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS R516_1
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (20) AND
  D.CAPITOL IN (1011,1016)
   --  AND D.CUIIO = 458868
GROUP BY
  D.CUIIO,
  D.CFP,
  D.CAPITOL
) DD ON (D.CUIIO=DD.CUIIO)
  
  
 INNER JOIN CIS2.VW_CL_CFP C ON (D.CFP=C.CODUL)
 INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')

GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CFP=B.CFP)
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL
----ORDER BY
--  A.CUATM
  
) VB
ORDER BY
  FULL_CODE,
  ORDINE
  
  )  DF;
  
  
  BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
    
    CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5, COL6 -- , COL7
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5, CR.COL6 -- , CR.COL7
    );
  END LOOP;
END;
  
  
  
  