
SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
'0' AS NR_SECTIE,
'0' AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
COL1||'~'||ROWNUM NR_ROW,
ROWNUM AS ORDINE,
'0000' AS DECIMAL_POS, 
RIND_DENUMIRE AS NUME_ROW,
COL2 AS COL1,
COL3 AS COL2,
COL4 AS COL3


FROM
(

SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ROWNUM ORDINE,
COL1,
COL2 AS COL2,
COL3 AS COL3,
COL4 AS COL4

FROM 
(
SELECT 
2 AS NR_TABLE, 
'Clasa de marime' AS TABLE_DENUMIRE,
CC.RINDOUT  RIND_DENUMIRE,
CC.RIND full_code,   
  
  COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND NVAL(D.COL1) >= 1 
     THEN D.CUIIO END) AS COL1,
     
       COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND NVAL(D.COL1) >= 1 
       
        AND (ROUND(BS.PERS_IT) >= 0 AND ROUND(BS.PERS_IT) <= 49)
     THEN D.CUIIO END) AS COL2,
     
            COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND NVAL(D.COL1) >= 1 
       
        AND (ROUND(BS.PERS_IT) >= 50 AND ROUND(BS.PERS_IT) <= 249)
     THEN D.CUIIO END) AS COL3,
     
     
        COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND NVAL(D.COL1) >= 1 
       
        AND (ROUND(BS.PERS_IT) >= 250 AND ROUND(BS.PERS_IT) <= 9999999999999999)
     THEN D.CUIIO END) AS COL4
     
     
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
 
            LEFT JOIN
 
         CIS2.X_BAZA_SONDAJ BS ON (D.CUIIO=BS.CUIIO AND BS.ANUL=2025)
         
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
  
--            INNER JOIN  CIS2.VW_CL_CAEM2  C ON C.CODUL = D.CAEM2
--            INNER JOIN  CIS2.VW_CL_CAEM2  CC   ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'


             INNER JOIN  CIS2.MD_RIND_OUT  C ON C.RINDOUT = D.CAEM2 AND C.ID_MDTABLE = 14569 
            INNER JOIN  CIS2.MD_RIND_OUT  CC    ON C.RIND LIKE '%'||CC.RINDOUT||';%' AND CC.ID_MDTABLE = 14569  
  





    

WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  
 D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 458963
 
 --AND CC.CODUL IN ('00000')
 
 
--AND  CC.CODUL IN (
--SELECT 
--RIND AS CODUL
--FROM CIS2.MD_RIND_OUT
--WHERE
--ID_MDTABLE = 14569
--)
  GROUP BY
CC.RIND,
CC.RINDOUT  
ORDER BY
CC.RIND


  ))
  
  WHERE
  
  
  COL1 <> 0
  OR  
  COL2 <> 0
  OR 
  COL3 <> 0
  OR  
  COL4 <> 0  
  
  
  
  
  
  






