SELECT 
    D.CUIIO,
  --  D.CUIIO_VERS,
    D.RIND  RIND,
    
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
--    D.ID_MD,
--    D.RIND_VERS,

    
       SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL1) ELSE 0 END ) COL1,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL2) ELSE 0 END ) COL2,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL2) END)  COL3,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL3) END)  COL4,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL3) ELSE 0 END ) COL5,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL7) ELSE 0 END ) COL6,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL8) ELSE 0 END ) COL7,
   SUM (CASE WHEN 1=1   THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8) END) COL8,
   SUM (CASE WHEN 1=1   THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL9) END) COL9,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL9) ELSE 0 END ) COL10,
   SUM (CASE WHEN  1=1   THEN CIS2.NVAL(D.COL10) ELSE 0 END ) COL11,
   SUM (CASE WHEN  1=1   THEN CIS2.NVAL(D.COL11) ELSE 0 END ) COL12,
   SUM (CASE WHEN  1=1   THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL11) END) COL13,
   SUM (CASE WHEN 1=1   THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL12) END)  COL14,
   SUM (CASE WHEN  1=1  THEN CIS2.NVAL(D.COL12) ELSE 0 END ) COL15
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','070')
     
       )   
       
       
       GROUP BY 
    D.CUIIO,
 --   D.CUIIO_VERS,
    D.RIND
--       D.ID_MD,
--    D.RIND_VERS
       
--HAVING
--
--D.RIND LIKE '%7133.3%' 
--OR
--D.RIND LIKE '%7133.4%'  
--OR
--D.RIND LIKE '%732?.1%'  
--OR
--D.RIND LIKE '%732?.2%'  
--OR
--D.RIND LIKE '%732?.3%'
--OR
--D.RIND LIKE '%732?.4%'
--OR
--D.RIND LIKE '%732?.5%'
--OR
--D.RIND LIKE '%732?.6%'
--OR
--D.RIND LIKE '%732?.7%'
--OR
--D.RIND LIKE '%732?.8%'               
       
       ORDER BY 
      D.CUIIO,
      D.RIND