SELECT
   'Unul din Rind. (700,701,702,703,704,705) - trebuie > 0 '
  

    
   AS REZULTAT
  
FROM
 CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA IN(:PERIOADA)      ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS   OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD                OR :ID_MD = -1) AND
  (:CAPITOL=:CAPITOL             OR :CAPITOL <>  :CAPITOL) AND
  (:FORM = :FORM) AND  
  D.FORM    IN(5) AND D.CAPITOL IN (309,1222) 
  
  
HAVING
 NVAL(SUM(CASE WHEN D.CAPITOL IN (309) AND D.RIND IN ('890') THEN D.COL1 ELSE 0 END)) > 0
 
 AND 
 
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('700') THEN D.COL1 ELSE 0 END)) + 
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('701') THEN D.COL1 ELSE 0 END)) + 
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('702') THEN D.COL1 ELSE 0 END)) + 
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('703') THEN D.COL1 ELSE 0 END)) +
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('704') THEN D.COL1 ELSE 0 END)) +
 NVAL(SUM(CASE WHEN D.CAPITOL IN (1222) AND D.RIND IN ('704') THEN D.COL1 ELSE 0 END))  =  0