SELECT


'RIND. 1.3.1 = ' ||
  SUM(CASE WHEN D.CAPITOL IN 1040 AND D.RIND IN ('1.3.1') THEN CIS2.NVAL(COL1) ELSE 0 END) 
 AS REZULTAT

FROM
  CIS2.VW_DATA_ALL_TEMP D
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (48)  AND
  D.CAPITOL IN (1040) AND
  D.RIND IN ('1.3.1')
 GROUP BY D.RIND

HAVING
 SUM(CASE WHEN D.CAPITOL IN 1040 AND D.RIND IN ('1.3.1') THEN CIS2.NVAL(COL1) ELSE 0 END)> 0 
--