--DROP VIEW CIS2.VW_DATA_ALL_GC_COEF;
--
--/* Formatted on 3/11/2026 1:45:44 PM (QP5 v5.326) */
CREATE OR REPLACE FORCE VIEW USER_BANCU.VW_DATA_ALL_GC_COEF
(
    PERIOADA,
    ANUL,
    NUM,
    UNIT_CODE,
    UNIT_CODE_VERS,
    NR_GOSP,
    NR_MAPS,
    CUATM,
    CUATM_FULL,
    ADDRESS_1,
    ADDRESS_2,
    ADDRESS_3,
    ADDRESS_4,
    ENVIRONMENT,
    PACHET,
    FORM,
    FORM_VERS,
    FORM_DEN,
    CAPITOL,
    CAPITOL_VERS,
    CAPITOL_DEN,
    TAB,
    ID_MD,
    RIND,
    RIND_VERS,
    ID_USER,
    USER_NAME,
    DATA_REG,
    COL1,
    COL2,
    COL3,
    COL4,
    COL5,
    COL6,
    COL7,
    COL8,
    COL9,
    COL10,
    COL11,
    COL12,
    COL13,
    COL14,
    COL15,
    COL16,
    COL17,
    COL18,
    COL19,
    COL20,
    COL21,
    COL22,
    COL23,
    COL24,
    COL25,
    COL26,
    COL27,
    COL28,
    COL29,
    COL30
)
AS
    SELECT D.PERIOADA,
           D.ANUL,
           D.NUM,
           D.UNIT_CODE,
           D.UNIT_CODE_VERS,
           D.NR_GOSP,
           D.NR_MAPS,
           D.CUATM,
           D.CUATM_FULL,
           D.ADDRESS_1,
           D.ADDRESS_2,
           D.ADDRESS_3,
           D.ADDRESS_4,
           D.ENVIRONMENT,
           D.PACHET,
           D.FORM,
           D.FORM_VERS,
           D.FORM_DEN,
           D.CAPITOL,
           D.CAPITOL_VERS,
           D.CAPITOL_DEN,
           D.TAB,
           D.ID_MD,
           D.RIND,
           D.RIND_VERS,
           D.ID_USER,
           D.USER_NAME,
           D.DATA_REG,
           EXTND_GC (D.COL1,
                     D.CA,
                     D.ID_MD,
                     1)
               AS COL1,
           EXTND_GC (D.COL2,
                     D.CA,
                     D.ID_MD,
                     2)
               AS COL2,
           EXTND_GC (D.COL3,
                     D.CA,
                     D.ID_MD,
                     3)
               AS COL3,
           EXTND_GC (D.COL4,
                     D.CA,
                     D.ID_MD,
                     4)
               AS COL4,
           EXTND_GC (D.COL5,
                     D.CA,
                     D.ID_MD,
                     5)
               AS COL5,
           EXTND_GC (D.COL6,
                     D.CA,
                     D.ID_MD,
                     6)
               AS COL6,
           EXTND_GC (D.COL7,
                     D.CA,
                     D.ID_MD,
                     7)
               AS COL7,
           EXTND_GC (D.COL8,
                     D.CA,
                     D.ID_MD,
                     8)
               AS COL8,
           EXTND_GC (D.COL9,
                     D.CA,
                     D.ID_MD,
                     9)
               AS COL9,
           EXTND_GC (D.COL10,
                     D.CA,
                     D.ID_MD,
                     10)
               AS COL10,
           EXTND_GC (D.COL11,
                     D.CA,
                     D.ID_MD,
                     11)
               AS COL11,
           EXTND_GC (D.COL12,
                     D.CA,
                     D.ID_MD,
                     12)
               AS COL12,
           EXTND_GC (D.COL13,
                     D.CA,
                     D.ID_MD,
                     13)
               AS COL13,
           EXTND_GC (D.COL14,
                     D.CA,
                     D.ID_MD,
                     14)
               AS COL14,
           EXTND_GC (D.COL15,
                     D.CA,
                     D.ID_MD,
                     15)
               AS COL15,
           EXTND_GC (D.COL16,
                     D.CA,
                     D.ID_MD,
                     16)
               AS COL16,
           EXTND_GC (D.COL17,
                     D.CA,
                     D.ID_MD,
                     17)
               AS COL17,
           EXTND_GC (D.COL18,
                     D.CA,
                     D.ID_MD,
                     18)
               AS COL18,
           EXTND_GC (D.COL19,
                     D.CA,
                     D.ID_MD,
                     19)
               AS COL19,
           EXTND_GC (D.COL20,
                     D.CA,
                     D.ID_MD,
                     20)
               AS COL20,
           EXTND_GC (D.COL21,
                     D.CA,
                     D.ID_MD,
                     21)
               AS COL21,
           EXTND_GC (D.COL22,
                     D.CA,
                     D.ID_MD,
                     22)
               AS COL22,
           EXTND_GC (D.COL23,
                     D.CA,
                     D.ID_MD,
                     23)
               AS COL23,
           EXTND_GC (D.COL24,
                     D.CA,
                     D.ID_MD,
                     24)
               AS COL24,
           EXTND_GC (D.COL25,
                     D.CA,
                     D.ID_MD,
                     25)
               AS COL25,
           EXTND_GC (D.COL26,
                     D.CA,
                     D.ID_MD,
                     26)
               AS COL26,
           EXTND_GC (D.COL27,
                     D.CA,
                     D.ID_MD,
                     27)
               AS COL27,
           EXTND_GC (D.COL28,
                     D.CA,
                     D.ID_MD,
                     28)
               AS COL28,
           EXTND_GC (D.COL29,
                     D.CA,
                     D.ID_MD,
                     29)
               AS COL29,
           EXTND_GC (D.COL30,
                     D.CA,
                     D.ID_MD,
                     30)
               AS COL30
      FROM USER_BANCU.VW_DATA_ALL_GC_CALC D;


--GRANT SELECT ON CIS2.VW_DATA_ALL_GC_COEF TO USER_BANCU;
