SELECT 

NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ROWNUM ORDINE,
COL1,
NULL AS COL2,
NULL AS COL3,
NULL AS COL4

FROM 
(
SELECT 
3 AS NR_TABLE, 
'CAEM2' AS TABLE_DENUMIRE,
CC.CODUL RIND_DENUMIRE,
CC.full_code,  
  
  COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND NVAL(D.COL1) >= 1 
     THEN D.CUIIO END) AS COL1
     
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
 
            
  
            INNER JOIN  CIS2.VW_CL_CAEM2  C ON C.CODUL = D.CAEM2
            INNER JOIN  CIS2.VW_CL_CAEM2  CC   ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'






    

WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  
 D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')
  AND D.CAEM2 NOT LIKE 'A%'
 --AND D.CUIIO = 458963
 
 --AND CC.CODUL IN ('00000')
 
 
AND  CC.CODUL IN (
SELECT 
RIND AS CODUL
FROM CIS2.MD_RIND_OUT
WHERE
ID_MDTABLE = 14569
)
  GROUP BY
CC.CODUL,
CC.full_code  
ORDER BY
CC.full_code

  )
  