SELECT 
    3 AS NR_TABLE, 
    ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
    CC.NUME_ROW AS RIND_DENUMIRE,
    CC.NR_ROW   AS ORDINE,
    CC.CS_CUATM AS RIND,
    CC.NR_ROW   AS COL_KEY,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    THEN D.CUIIO END) AS COL1,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL2,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL3,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
     
    THEN D.CUIIO END) AS COL4,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL5,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL6,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL7,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL8,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL9,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL10,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL11,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL12,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL13,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL14,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL15,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL16,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL17,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL18,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL19,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
     AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL20,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL21,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL22,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL23,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL24,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL1)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    
    THEN D.CUIIO END) AS COL25,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL2)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL26,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL3)=1 AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL27,
    COUNT(DISTINCT CASE WHEN D.RIND LIKE '1.12%'  AND CU.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
    
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
    
    THEN D.CUIIO END) AS COL28 

  FROM 
    CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.VW_CL_CUATM  CU ON CU.CODUL = D.CUATM
    CROSS JOIN (
      SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1'  AS ORDINE FROM  DUAL UNION  
      SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '2'  FROM  DUAL UNION
      SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '3'  FROM  DUAL UNION 
      SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '4'  FROM  DUAL UNION
      SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '5'  FROM  DUAL UNION
      SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '6'  FROM   DUAL UNION 
      SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total', '7'  FROM  DUAL UNION  
      SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '8'  FROM  DUAL UNION
      SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '9'  FROM  DUAL UNION 
      SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '10' FROM  DUAL UNION
      SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '11' FROM  DUAL UNION
      SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '12' FROM   DUAL UNION
      SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total', '13' FROM  DUAL UNION  
      SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '14' FROM  DUAL UNION
      SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '15' FROM  DUAL UNION 
      SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '16' FROM  DUAL UNION
      SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '17' FROM  DUAL UNION
      SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '18' FROM   DUAL 

    ) CC
  WHERE
    D.PERIOADA IN (:pPERIOADA) AND
    D.FORM     IN (:pFORM) AND 
    D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
    D.RIND IN ('1.12.1','1.12.2','1.12.3','1.12.4','1.12.5','1.12.6','1.12.7','1.12.8','1.12.9') AND
    D.CAEM2 NOT LIKE 'A%' 
 
  GROUP BY 
    CC.NR_ROW, CC.NUME_ROW, CC.CS_CUATM
    
    ORDER BY
    CC.NR_ROW