SELECT 

(ROUND(NVAL(SUM(CASE WHEN D.RIND IN('500-978') THEN D.COL1 ELSE 0 END)),1) + 
ROUND(NVAL(SUM(CASE WHEN D.RIND IN('500-840') THEN D.COL1 ELSE 0 END)),1) + 
ROUND(NVAL(SUM(CASE WHEN D.RIND IN('500-642') THEN D.COL1 ELSE 0 END)),1) + 
ROUND(NVAL(SUM(CASE WHEN D.RIND IN('500-643') THEN D.COL1 ELSE 0 END)),1) +
ROUND(NVAL(SUM(CASE WHEN D.RIND IN('500-999') THEN D.COL1 ELSE 0 END)),1))  
 AS REZULTAT
FROM
CIS2.VW_DATA_ALL D            
                                      
WHERE
    (D.PERIOADA=:PERIOADA          ) AND
    (D.CUIIO=:CUIIO               ) AND
    (D.CUIIO_VERS=:CUIIO_VERS     ) AND
    (D.FORM=:FORM                 ) AND
    (D.FORM_VERS=:FORM_VERS  ) AND
    (D.CAPITOL_VERS=:CAPITOL_VERS ) AND
    (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND          
    D.FORM     IN(67) AND
    D.CAPITOL  IN(1141)
   

  
--  HAVING
--CIS2.NVAL(SUM(CASE WHEN D.RIND IN('500-978') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)ELSE 0 END))+
--CIS2.NVAL(SUM(CASE WHEN D.RIND IN('500-840') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)ELSE 0 END))


--<
--CIS2.NVAL(SUM(CASE WHEN D.RIND IN('501') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)ELSE 0 END))

