SELECT
DISTINCT
D.CUIIO,
D.CUATM,
D.CAPITOL_DEN,
D.CAPITOL,
MR.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10,
SUM(D.COL11) AS COL11,


SUM(D.COL12) AS COL12,
SUM(D.COL13) AS COL13,
SUM(D.COL14) AS COL14,
SUM(D.COL15) AS COL15,
SUM(D.COL16) AS COL16,
SUM(D.COL17) AS COL17,
SUM(D.COL18) AS COL18,
SUM(D.COL19) AS COL19,
SUM(D.COL20) AS COL20,
SUM(D.COL21) AS COL21,
SUM(D.COL22) AS COL22

FROM
USER_EREPORTING.DATA_ALL_PRIMIT D 
INNER JOIN CIS2.DATA_ALL  R  ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND D.FORM = R.FORM AND D.FORM = R.FORM  AND D.ID_MD = R.ID_MD AND D.ID_SCHEMA IN (2) 
INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD =  D.ID_MD

WHERE
D.PERIOADA = :pPERIOADA AND
D.FORM IN (:pFORM)
AND D.ID_SCHEMA IN (2)
 AND D.FORM_VERS IN (:pFORM_VERS)   
 

             AND D.DATA_REG  < TO_DATE('06/01/2026 00:00:00', 'MM/DD/YYYY HH24:MI:SS') 


GROUP BY
D.CUIIO,
D.CUATM,
MR.CAPITOL,
MR.RIND
ORDER BY
CUIIO,
CAPITOL