SELECT 
'Este completat rind 01 - 09 - Raportul nu trebui sa fie completat'
REZULTAT
FROM VW_DATA_ALL_GC D
WHERE
   (D.PERIOADA=:PERIOADA          ) AND
  (D.NR_GOSP=:NR_GOSP               ) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS  OR :UNIT_CODE_VERS = -1  ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL =:CAPITOL           OR :CAPITOL <> :CAPITOL ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1)  AND 
    D.FORM IN (61)   

--   (D.PERIOADA=:PERIOADA          ) AND
--  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
--  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
--  (D.FORM = :FORM               ) AND
--  (D.FORM_VERS=:FORM_VERS ) AND
--  (D. CAPITOL=:CAPITOL            OR :CAPITOL = -1 ) AND
--  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
--  (D.ID_MD=:ID_MD               OR :ID_MD = -1) 
--  

  HAVING 
  SUM (CASE WHEN D.CAPITOL IN (1114) AND D.RIND  IN ('1','2','3','4','5','6','7','8','9') THEN NVAL(D.COL1) ELSE 0 END ) > 0 
  AND 
  SUM(CASE WHEN  D.CAPITOL = 1110 THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END ) + 
SUM(CASE WHEN  D.CAPITOL = 1111 THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END ) +
SUM(CASE WHEN  D.CAPITOL = 1112 THEN NVAL(D.COL1) + NVAL(D.COL2)   + NVAL(D.COL3) + NVAL(D.COL4)  + NVAL(D.COL5) + NVAL(D.COL6)  + NVAL(D.COL7)  ELSE 0 END ) +
SUM(CASE WHEN  D.CAPITOL = 1113 THEN NVAL(D.COL1) + NVAL(D.COL2)   + NVAL(D.COL3) + NVAL(D.COL4)  + NVAL(D.COL5) + NVAL(D.COL6)  + NVAL(D.COL7)  
+ NVAL(D.COL8)  + NVAL(D.COL9)   + NVAL(D.COL10) + NVAL(D.COL11) ELSE 0 END ) > 0