SELECT  
'Rind.' ||D.RIND||' : '|| 'COL1 : ' ||
CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND BETWEEN ('010') AND ('090') AND  P.NUM IN  (3,4)  THEN NVAL(D.COL1)  ELSE NULL END)) || ', COL2 :'
|| CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND BETWEEN ('010') AND ('090') AND  P.NUM IN  (3,4)  THEN NVAL(D.COL2)  ELSE NULL END))
AS REZULTAT
   FROM
  CIS2.VW_DATA_ALL_GC D          
  INNER JOIN CIS2.VW_MD_PERIOADA P ON(P.PERIOADA=P.PERIOADA )

  WHERE
--   (D.PERIOADA=:PERIOADA          ) AND
--  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
--  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
--  (D.FORM = :FORM               ) AND
--  (D.FORM_VERS=:FORM_VERS ) AND
  (D. CAPITOL=:CAPITOL            OR :CAPITOL = -1 ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
--  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
--  
  
  (D.NR_GOSP=:NR_GOSP           ) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (:CAPITOL=:CAPITOL            ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS ) AND
  (D.ID_MD=:ID_MD               ) AND
  


  D.FORM IN (61)  
  AND D.CAPITOL IN ('1111') AND D.RIND BETWEEN ('010')  AND ('090') 
  GROUP BY 
   D.RIND
HAVING
CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND BETWEEN ('010') AND ('090') AND  D.PERIOADA=:PERIOADA  AND  P.NUM IN  (3,4)  THEN NVAL(D.COL1)  ELSE NULL END)) > 0

OR 

CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND BETWEEN ('010') AND ('090') AND  D.PERIOADA=:PERIOADA   AND  P.NUM IN  (3,4)  THEN NVAL(D.COL2)  ELSE NULL END)) > 0