SELECT 
D.UNIT_CODE,
R.RIND,
SUM(D.COL3) AS COL3,
SUM(D.COL1) AS COL1

FROM
  VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1110)
  AND R.RIND IN ('001')
 GROUP BY 
   D.UNIT_CODE,
   R.RIND
   
   ORDER BY
   D.UNIT_CODE,
   R.RIND
   
   
   -- 2482.4589 / 3 = 827.4
   -- 218920  / 827.4 = 264.5878