INSERT INTO  CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5 , COL6
    )

SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
     CC.CODUL  AS NR_SECTIE,
     CC.DENUMIRE AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
     '0' AS NUME_SECTIE2,
    MR.RIND||'~'||SUM(ROWNUM) AS NR_ROW, 
    MR.ORDINE ORDINE, 
    '111111' AS DECIMAL_POS,  
         MR.DENUMIRE NUME_ROW, 
         ROUND(SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)    THEN  D.COL1  ELSE NULL END),1) AS COL1,
         ROUND(SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)  THEN  D.COL1  ELSE NULL END) /
         NOZERO(NVAL(
         
         (SUM(CASE WHEN R.CAPITOL IN (1118) AND  D.RIND IN ('0') THEN D.COL1 ELSE NULL END) / 4) 
         
         )),1) AS COL2,
         
         
         ROUND(SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)  THEN  D.COL1  ELSE NULL END) /
         NOZERO(NVAL(
         
        (SUM(CASE WHEN R.CAPITOL IN (1118) AND  D.RIND IN ('TIP2') THEN D.COL1 ELSE NULL END) / 4)
         
         
         )),1) AS COL3,
         ROUND(
         
         (SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)  THEN  D.COL1  ELSE NULL END) /
         NOZERO(NVAL(SUM(CASE WHEN R.CAPITOL IN (1118) AND  D.RIND IN ('TIP3') THEN D.COL1 ELSE NULL END) /4)
         
         )),1) AS COL4, 
         
         
         ROUND((SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)  THEN  D.COL1  ELSE NULL END))  / (HH.COL3/3),1) AS COL5,
         ROUND((SUM(CASE WHEN  MR.RIND = R.RIND AND R.CAPITOL IN (1115)  THEN  D.COL1  ELSE NULL END)) / (HH.COL1/3),1) AS COL6
  
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
   INNER  JOIN CIS2.VW_CL_CUATM CT ON D.CUATM = CT.CODUL 
  INNER JOIN CIS2.VW_CL_CUATM CC ON CT.FULL_CODE LIKE '%'||CC.CODUL||';%'   
  CROSS JOIN (
  SELECT 
            
     RIND,
            DENUMIRE,
            ORDINE    
           
            FROM    MD_RIND
            
            WHERE 
            
            form = 62
            
            AND CAPITOL = 1115
            AND CAPITOL_VERS = 1044
           
        ) MR     
     

CROSS JOIN (
SELECT 
R.RIND,
SUM(D.COL3) AS COL3,
SUM(D.COL1) AS COL1

FROM
  VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1110)
  AND R.RIND IN ('001')
 GROUP BY 
   R.RIND
) HH
 WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (62)  AND
  D.CAPITOL IN (1115,1118)
   
   AND CC.PRGS IN ('2')

  GROUP BY 
  CC.CODUL,
  CC.DENUMIRE, 
  CC.FULL_CODE,
  MR.RIND,
  MR.ORDINE,
  MR.DENUMIRE,
  HH.COL1,
  HH.COL3
  
    
  ORDER BY
  CC.FULL_CODE,
  MR.ORDINE