SELECT
    R.RIND,
    R.ORDINE, 
    R.DENUMIRE NUME_ROW, 
         ROUND(SUM(CASE WHEN  1=1 THEN  D.COL1  ELSE NULL END),1) AS COL1,
         ROUND(SUM(CASE WHEN  1=1 THEN  D.COL1  ELSE NULL END) / (HH.COL3/3),1) AS COL2
         
  
FROM
  VW_DATA_ALL_GC  D
   INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
   INNER  JOIN CIS2.VW_CL_CUATM CT ON D.CUATM = CT.CODUL 
   
   CROSS JOIN (
SELECT 
R.RIND,
SUM(D.COL3) AS COL3,
SUM(D.COL1) AS COL1

FROM
  VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1110)
  AND R.RIND IN ('001')
 GROUP BY 
   R.RIND
) HH
  
   WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (62)  AND
  D.CAPITOL IN (1115)
  AND R.RIND IN ('6010')
  
  
  GROUP BY 
    R.RIND,
    R.ORDINE, 
    R.DENUMIRE,
    HH.COL1,
    HH.COL3 