SELECT 
      
      D.CUIIO,
      R.RIND,
      R.RIND_VERS 
     
     from CIS2.VW_DATA_ALL_FR D INNER JOIN CIS2.MD_RIND R ON R.ID_MD = D.ID_Md 
    
WHERE
D.FORM = 63
AND D.PERIOADA = 2013
CAPITOL IN  (1120
AND R.RIND_VERS = 2009