SELECT
'Rind 930 - '||NVAL(SUM( CASE WHEN D.RIND IN ('930')   THEN  D.COL1  ELSE 0 END))  
||'  Rind 940 - '||NVAL(SUM( CASE WHEN D.RIND IN ('940')   THEN  D.COL1  ELSE 0 END))
  
  AS REZULTAT
  


FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1)
  AND D.FORM IN (64)
  AND D.CAPITOL = 1214
  
  HAVING  
  

 (
 NVAL(SUM( CASE WHEN D.RIND IN ('930')   THEN  D.COL1  ELSE 0 END)) <>  0 
 AND 
 NVAL(SUM( CASE WHEN D.RIND IN ('940')   THEN  D.COL1  ELSE 0 END)) =  0
 )
 
 OR 
 
 (
 NVAL(SUM( CASE WHEN D.RIND IN ('930')   THEN  D.COL1  ELSE 0 END)) =   0 
 AND 
 NVAL(SUM( CASE WHEN D.RIND IN ('940')   THEN  D.COL1  ELSE 0 END)) <>   0
 )