SELECT 
'CAEM2 - ' ||MAX(L.COL31)||'  dar r. 100 si r. 120  si r.200 = ' ||R.COL1  AS REZULTAT

FROM
(
SELECT 
D.CUIIO,
D.RIND,
D.COL31

  FROM

 CIS2.VW_DATA_ALL D  
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS<>:CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.CAPITOL IN (1127) AND D.RIND NOT IN ('400')
  AND D.FORM = 64
GROUP BY 
D.COL31,
D.RIND,
D.CUIIO

HAVING
D.COL31  IN  (
       SELECT 

            SUBSTR(CODUL,2,4) AS COL3
                
                FROM  CIS2.VW_CL_CAEM2
                
                WHERE 
                PRIM IN ('1')
                
                AND 
                (
                SUBSTR(CODUL,2,2)  IN ('56')
                ) 
                
 
) )L LEFT JOIN (

SELECT 
D.CUIIO,
SUM(CASE WHEN CAPITOL IN (1124) AND D.RIND IN ('100')  THEN  NVAL(D.COL1)  ELSE 0 END) +
SUM(CASE WHEN CAPITOL IN (1124) AND D.RIND IN ('120')  THEN  NVAL(D.COL1)  ELSE 0 END) + 
SUM(CASE WHEN CAPITOL IN (1125) AND D.RIND IN ('200')  THEN  NVAL(D.COL1)  ELSE 0 END) AS COL1


  FROM

 CIS2.VW_DATA_ALL D  
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS<>:CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM = 64
GROUP BY 
D.CUIIO

                





) R ON R.CUIIO = L.CUIIO 


GROUP BY 
--L.CUIIO,
--L.RIND,
--L.COL31,
R.COL1

HAVING 
MAX(L.COL31) IS NOT NULL 

AND 

R.COL1 = 0