SELECT

 'CAP.9 RIND - 980 - '||SUM( CASE WHEN D.RIND IN ('980')   THEN  D.COL1  ELSE NULL  END)||' nu este completat'   AS REZULTAT

 

        
FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <>  :CAPITOL ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
   D.FORM IN (64)

   
HAVING

NVAL(SUM (CASE WHEN D.CAPITOL  IN (100) AND D.RIND IN ('1') THEN D.COL1  ELSE null END))   =  1  

AND 

NVAL(SUM( CASE WHEN D.CAPITOL  IN (1214) AND D.RIND IN ('980')   THEN  D.COL1  ELSE NULL  END)) = 0 


