


SELECT 
--   RR.NR_ROW,
--   RR.NUME_ROW,
   CC.FULL_CODE,
  -- CC.DENUMIRE,
   CASE WHEN  CC.CODUL like '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
   CASE WHEN  Substr(CC.CODUL,1,1)||'0000' IS NOT NULL THEN Substr(CC.CODUL,1,1)||'0000' END AS CODUL, 
 --  CC.CODUL,
   CC.FULL_CODE AS ORDINE,
   
  
   
 ROUND(SUM ( CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN  DD.COL1 ELSE NULL END ),1) AS COL1
         

    FROM 
  (
-------------------------------------------------------------------------------
SELECT 
 
 DISTINCT D.CUIIO, 
 MAX( CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
 D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD')  THEN  D.COL1 ELSE 0 END))  AS COL0,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4) END))  AS COL1,
 

 
 (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS
 
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
 -- D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
--  AND D.CUIIO IN (40996334,41058201,37386492)

 GROUP BY D.CUIIO, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA
 
HAVING
--  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) >0
 )DD

-------------------------------------------------------------------------------

 INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR( C.CODUL,2,4)  = CASE WHEN DD.CAEM2_ACTUALIZAT IS NULL THEN DD.CAEM2 ELSE DD.CAEM2_ACTUALIZAT END
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON  (C.FULL_CODE LIKE '%'||CC.CODUL||';%') 
 


         
 WHERE 
  (DD.FORM=:pFORM) AND
  (DD.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
--  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) 
  --AND DD.CUIIO=227293
--  AND  C.CODUL LIKE 'A%'
 
   GROUP BY
   CC.FULL_CODE,
    CC.DENUMIRE,
   CC.CODUL
-- --   Substr(CC.CODUL,1,1),
--    RR.NR_ROW,       
--    RR.NUME_ROW
    
    ORDER BY 
  --  Substr(CC.CODUL,1,1),
    CC.CODUL