SELECT
    D.ANUL  AS ANUL,
    D.CUIIO  AS CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2,
    MAX(CASE WHEN D.CAPITOL IN (100)  AND D.RIND NOT IN ('CD','-') THEN D.RIND ELSE NULL END) AS CAP_SR,
    ROUND(MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END), 2) AS CAEM_ACT,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('293') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('293') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_293,
    
    
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2931') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2931') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2931,
    
        ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-1') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-1') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2106_1,
    
        ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-2') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-2') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2106_2,
    ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-3') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-3') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2106_3,
    
     ROUND(
        CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-4') THEN D.COL1 ELSE NULL END) = 0 THEN NULL
             ELSE SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2126-4') THEN D.COL1 ELSE NULL END)
        END
    , 2) AS RIND_2106_4
    
    
    
    
    
    
FROM
    CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
WHERE
    D.FORM IN (64)
    AND D.PERIOADA = :pPERIOADA
    AND D.CUATM_FULL LIKE '%' || :pCOD_CUATM || ';%'
    AND D.CAPITOL IN (1125, 1129,100,1200)
    
   
GROUP BY
    D.ANUL,
    D.CUIIO,
    R.IDNO,
    R.DENUMIRE,
    R.CUATM,
    R.CFP,
    R.CFOJ,
    R.CAEM2
ORDER BY
    D.CUIIO
