CREATE OR REPLACE FORCE VIEW USER_BANCU.EI_78_DATA_ALL_2024 AS
SELECT
  CUIIO,
  COL1,  COL2,  COL3,  COL4,  COL5,  COL6,  COL7,  COL8,  COL9,
  COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
  COL20, COL21, COL22, COL23, COL24, COL25, COL26, COL27, COL28, COL29,
  COL30, COL31, COL32, COL33, COL34, COL35, COL36, COL37
FROM (
  SELECT
      d.cuiio,

      -- COL1: 2.00.00
      SUM(CASE
              WHEN D.CAPITOL IN (405)
               AND REPLACE(' ' || CI.ITEM_PATH, ';', '; ') LIKE '% ' || '2.00.00' || ';%'
               AND D.RIND NOT IN ('1','-')
              THEN CIS2.NVAL(D.COL4) ELSE 0
          END) AS COL1,

      -- COL2..COL37
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.6.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL2,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.6.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL3,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.6.3'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL4,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.7.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL5,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.7.3'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL6,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.8.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL7,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.8.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL8,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.8.3'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL9,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'3.9'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL10,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'4.2.3'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL11,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.1.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL12,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.1.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL13,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.1.3'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL14,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.2'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL15,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.3'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL16,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.4.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL17,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'6.4.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL18,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'8.1'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL19,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'8.2'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL20,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'8.3'     ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL21,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'8.4.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL22,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'8.4.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL23,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'9.3.1'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL24,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'9.3.2'   ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL25,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.1.1.2'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL26,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.2.1.1'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL27,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.2.2.1'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL28,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.3.1.3'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL29,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.3.2.1'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL30,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.3.2.2'||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL31,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'10.3.3'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL32,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'11.1.1'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL33,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'11.1.2'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL34,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'11.2.1'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL35,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'11.2.2'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL36,
      SUM(CASE WHEN D.CAPITOL IN (405) AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||'11.2.3'  ||';%' AND D.RIND NOT IN ('1','-') THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL37
  FROM CIS2.VW_DATA_ALL D
  JOIN CIS2.VW_CLS_CLASS_ITEM CI
    ON CI.CLASS_CODE IN ('CSPM2')
   AND TRIM(D.COL31) = TRIM(CI.ITEM_CODE)
  WHERE
      (D.PERIOADA BETWEEN 1060 AND 1063)
  AND D.FORM = 44
  AND D.FORM_VERS = 1004
  AND D.CAPITOL IN (405)
  GROUP BY d.cuiio
)
WHERE GREATEST(
  ABS(COL1),  ABS(COL2),  ABS(COL3),  ABS(COL4),  ABS(COL5),  ABS(COL6),  ABS(COL7),  ABS(COL8),  ABS(COL9),
  ABS(COL10), ABS(COL11), ABS(COL12), ABS(COL13), ABS(COL14), ABS(COL15), ABS(COL16), ABS(COL17), ABS(COL18), ABS(COL19),
  ABS(COL20), ABS(COL21), ABS(COL22), ABS(COL23), ABS(COL24), ABS(COL25), ABS(COL26), ABS(COL27), ABS(COL28), ABS(COL29),
  ABS(COL30), ABS(COL31), ABS(COL32), ABS(COL33), ABS(COL34), ABS(COL35), ABS(COL36), ABS(COL37)
) > 0;
