
CREATE OR REPLACE FORCE VIEW USER_BANCU.CMPA_1_1

AS

SELECT 

    D.UNIT_CODE,
    COUNT(DISTINCT CASE WHEN D.RIND NOT IN ('TIP2', 'TIP3','0','-','CA')   THEN D.UNIT_CODE  ELSE NULL END) AS COL1

FROM
  CIS2.VW_DATA_ALL_GC  D
 
  


   
WHERE
  (D.PERIOADA IN (1066))  AND   
 
  D.FORM IN (58)  AND
  D.CAPITOL IN (419)
 
  
  GROUP BY 
  D.UNIT_CODE
  
  
  HAVING 
  
  COUNT(DISTINCT CASE WHEN D.RIND NOT IN ('TIP2', 'TIP3','0','-','CA')  THEN D.UNIT_CODE  ELSE NULL END) > 0 
  
  
  ORDER BY 
  
  D.UNIT_CODE