SELECT 
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('0')  THEN D.UNIT_CODE  ELSE NULL END) AS COL1,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP3')  THEN D.UNIT_CODE  ELSE NULL END) AS COL2,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP2')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL3,
    COUNT(DISTINCT CASE WHEN MR.RIND NOT IN ('TIP2', 'TIP3','0','-','CA')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL4
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)


   
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1114)
  AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
  



    
    

    
    
