
CREATE OR REPLACE FORCE VIEW USER_BANCU.CMPA_1_2

AS
SELECT 

    D.UNIT_CODE,
    COUNT(DISTINCT CASE WHEN D.RIND IN ('0')  THEN D.UNIT_CODE  ELSE NULL END) AS COL1

FROM
  CIS2.VW_DATA_ALL_GC  D
--  INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
--  INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)


   
WHERE
  (D.PERIOADA IN (1066))  AND   
  D.FORM IN (61)  AND
  D.CAPITOL IN (1114)

  GROUP BY 
  D.UNIT_CODE
  
  
  HAVING 
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('0')  THEN D.UNIT_CODE  ELSE NULL END) > 0 
  
  
  ORDER BY 
  
  D.UNIT_CODE