SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.RIND IN ('000') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R000_1,
  SUM(CASE WHEN MR.RIND IN ('000') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R000_3,
  SUM(CASE WHEN MR.RIND IN ('000') THEN CIS2.NVAL(D.COL5) ELSE NULL END) AS R000_5,
  SUM(CASE WHEN MR.RIND IN ('170') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R170_1,
  SUM(CASE WHEN MR.RIND IN ('170') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R170_2,
  SUM(CASE WHEN MR.RIND IN ('170') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R170_3,
  SUM(CASE WHEN MR.RIND IN ('180') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R180_1,
  SUM(CASE WHEN MR.RIND IN ('180') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R180_2,
  SUM(CASE WHEN MR.RIND IN ('180') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R180_3
  
FROM
   CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 
 
       
WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%' AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1017,1019)
    AND  D.CUIIO IN (38914777)

GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM
