DECLARE -- ====================================================================

  CURSOR C IS
  SELECT
    :pCOD_CUATM AS pCOD_CUATM
  FROM
    DUAL;

BEGIN -- ======================================================================
  FOR CR IN C
  LOOP
   IF CR.pCOD_CUATM = '0000000' THEN
---------------------------------------------------

    INSERT INTO TABLE_OUT
(   
    PERIOADA,
    FORM,
    FORM_VERS,
    ID_MDTABLE,
    COD_CUATM,
    NR_SECTIE,
    NUME_SECTIE,
    NR_SECTIE1,
    NUME_SECTIE1,
    NR_SECTIE2,
    NUME_SECTIE2,
    NR_ROW,
    ORDINE,
    DECIMAL_POS,
    NUME_ROW,
    COL1, COL2
)
------------------------------------------------------------------------------


SELECT
   :pPERIOADA AS PERIOADA,                                                    
   :pFORM AS FORM,                                                            
   :pFORM_VERS AS FORM_VERS,                                                  
   :pID_MDTABLE AS ID_MDTABLE,                                                
   :pCOD_CUATM AS COD_CUATM,   
   FF.FULL_CODE AS NR_SECTIE,                                                         
   FF.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  -- FF.COL2||'~'||FF.ORDINE AS NR_ROW,
   CASE WHEN INSTR(TO_CHAR(FF.COL2)||'~'||ROWNUM,'.',1) = 1 THEN 0||FF.COL2||'~'||ROWNUM ELSE FF.COL2||'~'||ROWNUM END AS NR_ROW,
   FF.ORDINE AS ORDINE,
  '11' AS DECIMAL_POS,
  FF.DENUMIRE AS NUME_ROW,
  FF.COL3  AS COL1,
  FF.COL4  AS COL2
FROM 
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  L.CUATM, 
  L.FULL_CODE,
  L.CUATM_DENUMIRE,
  L.DENUMIRE ,
  L.ORDINE,
  ROUND(L.COL1,1) AS COL1,
  ROUND((L.COL2/L.COL3) *100,1) AS COL2,
  ROUND((L.COL2/L.COL5) *100,1) AS COL3,
  ROUND((L.COL4/L.COL6) *100,1) AS COL4
FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM AS CUATM ,
  T.FULL_CODE AS FULL_CODE,
  T.CUATM_DENUMIRE AS CUATM_DENUMIRE,
  T.DENUMIRE AS DENUMIRE,
  T.ORDINE AS ORDINE, 
  
  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN  D.COL1_S  ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1017) THEN  DD.R000_4  ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R2002_2 * 28)  ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  DD.R210_2   ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R220_2 * 28)  ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R200_2 * 28)  ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  0  + 28  + 0 ELSE NULL END) AS COL7
  
 
FROM
(
-------------------------------------------------------------------


SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        -- INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND IN ('1','2','3','4','5','6')
      --  AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      -- AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) A
INNER JOIN
(      
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        -- INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      -- AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
   --    AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) B 
  ON A.CUIIO = B.CUIIO
 AND A.CUATM = B.CUATM
 AND A.CAPITOL = B.CAPITOL

INNER JOIN CIS2.VW_CL_CUATM C 
  ON A.CUATM = C.CODUL 

INNER JOIN CIS2.VW_CL_CUATM CC 
  ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'

WHERE
  CC.PRGS IN ('2')

GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL


-------------------------------------------------------------------

) D 
LEFT JOIN
(

SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R2002_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R2002_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R2002_3,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R230_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R230_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R230_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3

  
  
FROM CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 

  

WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  -- (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1017,1018)
  -- AND D.CUIIO IN (5921029)

  
GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM  
  
  
  
  
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D

  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  ID_MDTABLE = 14612 
  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE

  ) L
  
  GROUP BY
  L.CUATM,
  L.FULL_CODE,
  L.CUATM_DENUMIRE,
  L.DENUMIRE,
  L.ORDINE,
  L.COL1,
  L.COL2,
  L.COL3,
  L.COL4,
  L.COL5,
  L.COL6,
  L.COL7
  
  
  UNION 
  
  SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CUATM AS CUATM,
  A.FULL_CODE AS FULL_CODE,
  A.CUATM_DENUMIRE AS CUATM_DENUMIRE,
  A.DENUMIRE AS DENUMIRE,
  TO_NUMBER (A.ORDINE||'.'||A.RIND_S) AS ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4
 
  
FROM
(
SELECT
         C.CODUL AS CUATM,
         C.FULL_CODE,
        C.DENUMIRE AS CUATM_DENUMIRE,    
        B.RIND AS RIND_D,
  A.RIND AS RIND_S,
  B.ID_MD AS ID_MD_D,
  A.ID_MD AS ID_MD_S,
  B.CAPITOL,
  A.DENUMIRE,
  T.ORDINE
FROM
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND IN ('1','2','3','4','5','6')
) A
CROSS JOIN
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B
CROSS JOIN CIS2.VW_CL_CUATM C
INNER JOIN
(
SELECT
  ORDINE,
  RIND
FROM CIS2.MD_RIND_OUT
WHERE ID_MDTABLE = 14630
) T ON (T.RIND = B.RIND)
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
ORDER BY
  T.ORDINE,
  B.RIND,
  A.RIND
) A
LEFT JOIN
(
 SELECT
 LL.RIND_S AS RIND_S,
 LL.RIND_D AS RIND_D,
 LL.ID_MD_S AS ID_MD_S,
 LL.ID_MD_D AS ID_MD_D,
 LL.CUATM AS CUATM,
 ROUND (LL.COL1,1) AS COL1,
 ROUND((LL.COL2/LL.COL3) * 100,1) AS COL2,
 ROUND((LL.COL2/LL.COL5) * 100,1) AS COL3,
 ROUND((LL.COL4/LL.COL6) * 100,1) AS COL4
  
 FROM (
SELECT
  D.RIND_S  AS RIND_S,
  D.RIND_D  AS RIND_D,
  D.ID_MD_S AS ID_MD_S,
  D.ID_MD_D AS ID_MD_D,
  CC.CODUL  AS CUATM,
  
  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN  D.COL1_S  ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1017) THEN  DD.R000_4  ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R2002_2 * 28)  ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  DD.R210_2   ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R220_2 * 28)  ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R200_2 * 28)  ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  0  + 28  + 0 ELSE NULL END) AS COL7

    
FROM
(
------------------------------------------------------------------------------------------------------

SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        -- INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND IN ('1','2','3','4','5','6')
     ---  AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
     --  AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) A
INNER JOIN
(      
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        -- INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      -- AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      -- AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) B 
  ON A.CUIIO = B.CUIIO
 AND A.CUATM = B.CUATM
 AND A.CAPITOL = B.CAPITOL

INNER JOIN CIS2.VW_CL_CUATM C 
  ON A.CUATM = C.CODUL 

INNER JOIN CIS2.VW_CL_CUATM CC 
  ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'

WHERE
  CC.PRGS IN ('2')

GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL

  
  ----------------------------------------------------------------------------------------
) D
LEFT JOIN
(
---
SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R2002_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R2002_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R2002_3,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R230_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R230_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R230_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3

  
  
FROM CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 

  

WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  -- (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1017,1018)
  -- AND D.CUIIO IN (5921029)

  
GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM  
  
  ---  
  
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
  ) LL 
  
  GROUP BY 
  LL.RIND_S,
  LL.RIND_D,
  LL.ID_MD_S,
  LL.ID_MD_D,
  LL.CUATM,
  LL.COL1,
  LL.COL2,
  LL.COL3,
  LL.COL5,
  LL.COL4,
  LL.COL6,
  LL.COL7 
  
  
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D  AND A.CUATM=B.CUATM)
--WHERE
  
  ) FF
  
 -- ORDER BY
 -- FF.FULL_CODE,
 -- FF.ORDINE
  
  
---              -------------------------------------------------------------
  ;
   ELSE
---------------------------------

     INSERT INTO TABLE_OUT
(   
    PERIOADA,
    FORM,
    FORM_VERS,
    ID_MDTABLE,
    COD_CUATM,
    NR_SECTIE,
    NUME_SECTIE,
    NR_SECTIE1,
    NUME_SECTIE1,
    NR_SECTIE2,
    NUME_SECTIE2,
    NR_ROW,
    ORDINE,
    DECIMAL_POS,
    NUME_ROW,
    COL1, COL2
)


SELECT
   :pPERIOADA AS PERIOADA,                                                    
   :pFORM AS FORM,                                                            
   :pFORM_VERS AS FORM_VERS,                                                  
   :pID_MDTABLE AS ID_MDTABLE,                                                
   :pCOD_CUATM AS COD_CUATM,   
   FF.FULL_CODE AS NR_SECTIE,                                                         
   FF.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  -- FF.COL2||'~'||FF.ORDINE AS NR_ROW,
   CASE WHEN INSTR(TO_CHAR(FF.COL2)||'~'||ROWNUM,'.',1) = 1 THEN 0||FF.COL2||'~'||ROWNUM ELSE FF.COL2||'~'||ROWNUM END AS NR_ROW,
   FF.ORDINE AS ORDINE,
  '11' AS DECIMAL_POS,
  FF.DENUMIRE AS NUME_ROW,
  FF.COL3  AS COL1,
  FF.COL4  AS COL2
FROM 
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  L.CUATM, 
  L.FULL_CODE,
  L.CUATM_DENUMIRE,
  L.DENUMIRE ,
  L.ORDINE,
  ROUND(L.COL1,1) AS COL1,
  ROUND((L.COL2/L.COL3) *100,1) AS COL2,
  ROUND((L.COL2/L.COL5) *100,1) AS COL3,
  ROUND((L.COL4/L.COL6) *100,1) AS COL4
FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM AS CUATM ,
  T.FULL_CODE AS FULL_CODE,
  T.CUATM_DENUMIRE AS CUATM_DENUMIRE,
  T.DENUMIRE AS DENUMIRE,
  T.ORDINE AS ORDINE, 
  
  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN  D.COL1_S  ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1017) THEN  DD.R000_4  ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R2002_2 * 28)  ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  DD.R210_2   ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R220_2 * 28)  ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R200_2 * 28)  ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  0  + 28  + 0 ELSE NULL END) AS COL7
  
  
 
FROM
(
-------------------------------------------------------------------


SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND IN ('1','2','3','4','5','6')
     ---  AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) A
INNER JOIN
(      
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      -- AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) B 
  ON A.CUIIO = B.CUIIO
 AND A.CUATM = B.CUATM
 AND A.CAPITOL = B.CAPITOL

INNER JOIN CIS2.VW_CL_CUATM C 
  ON A.CUATM = C.CODUL 

INNER JOIN CIS2.VW_CL_CUATM CC 
  ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'

WHERE
  CC.PRGS IN ('2')

GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL


-------------------------------------------------------------------

) D 
LEFT JOIN
(

SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R2002_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R2002_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R2002_3,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R230_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R230_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R230_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3

  
  
FROM CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 

  

WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1017,1018)
 -- AND D.CUIIO IN (5921029)

  
GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM  
  
  
  
  
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D

  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND  ID_MDTABLE = 14612 
  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE

  ) L
  
  GROUP BY
  L.CUATM,
  L.FULL_CODE,
  L.CUATM_DENUMIRE,
  L.DENUMIRE,
  L.ORDINE,
  L.COL1,
  L.COL2,
  L.COL3,
  L.COL4,
  L.COL5,
  L.COL6,
  L.COL7
  
  
  UNION 
  
  SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CUATM AS CUATM,
  A.FULL_CODE AS FULL_CODE,
  A.CUATM_DENUMIRE AS CUATM_DENUMIRE,
  A.DENUMIRE AS DENUMIRE,
  TO_NUMBER (A.ORDINE||'.'||A.RIND_S) AS ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4
 
  
FROM
(
SELECT
         C.CODUL AS CUATM,
         C.FULL_CODE,
        C.DENUMIRE AS CUATM_DENUMIRE,    
        B.RIND AS RIND_D,
  A.RIND AS RIND_S,
  B.ID_MD AS ID_MD_D,
  A.ID_MD AS ID_MD_S,
  B.CAPITOL,
  A.DENUMIRE,
  T.ORDINE
FROM
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND IN ('1','2','3','4','5','6')
) A
CROSS JOIN
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B
CROSS JOIN CIS2.VW_CL_CUATM C
INNER JOIN
(
SELECT
  ORDINE,
  RIND
FROM CIS2.MD_RIND_OUT
WHERE ID_MDTABLE = 14630
) T ON (T.RIND = B.RIND)
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
ORDER BY
  T.ORDINE,
  B.RIND,
  A.RIND
) A
LEFT JOIN
(
 SELECT
 LL.RIND_S AS RIND_S,
 LL.RIND_D AS RIND_D,
 LL.ID_MD_S AS ID_MD_S,
 LL.ID_MD_D AS ID_MD_D,
 LL.CUATM AS CUATM,
 ROUND (LL.COL1,1) AS COL1,
 ROUND((LL.COL2/LL.COL3) * 100,1) AS COL2,
 ROUND((LL.COL2/LL.COL5) * 100,1) AS COL3,
 ROUND((LL.COL4/LL.COL6) * 100,1) AS COL4
  
 FROM (
SELECT
  D.RIND_S  AS RIND_S,
  D.RIND_D  AS RIND_D,
  D.ID_MD_S AS ID_MD_S,
  D.ID_MD_D AS ID_MD_D,
  CC.CODUL  AS CUATM,
  
  SUM(CASE WHEN D.CAPITOL  IN (1010) THEN  D.COL1_S  ELSE NULL END) AS COL1,
  SUM(CASE WHEN DD.CAPITOL IN (1017) THEN  DD.R000_4  ELSE NULL END) AS COL2,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R2002_2 * 28)  ELSE NULL END) AS COL3,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  DD.R210_2   ELSE NULL END) AS COL4,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R220_2 * 28)  ELSE NULL END) AS COL5,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  (DD.R200_2 * 28)  ELSE NULL END) AS COL6,
  SUM(CASE WHEN DD.CAPITOL IN (1018) THEN  0  + 28  + 0 ELSE NULL END) AS COL7

    
FROM
(
------------------------------------------------------------------------------------------------------

SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND IN ('1','2','3','4','5','6')
      --- AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) A
INNER JOIN
(      
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
        INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      -- AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
      AND C.FULL_CODE LIKE '%' ||:pCOD_CUATM|| ';%'
) B 
  ON A.CUIIO = B.CUIIO
 AND A.CUATM = B.CUATM
 AND A.CAPITOL = B.CAPITOL

INNER JOIN CIS2.VW_CL_CUATM C 
  ON A.CUATM = C.CODUL 

INNER JOIN CIS2.VW_CL_CUATM CC 
  ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'

WHERE
  CC.PRGS IN ('2')

GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL

  
  ----------------------------------------------------------------------------------------
) D
LEFT JOIN
(
---
SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R000_2,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL4) ELSE NULL END) AS R000_4,
  SUM(CASE WHEN MR.CAPITOL IN (1017) AND  MR.RIND IN ('000')  THEN CIS2.NVAL(D.COL6) ELSE NULL END) AS R000_6,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R2002_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R2002_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('2002') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R2002_3,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('220')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R230_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R230_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('230')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R230_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('210')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3, 
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN MR.CAPITOL IN (1018) AND  MR.RIND IN ('200')  THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3

  
  
FROM CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 

  

WHERE
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1017,1018)
 -- AND D.CUIIO IN (5921029)

  
GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM  
  
  ---  
  
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
  ) LL 
  
  GROUP BY 
  LL.RIND_S,
  LL.RIND_D,
  LL.ID_MD_S,
  LL.ID_MD_D,
  LL.CUATM,
  LL.COL1,
  LL.COL2,
  LL.COL3,
  LL.COL5,
  LL.COL4,
  LL.COL6,
  LL.COL7 
  
  
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D  AND A.CUATM=B.CUATM)
--WHERE
  
  ) FF
  
 -- ORDER BY
 -- FF.FULL_CODE,
 -- FF.ORDINE
  
    
  
  ;
   END IF;
  END LOOP;
END; -- =======================================================================