SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3
  
FROM
  CIS2.DATA_ALL D
  
       
WHERE
 (D.PERIOADA =:pPERIOADA) AND 
 (:pFORM =:pFORM) AND
 (:pFORM_VERS =:pFORM_VERS) AND 
 (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  D.CAPITOL IN (1018)

GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM
