SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND IN ('1','2','3','4','5','6')
      AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
) A
INNER JOIN
(      
   SELECT
      D.CUIIO,
      R.CUATM,
      MR.RIND,
      MR.ID_MD,
      MR.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
   FROM CIS2.DATA_ALL D
      INNER JOIN CIS2.RENIM R 
        ON R.CUIIO = D.CUIIO 
       AND R.CUIIO_VERS = D.CUIIO_VERS 
      INNER JOIN CIS2.MD_RIND MR 
        ON MR.ID_MD = D.ID_MD
   WHERE
      D.PERIOADA = 2014
      AND D.FORM IN (20)
      AND D.FORM_VERS = 2000
      AND MR.CAPITOL IN (1010)
      AND MR.RIND NOT IN ('00','--','1','2','3','4','5','6')
      AND D.CUIIO IN (5921029)
      AND CIS2.NVAL(D.COL1) <> 0
) B 
  ON A.CUIIO = B.CUIIO
 AND A.CUATM = B.CUATM
 AND A.CAPITOL = B.CAPITOL

INNER JOIN CIS2.VW_CL_CUATM C 
  ON A.CUATM = C.CODUL 

INNER JOIN CIS2.VW_CL_CUATM CC 
  ON C.FULL_CODE LIKE '%' || CC.CODUL || ';%'

WHERE
  CC.PRGS IN ('2')

GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL;