SELECT
  D.CUIIO,
  R.CUATM,
  MR.CAPITOL,
  SUM(CASE WHEN MR.RIND IN ('200') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN MR.RIND IN ('200') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN MR.RIND IN ('200') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3,
  SUM(CASE WHEN MR.RIND IN ('210') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN MR.RIND IN ('210') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN MR.RIND IN ('210') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3,
  SUM(CASE WHEN MR.RIND IN ('220') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN MR.RIND IN ('220') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN MR.RIND IN ('220') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3
  
FROM
  CIS2.DATA_ALL D
          INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
          INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
          INNER JOIN CIS2.VW_CL_CUATM C  ON R.CUATM = C.CODUL 
 
       
WHERE
 (D.PERIOADA =:pPERIOADA) AND 
 (D.FORM =:pFORM) AND
 (D.FORM_VERS =:pFORM_VERS) AND 
 (:pID_MDTABLE =:pID_MDTABLE) AND
 (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  MR.CAPITOL IN (1018)

GROUP BY
  D.CUIIO,
  MR.CAPITOL,
  R.CUATM
