SELECT
   :pPERIOADA AS PERIOADA,                                                    
   :pFORM AS FORM,                                                            
   :pFORM_VERS AS FORM_VERS,                                                  
   :pID_MDTABLE AS ID_MDTABLE,                                                
   :pCOD_CUATM AS COD_CUATM,   
   FF.FULL_CODE AS NR_SECTIE,                                                         
   FF.CUATM_DENUMIRE AS NUME_SECTIE, 
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  -- FF.COL2||'~'||ROWNUM AS NR_ROW,
    CASE WHEN INSTR(TO_CHAR(FF.COL2)||'~'||ROWNUM,'.',1) = 1 THEN 0||FF.COL2||'~'||ROWNUM ELSE FF.COL2||'~'||ROWNUM END AS NR_ROW,
   FF.ORDINE AS ORDINE,
  '00' AS DECIMAL_POS,
   FF.DENUMIRE AS NUME_ROW,
   FF.COL3  AS COL1,
   FF.COL4  AS COL2
FROM
(
SELECT
--  D.RIND_S,
--  D.RIND_D,
--  D.ID_MD_S,
--  D.ID_MD_D,
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE,
   ROUND(SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S  ELSE NULL END),1) AS COL1,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R200_1+DD.R200_2+DD.R200_3 ELSE NULL END),1) AS COL2,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R210_1+DD.R210_2+DD.R210_3 ELSE NULL END),1) AS COL3,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R220_1+DD.R220_2+DD.R220_3 ELSE NULL END),1) AS COL4
 
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  CC.CODUL AS CUATM,
  CC.DENUMIRE AS CUATM_DENUMIRE,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
     CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA - 1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
      
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') 
      ) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
      CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA - 1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
      
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6')   
        
) B ON (A.CUIIO=B.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL) 
--  INNER JOIN VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
WHERE
  CC.PRGS IN (2)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  CC.CODUL,
  CC.DENUMIRE,
  A.CAPITOL
) D 
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3
  
FROM
  CIS2.VW_DATA_ALL D
  
       
WHERE
 (D.PERIOADA =:pPERIOADA) AND 
 (:pFORM =:pFORM) AND
 (:pFORM_VERS =:pFORM_VERS) AND 
 (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (19) AND
  D.CAPITOL IN (1018)

GROUP BY
  D.CUIIO,
  D.CAPITOL,
  D.CUATM
  
) DD ON (D.CUIIO=DD.CUIIO)
RIGHT JOIN
(
SELECT
  C.CODUL AS CUATM,
  C.FULL_CODE,
  C.DENUMIRE AS CUATM_DENUMIRE,
  D.DENUMIRE,
  D.ORDINE,
  D.RIND
FROM  CIS2.MD_RIND_OUT D

  CROSS JOIN CIS2.VW_CL_CUATM C
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
  AND D.ID_MDTABLE = 14612 
  
  
  
) T ON (T.RIND LIKE '%'||D.RIND_D||'%' AND T.CUATM=D.CUATM)

GROUP BY
  T.CUATM,
  T.FULL_CODE,
  T.CUATM_DENUMIRE,
  T.DENUMIRE,
  T.ORDINE
--  D.RIND_S,
--  D.RIND_D
--  D.ID_MD_S,
--  D.ID_MD_D
--ORDER BY
--  T.FULL_CODE
  
UNION

SELECT
--  A.RIND_S,
--  A.RIND_D,
--  A.ID_MD_S,
--  A.ID_MD_D,
  A.CUATM,
  A.FULL_CODE,
  A.CUATM_DENUMIRE,
  A.DENUMIRE,
  TO_NUMBER(A.ORDINE||'.'||A.RIND_S) ORDINE,
  B.COL1,
  B.COL2,
  B.COL3,
  B.COL4
  
FROM
(
SELECT
         C.CODUL AS CUATM,
         C.FULL_CODE,
        C.DENUMIRE AS CUATM_DENUMIRE,    
        B.RIND AS RIND_D,
  A.RIND AS RIND_S,
  B.ID_MD AS ID_MD_D,
  A.ID_MD AS ID_MD_S,
  B.CAPITOL,
  A.DENUMIRE,
  T.ORDINE
FROM
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND IN ('1','2','3','4','5','6')
) A
CROSS JOIN
(
SELECT
  R.RIND,
  R.DENUMIRE,
  R.ID_MD,
  R.CAPITOL,
  ROWNUM
FROM CIS2.MD_RIND R
WHERE
  R.FORM IN (20) AND
  R.CAPITOL IN (1010) AND
  R.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
) B
CROSS JOIN CIS2.VW_CL_CUATM C
INNER JOIN
(
SELECT
  ORDINE,
  RIND
FROM CIS2.MD_RIND_OUT
WHERE ID_MDTABLE = 14630
) T ON (T.RIND = B.RIND)
WHERE
  C.PRGS IN (2) AND
  C.CODUL NOT IN ('9800000')
ORDER BY
  T.ORDINE,
  B.RIND,
  A.RIND
) A
LEFT JOIN
(
SELECT
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL AS CUATM,
   ROUND(SUM(CASE WHEN D.CAPITOL  IN (1010) THEN D.COL1_S  ELSE NULL END),1) AS COL1,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R200_1+DD.R200_2+DD.R200_3 ELSE NULL END),1) AS COL2,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R210_1+DD.R210_2+DD.R210_3 ELSE NULL END),1) AS COL3,
   ROUND(SUM(CASE WHEN DD.CAPITOL IN (1018) THEN DD.R220_1+DD.R220_2+DD.R220_3 ELSE NULL END),1) AS COL4
FROM
(
SELECT
  A.RIND AS RIND_S,
  B.RIND AS RIND_D,
  A.CUIIO,
  C.CODUL AS CUATM,
  A.CAPITOL,
  A.ID_MD AS ID_MD_S,
  B.ID_MD AS ID_MD_D,
  SUM(A.COL1) AS COL1_S,
  SUM(B.COL1) AS COL1_D
FROM
(
SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
       CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA- 1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND IN ('1','2','3','4','5','6')
       AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') 
      
--      AND 
--      D.CUIIO IN (40591077)
) A
INNER JOIN
(      
 SELECT
      D.CUIIO,
      D.CUATM,
      D.RIND,
      D.ID_MD,
      D.CAPITOL,
      CIS2.NVAL(D.COL1) AS COL1
    FROM
       CIS2.VW_DATA_ALL D
      
         INNER JOIN
         (
           SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
           WHERE P.PERIOADA = :pPERIOADA 
    
           UNION   
   
           SELECT P.PERIOADA - 1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
           WHERE T.PERIOADA = :pPERIOADA
   
        ) P ON(D.PERIOADA=P.PERIOADA)
    WHERE
      D.FORM IN (20) AND
      D.CAPITOL IN (1010) AND
      D.RIND NOT IN ('00','--','1','2','3','4','5','6','113')
           
) B ON (A.CUIIO=B.CUIIO)
INNER JOIN CIS2.VW_CL_CUATM C ON (A.CUATM=C.CODUL)
--INNER JOIN CIS2.VW_CL_CUATM CC ON (C.GRUPA=CC.CODUL)
GROUP BY
  A.RIND,
  B.RIND,
  A.ID_MD,
  B.ID_MD,
  A.CUIIO,
  C.CODUL,
  A.CAPITOL
) D
LEFT JOIN
(
SELECT
  D.CUIIO,
  D.CUATM,
  D.CAPITOL,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R200_1,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R200_2,
  SUM(CASE WHEN D.RIND IN ('200') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R200_3,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R210_1,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R210_2,
  SUM(CASE WHEN D.RIND IN ('210') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R210_3,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) ELSE NULL END) AS R220_1,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL2) ELSE NULL END) AS R220_2,
  SUM(CASE WHEN D.RIND IN ('220') THEN CIS2.NVAL(D.COL3) ELSE NULL END) AS R220_3
  
  
  
FROM
   CIS2.VW_DATA_ALL D
  
    
WHERE
   (D.PERIOADA =:pPERIOADA) AND 
   (:pFORM =:pFORM) AND
   (:pFORM_VERS =:pFORM_VERS) AND 
   (:pID_MDTABLE =:pID_MDTABLE) AND
   (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
    D.FORM IN (19) AND
    D.CAPITOL IN (1018)
        
GROUP BY
  D.CUIIO,
  D.CUATM,
  D.CAPITOL
) DD ON (D.CUIIO=DD.CUIIO)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%')
WHERE
  CC.PRGS IN (2) AND
  CC.CODUL NOT IN ('9800000')
GROUP BY
  D.RIND_S,
  D.RIND_D,
  D.ID_MD_S,
  D.ID_MD_D,
  CC.CODUL
) B ON (A.RIND_S=B.RIND_S AND A.RIND_D=B.RIND_D AND A.ID_MD_S=B.ID_MD_S AND A.ID_MD_D=B.ID_MD_D AND A.CUATM=B.CUATM)
--WHERE
--  A.CUATM=B.CUATM OR
--  B.CUATM IS NULL
----ORDER BY
--  A.CUATM
  
) FF
--ORDER BY
 -- FF.FULL_CODE,
 -- FF.ORDINE
  
