SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
 COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10,
COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20,
COL21, COL22, COL23, COL24, COL25, COL26, COL27, COL28, COL29, COL30,
COL31, COL32, COL33, COL34, COL35, COL36, COL37
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL37,0) AS COL1,
  ROUND(A.COL1,0) AS COL2,
  ROUND(A.COL2,0) AS COL3,
  ROUND(A.COL3,0) AS COL4,
  ROUND(A.COL4,0) AS COL5,
  
  ROUND(A.COL5,0) AS COL6,
  ROUND(A.COL6,0) AS COL7,
  ROUND(A.COL7,0) AS COL8,
  ROUND(A.COL8,0) AS COL9,
  ROUND(A.COL9,0) AS COL10,
  ROUND(A.COL10,0) AS COL11,
  ROUND(A.COL11,0) AS COL12,
  ROUND(A.COL12,0) AS COL13,
  ROUND(A.COL13,0) AS COL14,
  ROUND(A.COL14,0) AS COL15,
  ROUND(A.COL15,0) AS COL16,
  ROUND(A.COL16,0) AS COL17,
  
  
  ROUND(A.COL17, 0) AS COL18,
ROUND(A.COL18, 0) AS COL19,
ROUND(A.COL19, 0) AS COL20,
ROUND(A.COL20, 0) AS COL21,
ROUND(A.COL21, 0) AS COL22,
ROUND(A.COL22, 0) AS COL23,
ROUND(A.COL23, 0) AS COL24,
ROUND(A.COL24, 0) AS COL25,
ROUND(A.COL25, 0) AS COL26,
ROUND(A.COL26, 0) AS COL27,
ROUND(A.COL27, 0) AS COL28,
ROUND(A.COL28, 0) AS COL29,
ROUND(A.COL29, 0) AS COL30,
ROUND(A.COL30, 0) AS COL31,
ROUND(A.COL31, 0) AS COL32,
ROUND(A.COL32, 0) AS COL33,
ROUND(A.COL33, 0) AS COL34,
ROUND(A.COL34, 0) AS COL35,
ROUND(A.COL35, 0) AS COL36,
ROUND(A.COL36, 0) AS COL37
 
FROM
(
SELECT 
 
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.1') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.1') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.1') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL3,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.2') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL4,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.2') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL5,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.2') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL6,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.3') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL7,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.3') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL8,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.3') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL9,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.4') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL10,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.4') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL11,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.4') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL12,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.5') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL13,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.5') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL14,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.5') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL15,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.6') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL16,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.6') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL17,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.6') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL18,
  
  
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.7') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL19,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.7') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL20,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.7') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL21,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.8') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL22,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.8') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL23,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.8') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL24,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.9') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL25,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.9') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL26,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.9') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL27,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.10') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL28,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.10') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL29,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.10') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL30,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.11') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL31,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.11') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL32,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.11') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL33,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.12') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL34,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.12') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL35,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('3.1.12') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL36,
  
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
  COUNT(DISTINCT CASE WHEN D.RIND LIKE '3.1%'  AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL37
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
  ---------------------------------------------------------
  
  ------------------------------------------------------------  
            
  
            INNER JOIN (
            
SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') 




) C ON C.CODUL = D.CAEM2

CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ' AS RIND_DENUMIRE, '7' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G' AS RIND, 'Comert cu ridicata ' AS RIND_DENUMIRE, '8' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H' AS RIND, 'Transport si depozitare ' AS RIND_DENUMIRE, '9' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J' AS RIND, 'Informatii si comunicatii' AS RIND_DENUMIRE, '10' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K' AS RIND, 'Activitati  financiare si asigurari' AS RIND_DENUMIRE, '11' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71' AS RIND, 'Activitati de arhitectura si inginerie' AS RIND_DENUMIRE, '12' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72' AS RIND, 'Activitati de cercetare dezvoltare' AS RIND_DENUMIRE, '13' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73' AS RIND, 'Publicitate si activitati de studiere a pietei' AS RIND_DENUMIRE, '14' AS ORDINE FROM DUAL   
    

  ) TR
            
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1042 AND  
  D.RIND LIKE '3.1%' 
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  GROUP BY
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

--  A.CAEM2
ORDER BY
  TR.NR_TABLE,
  TO_NUMBER(TR.ORDINE)
 )  A
--  
 ) 