SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10,
COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20,
COL21, COL22, COL23, COL24, COL25, COL26, COL27, COL28, COL29, COL30,
COL31, COL32, COL33, COL34, COL35, COL36, COL37
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
ROUND(A.COL37,0) AS COL1,
  ROUND(A.COL1,0) AS COL2,
  ROUND(A.COL2,0) AS COL3,
  ROUND(A.COL3,0) AS COL4,
  ROUND(A.COL4,0) AS COL5,
  
  ROUND(A.COL5,0) AS COL6,
  ROUND(A.COL6,0) AS COL7,
  ROUND(A.COL7,0) AS COL8,
  ROUND(A.COL8,0) AS COL9,
  ROUND(A.COL9,0) AS COL10,
  ROUND(A.COL10,0) AS COL11,
  ROUND(A.COL11,0) AS COL12,
  ROUND(A.COL12,0) AS COL13,
  ROUND(A.COL13,0) AS COL14,
  ROUND(A.COL14,0) AS COL15,
  ROUND(A.COL15,0) AS COL16,
  ROUND(A.COL16,0) AS COL17,

ROUND(A.COL17, 0) AS COL18,
ROUND(A.COL18, 0) AS COL19,
ROUND(A.COL19, 0) AS COL20,
ROUND(A.COL20, 0) AS COL21,
ROUND(A.COL21, 0) AS COL22,
ROUND(A.COL22, 0) AS COL23,
ROUND(A.COL23, 0) AS COL24,
ROUND(A.COL24, 0) AS COL25,
ROUND(A.COL25, 0) AS COL26,
ROUND(A.COL26, 0) AS COL27,
ROUND(A.COL27, 0) AS COL28,
ROUND(A.COL28, 0) AS COL29,
ROUND(A.COL29, 0) AS COL30,
ROUND(A.COL30, 0) AS COL31,
ROUND(A.COL31, 0) AS COL32,
ROUND(A.COL32, 0) AS COL33,
ROUND(A.COL33, 0) AS COL34,
ROUND(A.COL34, 0) AS COL35,
ROUND(A.COL35, 0) AS COL36,
ROUND(A.COL36, 0) AS COL37
  
  
 
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.1') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL1,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.1') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL2,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.1') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL3,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.2') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL4,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.2') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL5,
 
 
 COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.2') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL6,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.3') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL7,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.3') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL8,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.3') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL9,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.4') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL10,
 
 
   COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.4') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL11,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.4') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL12,
 
 
 
    COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.5') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL13,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.5') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL14,
 
 
     COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.5') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL15,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.6') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL16,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.6') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL17,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.6') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL18,
 
 --
 COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.7') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL19,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.7') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL20,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.7') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL21,
 --
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.8') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL22,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.8') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL23,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.8') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL24,
 --
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.9') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL25,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.9') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL26,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.9') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL27,
 
 --
 
 COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.10') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL28,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.10') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL29,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.10') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL30,
 --
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.11') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL31,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.11') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL32,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.11') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL33,
 --
 
 
 COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.12') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL34,
 
 
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.12') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL35,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('3.1.12') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL36,
 --
 
 
   COUNT(DISTINCT CASE WHEN A.RIND  LIKE '3.1%' AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL37
  
  
 
  
FROM
(
SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1,
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5  


FROM 
  CIS2.VW_DATA_ALL D
  
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1042 AND  
  D.RIND LIKE '3.1%'
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 458963
  
) A LEFT JOIN
 
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  INNER JOIN (SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') ) C ON C.CODUL = A.CAEM2
  CROSS JOIN 
(

   
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '2' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '3' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '4' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '5' AS ORDINE  , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '6' AS ORDINE, 'B+C+D+E' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '7' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '8' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '9' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '10' AS ORDINE  , 'B+C+D+E' AS RIND_C FROM DUAL UNION 
    
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '11' AS ORDINE, 'H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '12' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '13' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '14' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '15' AS ORDINE  , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL
    
  ) TR
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

) A

--
--ORDER BY
--  TO_NUMBER(A.NR_TABLE),
--  TO_NUMBER(A.ORDINE)
  
 )