SELECT 
  3 AS NR_TABLE, 
  ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
  NUME_ROW AS RIND_DENUMIRE,
  NR_ROW AS ORDINE,
  CS_CUATM AS RIND,

SUM(COL2) + SUM(COL3) + SUM(COL4) AS COL1,
SUM(COL2)  AS COL2, 
SUM(COL3)  AS COL3, 
SUM(COL4)  AS COL4 

FROM
(
SELECT
CC.NR_ROW,
CC.CS_CUATM,
CC.NUME_ROW,

CC.ORDINE,
COUNT(DISTINCT CASE WHEN  D.RIND IN ('1.1.1','1.1.2') AND NVAL(D.COL1)  >=  1  AND (DD.has_151 + DD.has_152 + DD.has_153 + DD.has_154 + DD.has_155 + DD.has_156 + DD.has_157 = 0)  
AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%'   
AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  

THEN D.CUIIO END) AS COL2,

COUNT(DISTINCT CASE WHEN D.RIND LIKE ('1.5.%')  AND NVAL(D.COL1) >= 1  AND (DD.has_112 + DD.has_111 = 0)  AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%'  
 AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL3,

COUNT(DISTINCT CASE WHEN D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')   AND NVAL(D.COL1) >= 1 AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
  AND 
((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END)
 AS COL4
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
  D.ANUL,
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2,
  DD.has_111,
  DD.has_112,
  DD.has_151,
  DD.has_152,
  DD.has_153,
  DD.has_154,
  DD.has_155,
  DD.has_156,
  DD.has_157
FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (
  SELECT
    CUIIO,
    MAX(CUIIO_VERS) CUIIO_VERS,

    MAX(CASE WHEN ID_MD = 83509 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_111,
    MAX(CASE WHEN ID_MD = 83504 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_112,
    MAX(CASE WHEN ID_MD = 83532 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_151,
    MAX(CASE WHEN ID_MD = 83533 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_152,
    MAX(CASE WHEN ID_MD = 83534 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_153,
    MAX(CASE WHEN ID_MD = 83535 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_154,
    MAX(CASE WHEN ID_MD = 83536 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_155,
    MAX(CASE WHEN ID_MD = 83537 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_156,
    MAX(CASE WHEN ID_MD = 83538 AND NVAL(COL1) = 1 THEN 1 ELSE 0 END) AS has_157
    

  FROM CIS2.DATA_ALL
  WHERE PERIOADA = :pPERIOADA
    AND FORM     = :pFORM
    AND 
    ID_MD IN (83509,83504,83532,83533,83534,83535,83536,83537,83538)
     
    
    
 
  GROUP BY 
    CUIIO
  
    

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 400053

  ) DD ON DD.CUIIO = D.CUIIO AND DD.CUIIO_VERS = D.CUIIO_VERS  
  
            INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
            

            
            CROSS JOIN (
            
            SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE  FROM  DUAL UNION  
            SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '2' AS ORDINE   FROM  DUAL UNION
            SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '3' AS ORDINE   FROM  DUAL UNION 
            SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '4' AS ORDINE   FROM  DUAL UNION
            SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '5' AS ORDINE   FROM  DUAL UNION
            SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '6' AS ORDINE   FROM   DUAL UNION 
            
            SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '7' AS ORDINE  FROM  DUAL UNION  
            SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '8' AS ORDINE   FROM  DUAL UNION
            SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '9' AS ORDINE   FROM  DUAL UNION 
            SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '10' AS ORDINE   FROM  DUAL UNION
            SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '11' AS ORDINE   FROM  DUAL UNION
            SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '12' AS ORDINE   FROM   DUAL UNION
            
            SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '13' AS ORDINE  FROM  DUAL UNION  
            SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '14' AS ORDINE   FROM  DUAL UNION
            SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '15' AS ORDINE   FROM  DUAL UNION 
            SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '16' AS ORDINE   FROM  DUAL UNION
            SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '17' AS ORDINE   FROM  DUAL UNION
            SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '18' AS ORDINE   FROM   DUAL 
            
            
            
            
            
            ) CC
               
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.1.1','1.1.2','1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7')
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  

  
  GROUP BY
  CC.NR_ROW,
  CC.NUME_ROW,
  CC.ORDINE,
  CC.CS_CUATM
  )
  
  GROUP BY 
 NR_ROW,
ORDINE,
NUME_ROW,
CS_CUATM