INSERT INTO CIS2.MD_RIND_OUT 
  (
  ID_MDTABLE,
  RINDOUT_VERS,
  RINDOUT,
  DENUMIRE,
  STATUT,
  ORDINE,
  DATA_REG,
  RIND
  )     

SELECT
14569  ID_MDTABLE,
1004 RINDOUT_VERS,
SUBSTR(L.CAEM2,6,11) RINDOUT,
  NULL DENUMIRE,
  NULL STATUT,
  NULL ORDINE,
  NULL DATA_REG,
  R.FULL_CODE  AS RIND 

FROM USER_BANCU.CAEM2 L LEFT JOIN CIS2.VW_CL_CAEM2 R ON R.CODUL = SUBSTR(L.CAEM2,6,11) 


--SELECT 
--RIND AS CODUL
--FROM CIS2.MD_RIND_OUT
--WHERE
--ID_MDTABLE = 14569