--INSERT INTO CIS2.MD_RIND_OUT 
--  (
--  ID_MDTABLE,
--  RINDOUT_VERS,
--  RINDOUT,
--  DENUMIRE,
--  STATUT,
--  ORDINE,
--  DATA_REG,
--  RIND
--  )     

SELECT
14569  ID_MDTABLE,
1004 RINDOUT_VERS,
SUBSTR(CAEM2,6,11) RINDOUT,
  NULL DENUMIRE,
  NULL STATUT,
  NULL ORDINE,
  NULL DATA_REG,
SUBSTR(CAEM2,6,11) AS RIND

FROM USER_BANCU.CAEM2 L


--SELECT 
--RIND AS CODUL
--FROM CIS2.MD_RIND_OUT
--WHERE
--ID_MDTABLE = 14569