SELECT 
  3 AS NR_TABLE, 
  ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
  NUME_ROW AS RIND_DENUMIRE,
  NR_ROW AS ORDINE,
  CS_CUATM AS RIND,

SUM(COL11)  AS COL1,
SUM(COL1)  AS COL2, 
SUM(COL2)  AS COL3, 
SUM(COL3)  AS COL4,
SUM(COL4)  AS COL5,
SUM(COL5)  AS COL6,
SUM(COL6)  AS COL7, 
SUM(COL7)  AS COL8, 
SUM(COL8)  AS COL9,
SUM(COL9)  AS COL10,
SUM(COL10)  AS COL11   

FROM
(
SELECT
CC.NR_ROW,
CC.CS_CUATM,
CC.NUME_ROW,

CC.ORDINE,
COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  
THEN D.CUIIO END) AS COL1,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL2) = 1  AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL2,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL3) = 1 AND ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL3,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL4) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL4,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL5) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL5,


----------------------------------------------------------------------------------------



COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  
THEN D.CUIIO END) AS COL6,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL2) = 1  AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL7,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL3) = 1 AND ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL8,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL4) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL9,

COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL5) = 1 AND  ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL10,

COUNT(DISTINCT CASE WHEN D.RIND LIKE '2.1%' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%'  AND ((CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (CC.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )   
THEN D.CUIIO END) AS COL11

FROM 
  CIS2.VW_DATA_ALL D
  
   
  
            INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
            

            
            CROSS JOIN (
            
            SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE  FROM  DUAL UNION  
            SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '2' AS ORDINE   FROM  DUAL UNION
            SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '3' AS ORDINE   FROM  DUAL UNION 
            SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '4' AS ORDINE   FROM  DUAL UNION
            SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '5' AS ORDINE   FROM  DUAL UNION
            SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '6' AS ORDINE   FROM   DUAL UNION 
            
            SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '7' AS ORDINE  FROM  DUAL UNION  
            SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '8' AS ORDINE   FROM  DUAL UNION
            SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '9' AS ORDINE   FROM  DUAL UNION 
            SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '10' AS ORDINE   FROM  DUAL UNION
            SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '11' AS ORDINE   FROM  DUAL UNION
            SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total' AS RIND_DENUMIRE, '12' AS ORDINE   FROM   DUAL UNION
            
            SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '13' AS ORDINE  FROM  DUAL UNION  
            SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '14' AS ORDINE   FROM  DUAL UNION
            SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '15' AS ORDINE   FROM  DUAL UNION 
            SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '16' AS ORDINE   FROM  DUAL UNION
            SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '17' AS ORDINE   FROM  DUAL UNION
            SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '18' AS ORDINE   FROM   DUAL 
            
            
            
            
            
            ) CC
               
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1041 AND  
  D.RIND LIKE '2.1%' 
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  

  
  GROUP BY
  CC.NR_ROW,
  CC.NUME_ROW,
  CC.ORDINE,
  CC.CS_CUATM
  ) 
  
  GROUP BY 
 NR_ROW,
ORDINE,
NUME_ROW,
CS_CUATM