INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10
)




----------------------------------------------------------------------------------------------------



SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
NR_TABLE AS NR_SECTIE,
TABLE_DENUMIRE AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
COL1||'~'||ROWNUM  NR_ROW,
ROWNUM AS ORDINE,
'0000000000' AS DECIMAL_POS, 
RIND_DENUMIRE AS NUME_ROW,
COL2 AS COL1, 
COL3 AS COL2,
COL4 AS COL3,
COL5 AS COL4,
COL6 AS COL5, 
COL7 AS COL6,
COL8 AS COL7,
COL9 AS COL8,
COL10 AS COL9,
COL11 AS COL10

FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL1,0) AS COL1,
  ROUND(A.COL2,0) AS COL2,
  ROUND(A.COL3,0) AS COL3,
  ROUND(A.COL4,0) AS COL4,
  ROUND(A.COL5,0) AS COL5,
  
  ROUND(A.COL6,0) AS COL6,
  ROUND(A.COL7,0) AS COL7,
  ROUND(A.COL8,0) AS COL8,
  ROUND(A.COL9,0) AS COL9,
  ROUND(A.COL10,0) AS COL10,
  ROUND(A.COL11,0) AS COL11
  
  
  
FROM
(


SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
COL1, COL2,COL3,COL4, COL5, COL6, COL7,COL8,COL9,COL10, COL11
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
ROUND((A.COL11),0) AS COL1,
  ROUND(A.COL1,0) AS COL2,
  ROUND(A.COL2,0) AS COL3,
  ROUND(A.COL3,0) AS COL4,
  ROUND(A.COL4,0) AS COL5,
  
  ROUND(A.COL5,0) AS COL6,
  ROUND(A.COL6,0) AS COL7,
  ROUND(A.COL7,0) AS COL8,
  ROUND(A.COL8,0) AS COL9,
  
  ROUND(A.COL9,0) AS COL10,
  ROUND(A.COL10,0) AS COL11
 
FROM
(
SELECT 
 
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL3,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND NVAL(D.COL4) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL4,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.1') AND NVAL(D.COL5) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL5,
  
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND NVAL(D.COL1) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL6,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND NVAL(D.COL2) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL7,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND NVAL(D.COL3) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL8,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND NVAL(D.COL4) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL9,
  COUNT(DISTINCT CASE WHEN D.RIND IN ('2.1.2') AND NVAL(D.COL5) = 1 AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL10,
  
  
  COUNT(DISTINCT CASE WHEN D.RIND LIKE '2.1%'  AND ( (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%') OR (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%') )  THEN D.CUIIO END) AS COL11
   
    
FROM 
  CIS2.VW_DATA_ALL D 
  
  ---------------------------------------------------------
  
  ------------------------------------------------------------  
            
  
            INNER JOIN (
            
SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') 




) C ON C.CODUL = D.CAEM2

CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ' AS RIND_DENUMIRE, '7' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G' AS RIND, 'Comert cu ridicata ' AS RIND_DENUMIRE, '8' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H' AS RIND, 'Transport si depozitare ' AS RIND_DENUMIRE, '9' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J' AS RIND, 'Informatii si comunicatii' AS RIND_DENUMIRE, '10' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K' AS RIND, 'Activitati  financiare si asigurari' AS RIND_DENUMIRE, '11' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71' AS RIND, 'Activitati de arhitectura si inginerie' AS RIND_DENUMIRE, '12' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72' AS RIND, 'Activitati de cercetare dezvoltare' AS RIND_DENUMIRE, '13' AS ORDINE FROM DUAL UNION  
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73' AS RIND, 'Publicitate si activitati de studiere a pietei' AS RIND_DENUMIRE, '14' AS ORDINE FROM DUAL   
    

  ) TR
            
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1041 AND  
  D.RIND LIKE '2.1%' 
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  GROUP BY
 TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

--  A.CAEM2
ORDER BY
  TR.NR_TABLE,
  TO_NUMBER(TR.ORDINE)
  )  A
  
  ) 
UNION 
SELECT 
NR_TABLE,
TABLE_DENUMIRE,
RIND_DENUMIRE,
ORDINE,
RIND,
COL1, COL2,COL3,COL4, COL5, COL6, COL7,COL8,COL9,COL10, COL11
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND((A.COL11),0) AS COL1,
  ROUND(A.COL1,0) AS COL2,
  ROUND(A.COL2,0) AS COL3,
  ROUND(A.COL3,0) AS COL4,
  ROUND(A.COL4,0) AS COL5,
  
  ROUND(A.COL5,0) AS COL6,
  ROUND(A.COL6,0) AS COL7,
  ROUND(A.COL7,0) AS COL8,
  ROUND(A.COL8,0) AS COL9,
  
  ROUND(A.COL9,0) AS COL10,
  ROUND(A.COL10,0) AS COL11
  
  
 
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.1') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL1,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.1') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL2,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.1') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL3,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.1') AND NVAL(A.COL4) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL4,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.1') AND NVAL(A.COL5) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL5,
 
 
 COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.2') AND NVAL(A.COL1) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL6,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.2') AND NVAL(A.COL2) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL7,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.2') AND NVAL(A.COL3) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL8,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.2') AND NVAL(A.COL4) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL9,
 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('2.1.2') AND NVAL(A.COL5) = 1  AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL10,
 
 
 
   COUNT(DISTINCT CASE WHEN A.RIND  LIKE '2.1%' AND ((ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL  )
  AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%') )   
 THEN A.CUIIO END) AS COL11
  
  
 
  
FROM
(
SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1,
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5  


FROM 
  CIS2.VW_DATA_ALL D
  
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1041 AND  
  D.RIND LIKE '2.1%'
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 458963
  
) A LEFT JOIN
 
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  INNER JOIN (SELECT
CODUL,
full_code 
FROM CIS2.VW_CL_CAEM2
WHERE 
SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') OR 
SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73') ) C ON C.CODUL = A.CAEM2
  CROSS JOIN 
(

   
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '2' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '3' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '4' AS ORDINE , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '5' AS ORDINE  , 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '6' AS ORDINE, 'B+C+D+E' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '7' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '8' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '9' AS ORDINE , 'B+C+D+E' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '10' AS ORDINE  , 'B+C+D+E' AS RIND_C FROM DUAL UNION 
    
    
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Servicii - total' AS RIND_DENUMIRE, '11' AS ORDINE, 'H+J+K+G46+M71+M72+M73' AS RIND_C  FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '12' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '13' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '14' AS ORDINE , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '15' AS ORDINE  , 'H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL
    
  ) TR
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

) A
ORDER BY
  TO_NUMBER(A.NR_TABLE),
  TO_NUMBER(A.ORDINE)
  
 )

  
) A
ORDER BY
  TO_NUMBER(A.NR_TABLE),
  TO_NUMBER(A.ORDINE)
  
  
  
  
  
  
  
)

