
CREATE OR REPLACE FORCE VIEW USER_BANCU.VVW_RSF1_2025

AS 

SELECT 
D.CUIIO,
D.CAEM2 RSF_1_CAEM2,
            MAX (
                 CASE
                     WHEN     D.FORM = 57
                          AND D.CAPITOL IN (1091)
                          AND D.RIND IN ('6')
                     THEN
                         D.COL1
                     ELSE
                         NULL
                 END)
                 AS NMP,
              MAX (
                 CASE
                     WHEN     D.FORM = 57
                          AND D.CAPITOL IN (1091)
                          AND D.RIND IN ('CAEM')
                     THEN
                         D.COL1
                     ELSE
                         NULL
                 END)
                 AS CAEM_TITLU,
SUM(CASE WHEN D.CAPITOL IN (1092) AND  D.RIND IN ('010') THEN D.COL1 ELSE NULL END ) RSF1_R_010_C3,
SUM(CASE WHEN D.CAPITOL IN (1092) AND  D.RIND IN ('010') THEN D.COL2 ELSE NULL END ) RSF1_R_010_C4,
--SUM(CASE WHEN D.CAPITOL IN (1092) AND  D.RIND IN ('040') THEN D.COL1 ELSE NULL END ) RSF_040_COL3,
--SUM(CASE WHEN D.CAPITOL IN (1092) AND  D.RIND IN ('040') THEN D.COL2 ELSE NULL END ) RSF_040_COL4,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('290') THEN D.COL1 ELSE NULL END ) RSF1_R_290_C4,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('290') THEN D.COL2 ELSE NULL END ) RSF1_R_290_C5,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('260') THEN D.COL1 ELSE NULL END ) RSF1_R_260_C4,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('260') THEN D.COL2 ELSE NULL END ) RSF1_R_260_C5,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('270') THEN D.COL1 ELSE NULL END ) RSF1_R_270_C4,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('270') THEN D.COL2 ELSE NULL END ) RSF1_R_270_C5,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('280') THEN D.COL1 ELSE NULL END ) RSF1_R_280_C4,
SUM(CASE WHEN D.CAPITOL IN (1090) AND  D.RIND IN ('280') THEN D.COL2 ELSE NULL END ) RSF1_R_280_C5   --RSF1_R_280_C5



FROM
       CIS2.VW_DATA_ALL_FR D             
WHERE 
  D.FORM IN (57)           AND 
          
  D.CAPITOL IN (1092,1090,1091) AND
  D.FORM_VERS = 2009  AND 
  D.FORM = 57 AND
  D.PERIOADA IN (2014) --AND 
  --D.RIND IN ('010','040')
 -- AND D.CUIIO = 227293
  GROUP BY
 D.CUIIO,
D.CAEM2