SELECT 
  NR_TABLE,
  TABLE_DENUMIRE,
  RIND_DENUMIRE,
  ORDINE,
  RIND,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8
FROM
(
  SELECT
    A.NR_TABLE,
    A.TABLE_DENUMIRE,
    A.RIND_DENUMIRE,
    A.ORDINE,
    A.RIND,
    /* COL1 = TOTAL; COL2..COL8 = 1.5.1..1.5.7 */
    ROUND((A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7),0) AS COL1,
    ROUND(A.COL1,0) AS COL2,
    ROUND(A.COL2,0) AS COL3,
    ROUND(A.COL3,0) AS COL4,
    ROUND(A.COL4,0) AS COL5,
    ROUND(A.COL5,0) AS COL6,
    ROUND(A.COL6,0) AS COL7,
    ROUND(A.COL7,0) AS COL8
  FROM
  (
    SELECT 
      TR.NR_TABLE,
      TR.TABLE_DENUMIRE,
      TR.RIND_DENUMIRE,
      TR.ORDINE,
      TR.RIND,
      /* 1.5.1..1.5.7 -> COL1..COL7 (intermediar) */
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.1') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL1,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.2') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL2,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.3') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL3,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.4') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL4,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.5') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL5,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.6') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL6,
      COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.7') AND NVAL(D.COL1) = 1
            AND (TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,1,1) ||'%' OR TR.RIND LIKE '%'|| SUBSTR(D.CAEM2,2,2) ||'%')
          THEN D.CUIIO END) AS COL7
    FROM 
      CIS2.VW_DATA_ALL D 
      INNER JOIN (
        SELECT CODUL, FULL_CODE 
        FROM CIS2.VW_CL_CAEM2
        WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K')
           OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
      ) C ON C.CODUL = D.CAEM2
      CROSS JOIN 
      (
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ' AS RIND_DENUMIRE, '7' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G' AS RIND, 'Comert cu ridicata ' AS RIND_DENUMIRE, '8' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H' AS RIND, 'Transport si depozitare ' AS RIND_DENUMIRE, '9' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J' AS RIND, 'Informatii si comunicatii' AS RIND_DENUMIRE, '10' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K' AS RIND, 'Activitati  financiare si asigurari' AS RIND_DENUMIRE, '11' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71' AS RIND, 'Activitati de arhitectura si inginerie' AS RIND_DENUMIRE, '12' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72' AS RIND, 'Activitati de cercetare dezvoltare' AS RIND_DENUMIRE, '13' AS ORDINE FROM DUAL UNION  
        SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73' AS RIND, 'Publicitate si activitati de studiere a pietei' AS RIND_DENUMIRE, '14' AS ORDINE FROM DUAL   
      ) TR
    WHERE
      D.PERIOADA IN (:pPERIOADA) AND
      D.FORM IN (:pFORM) AND 
      D.RIND IN ('1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND
      D.CAEM2 NOT LIKE 'A%'
    GROUP BY
      TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND
    ORDER BY
      TR.NR_TABLE, TO_NUMBER(TR.ORDINE)
  )  A
)
