--Modifica codul SQL dupa noii parametri
--acum sunt 25 de coloane in fisierul csv sunt parametri   

--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10,
--  COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20,
--  COL21, COL22, COL23, COL24, COL25
--)
SELECT 
  :pPERIOADA   AS PERIOADA,
  :pFORM       AS FORM,
  :pFORM_VERS  AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM  AS COD_CUATM,    
  NR_TABLE     AS NR_SECTIE,
  TABLE_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2, 
  COL1||'~'||ROWNUM  NR_ROW,
  ROWNUM AS ORDINE,
  '0000000000000000000000000' AS DECIMAL_POS,  -- 25 zeroes
  RIND_DENUMIRE AS NUME_ROW,

  /* Mapare finala: pastram logica existenta pentru primele 8 coloane;
     extindem cu umplere 0 pentru COL9..COL25 ca sa corespunda noului CSV (25 coloane) */
  COL2 AS COL1,   -- 1.5.1
  COL3 AS COL2,   -- 1.5.2
  COL4 AS COL3,   -- 1.5.3
  COL5 AS COL4,   -- 1.5.4
  COL6 AS COL5,   -- 1.5.5
  COL7 AS COL6,   -- 1.5.6
  COL8 AS COL7,   -- 1.5.7
  COL1 AS COL8,   -- TOTAL (toate 1.5.x) conform calculelor din subselect
  0    AS COL9,
  0    AS COL10,
  0    AS COL11,
  0    AS COL12,
  0    AS COL13,
  0    AS COL14,
  0    AS COL15,
  0    AS COL16,
  0    AS COL17,
  0    AS COL18,
  0    AS COL19,
  0    AS COL20,
  0    AS COL21,
  0    AS COL22,
  0    AS COL23,
  0    AS COL24,
  0    AS COL25
FROM
(
  SELECT
    A.NR_TABLE,
    A.TABLE_DENUMIRE,
    A.RIND_DENUMIRE,
    A.ORDINE,
    A.RIND,
    ROUND(A.COL1,0) AS COL1,
    ROUND(A.COL2,0) AS COL2,
    ROUND(A.COL3,0) AS COL3,
    ROUND(A.COL4,0) AS COL4,
    ROUND(A.COL5,0) AS COL5,
    ROUND(A.COL6,0) AS COL6,
    ROUND(A.COL7,0) AS COL7,
    ROUND(A.COL8,0) AS COL8
  FROM
  (
    SELECT 
      NR_TABLE,
      TABLE_DENUMIRE,
      RIND_DENUMIRE,
      ORDINE,
      RIND,
      COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8
    FROM
    (
      SELECT
        A.NR_TABLE,
        A.TABLE_DENUMIRE,
        A.RIND_DENUMIRE,
        A.ORDINE,
        A.RIND,
        /* COL1 = TOTAL; COL2..COL8 = 1.5.1..1.5.7 (conform logicii existente) */
        ROUND(A.COL8,0) AS COL1,
        ROUND(A.COL1,0) AS COL2,
        ROUND(A.COL2,0) AS COL3,
        ROUND(A.COL3,0) AS COL4,
        ROUND(A.COL4,0) AS COL5,
        ROUND(A.COL5,0) AS COL6,
        ROUND(A.COL6,0) AS COL7,
        ROUND(A.COL7,0) AS COL8
      FROM
      (
        SELECT
          TR.NR_TABLE,
          TR.TABLE_DENUMIRE,
          TR.RIND_DENUMIRE,
          TR.ORDINE,
          TR.RIND,
          /* 1.5.1..1.5.7 -> COL1..COL7; COL8 = TOTAL 1.5.% */
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.1' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL1,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.2' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL2,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.3' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL3,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.4' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL4,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.5' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL5,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.6' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL6,
          COUNT(DISTINCT CASE WHEN A.RIND = '1.5.7' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL7,
          COUNT(DISTINCT CASE WHEN A.RIND LIKE '1.5%' AND NVAL(A.COL1) = 1
               AND ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
               AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
               THEN A.CUIIO END) AS COL8
        FROM
        (
          SELECT
            D.ANUL,
            D.CUIIO,
            D.CUATM,
            D.CAEM2,
            D.CAPITOL,
            D.RIND,
            D.COL1
          FROM CIS2.VW_DATA_ALL D
          WHERE
            D.PERIOADA IN (:pPERIOADA) AND
            D.FORM     IN (:pFORM) AND 
            D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
            D.RIND IN ('1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND
            D.CAEM2 NOT LIKE 'A%'
        ) A
        LEFT JOIN CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
        INNER JOIN (
          SELECT CODUL, FULL_CODE 
          FROM CIS2.VW_CL_CAEM2
          WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') 
             OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
        ) C ON C.CODUL = A.CAEM2
        CROSS JOIN 
        (
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie - total' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL  UNION
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B' AS RIND, 'Industrie extractiva' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'C' AS RIND, 'Industrie prelucratoare' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'D' AS RIND, 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS RIND_DENUMIRE, '5' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'E' AS RIND, 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare' AS RIND_DENUMIRE, '6' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H+J+K+G+M' AS RIND, 'Servicii - total ', '7' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G', 'Comert cu ridicata ', '8' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'H', 'Transport si depozitare ', '9' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'J', 'Informatii si comunicatii', '10' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'K', 'Activitati  financiare si asigurari', '11' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '71', 'Activitati de arhitectura si inginerie', '12' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '72', 'Activitati de cercetare dezvoltare', '13' FROM DUAL UNION  
          SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, '73', 'Publicitate si activitati de studiere a pietei', '14' FROM DUAL   
        ) TR
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM IN (:pFORM) AND 
        D.RIND IN ('1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND
        D.CAEM2 NOT LIKE 'A%'
      GROUP BY
        TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND
    )

    UNION ALL

    SELECT 
      3 AS NR_TABLE, 
      ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
      NUME_ROW AS RIND_DENUMIRE,
      NR_ROW   AS ORDINE,
      CS_CUATM AS RIND,
      SUM(COL8) AS COL1,
      SUM(COL1) AS COL2, 
      SUM(COL2) AS COL3, 
      SUM(COL3) AS COL4,
      SUM(COL4) AS COL5,
      SUM(COL5) AS COL6,
      SUM(COL6) AS COL7,
      SUM(COL7) AS COL8
    FROM
    (
      SELECT
        CC.NR_ROW,
        CC.CS_CUATM,
        CC.NUME_ROW,
        CC.ORDINE,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.1' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL1,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.2' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL2,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.3' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL3,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.4' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL4,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.5' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL5,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.6' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL6,
        COUNT(DISTINCT CASE WHEN D.RIND = '1.5.7' AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL7,
        COUNT(DISTINCT CASE WHEN D.RIND LIKE '1.5%' AND NVAL(D.COL1) = 1 AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' 
             AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
             THEN D.CUIIO END) AS COL8
      FROM 
        CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
        CROSS JOIN (
          SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1'  AS ORDINE FROM  DUAL UNION  
          SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '2'  FROM  DUAL UNION
          SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '3'  FROM  DUAL UNION 
          SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '4'  FROM  DUAL UNION
          SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '5'  FROM  DUAL UNION
          SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '6'  FROM   DUAL 
        ) CC
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM     IN (:pFORM) AND 
        D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
        D.RIND IN ('1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND
        D.CAEM2 NOT LIKE 'A%'
      GROUP BY
        CC.NR_ROW, CC.NUME_ROW, CC.ORDINE, CC.CS_CUATM
    )
    GROUP BY 
      NR_ROW,
      ORDINE,
      NUME_ROW,
      CS_CUATM
  ) A
  ORDER BY
    TO_NUMBER(A.NR_TABLE),
    TO_NUMBER(A.ORDINE)
);
