SELECT 
  3 AS NR_TABLE, 
  ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
  NUME_ROW AS RIND_DENUMIRE,
  NR_ROW   AS ORDINE,
  CS_CUATM AS RIND,

  /* COL1 = TOTAL; COL2..COL8 = 1.5.1..1.5.7 */
  (SUM(COL1) + SUM(COL2) + SUM(COL3) + SUM(COL4) + SUM(COL5) + SUM(COL6) + SUM(COL7)) AS COL1,
  SUM(COL1) AS COL2, 
  SUM(COL2) AS COL3, 
  SUM(COL3) AS COL4,
  SUM(COL4) AS COL5,
  SUM(COL5) AS COL6,
  SUM(COL6) AS COL7,
  SUM(COL7) AS COL8
FROM
(
  SELECT
    CC.NR_ROW,
    CC.CS_CUATM,
    CC.NUME_ROW,
    CC.ORDINE,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.1') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL1,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.2') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL2,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.3') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL3,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.4') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL4,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.5') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL5,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.6') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL6,

    COUNT(DISTINCT CASE WHEN D.RIND IN ('1.5.7') AND C.FULL_CODE LIKE '%'||CC.CS_CUATM||'%' AND NVAL(D.COL1)=1
         AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
         THEN D.CUIIO END) AS COL7

  FROM 
    CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
    CROSS JOIN (
      SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1'  AS ORDINE FROM  DUAL UNION  
      SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '2'  FROM  DUAL UNION
      SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '3'  FROM  DUAL UNION 
      SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '4'  FROM  DUAL UNION
      SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '5'  FROM  DUAL UNION
      SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9800000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '6'  FROM   DUAL UNION 
      SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total', '7'  FROM  DUAL UNION  
      SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '8'  FROM  DUAL UNION
      SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '9'  FROM  DUAL UNION 
      SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '10' FROM  DUAL UNION
      SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '11' FROM  DUAL UNION
      SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9800000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '12' FROM   DUAL UNION
      SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total', '13' FROM  DUAL UNION  
      SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '14' FROM  DUAL UNION
      SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '15' FROM  DUAL UNION 
      SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '16' FROM  DUAL UNION
      SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '17' FROM  DUAL UNION
      SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9800000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '18' FROM   DUAL 
    ) CC
  WHERE
    D.PERIOADA IN (:pPERIOADA) AND
    D.FORM     IN (:pFORM) AND 
    D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
    D.RIND IN ('1.5.1','1.5.2','1.5.3','1.5.4','1.5.5','1.5.6','1.5.7') AND
    D.CAEM2 NOT LIKE 'A%'
  GROUP BY
    CC.NR_ROW, CC.NUME_ROW, CC.ORDINE, CC.CS_CUATM
)
GROUP BY 
  NR_ROW,
  ORDINE,
  NUME_ROW,
  CS_CUATM
