/* === Output 27 coloane conform CSV: 
   1..3 -> 1.12.1 (COL1..COL3), 4..6 -> 1.12.2, ..., 25..27 -> 1.12.9 === */

SELECT 
  :pPERIOADA   AS PERIOADA,
  :pFORM       AS FORM,
  :pFORM_VERS  AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM  AS COD_CUATM,    
  NR_TABLE     AS NR_SECTIE,
  TABLE_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2, 
  COL_KEY||'~'||ROWNUM  AS NR_ROW,
  ROWNUM AS ORDINE,
  '00000000' AS DECIMAL_POS, 
  RIND_DENUMIRE AS NUME_ROW,

  /* 27 coloane în ordinea din CSV */
  ROUND(P01,0) AS COL1,  ROUND(P02,0) AS COL2,  ROUND(P03,0) AS COL3,
  ROUND(P04,0) AS COL4,  ROUND(P05,0) AS COL5,  ROUND(P06,0) AS COL6,
  ROUND(P07,0) AS COL7,  ROUND(P08,0) AS COL8,  ROUND(P09,0) AS COL9,
  ROUND(P10,0) AS COL10, ROUND(P11,0) AS COL11, ROUND(P12,0) AS COL12,
  ROUND(P13,0) AS COL13, ROUND(P14,0) AS COL14, ROUND(P15,0) AS COL15,
  ROUND(P16,0) AS COL16, ROUND(P17,0) AS COL17, ROUND(P18,0) AS COL18,
  ROUND(P19,0) AS COL19, ROUND(P20,0) AS COL20, ROUND(P21,0) AS COL21,
  ROUND(P22,0) AS COL22, ROUND(P23,0) AS COL23, ROUND(P24,0) AS COL24,
  ROUND(P25,0) AS COL25, ROUND(P26,0) AS COL26, ROUND(P27,0) AS COL27

FROM (
  /* =====================
     BLOC 1: Clasa de marime (cu BS)
     ===================== */
  SELECT 
    TR.NR_TABLE,
    TR.TABLE_DENUMIRE,
    TR.RIND_DENUMIRE,
    TR.ORDINE,
    TR.RIND,
    /* Cheia de rând (po?i pastra ce aveai anterior) */
    '1' AS COL_KEY,

    /* 1.12.1 -> P01..P03 (COL1..COL3), 1.12.2 -> P04..P06, ..., 1.12.9 -> P25..P27 */
    /* Pentru fiecare rind, trei numaratori dupa COL1/COL2/COL3 */
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P01,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P02,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P03,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P04,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P05,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P06,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P07,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P08,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P09,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P10,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P11,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P12,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P13,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P14,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P15,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P16,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P17,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P18,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P19,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P20,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P21,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P22,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P23,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P24,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS P25,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS P26,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS P27

  FROM (
    SELECT D.ANUL, D.CUIIO, D.CUATM, D.CAEM2, D.CAPITOL, D.RIND, D.COL1, D.COL2, D.COL3
    FROM CIS2.VW_DATA_ALL D
    WHERE
      D.PERIOADA IN (:pPERIOADA)
      AND D.FORM IN (:pFORM)
      AND D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013
      AND D.RIND IN ('1.12.1','1.12.2','1.12.3','1.12.4','1.12.5','1.12.6','1.12.7','1.12.8','1.12.9')
      AND D.CAEM2 NOT LIKE 'A%'
  ) A
  LEFT JOIN CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  INNER JOIN (
    SELECT CODUL, FULL_CODE 
    FROM CIS2.VW_CL_CAEM2
    WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') 
       OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
  ) C ON C.CODUL = A.CAEM2
  CROSS JOIN (
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',        '2',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',       '3',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',      '4',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','5','B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Industrie - total','6',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '7',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',     '8',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '9',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati', '10','B+C+D+E' FROM DUAL UNION 
    SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Servicii - total', '11','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '12','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',     '13','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '14','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','15','H+J+K+G46+M71+M72+M73' FROM DUAL
  ) TR
  WHERE
    ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
    AND (TR.RIND_C LIKE '%'||SUBSTR(A.CAEM2,1,1)||'%' OR TR.RIND_C LIKE '%'||SUBSTR(A.CAEM2,2,2)||'%')
  GROUP BY TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND

  UNION ALL

  /* =====================
     BLOC 2: CAEM2 (fara BS)
     ===================== */
  SELECT 
    TR.NR_TABLE,
    TR.TABLE_DENUMIRE,
    TR.RIND_DENUMIRE,
    TR.ORDINE,
    TR.RIND,
    '1' AS COL_KEY,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P01,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P02,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P03,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P04,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P05,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P06,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P07,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P08,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P09,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P10,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P11,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P12,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P13,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P14,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P15,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P16,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P17,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P18,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P19,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P20,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P21,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P22,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P23,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P24,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P25,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P26,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P27

  FROM CIS2.VW_DATA_ALL D
    INNER JOIN (
      SELECT CODUL, FULL_CODE 
      FROM CIS2.VW_CL_CAEM2
      WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K')
         OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
    ) C ON C.CODUL = D.CAEM2
    CROSS JOIN (
      SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+G+H+J+K+M' AS RIND, 'Total' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION 
      SELECT 1, 'CAEM2', NULL, NULL, 'B+C+D+E', 'Industrie - total', '2' FROM DUAL  UNION
      SELECT 1, 'CAEM2', NULL, NULL, 'B', 'Industrie extractiva', '3' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'C', 'Industrie prelucratoare', '4' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'D', 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat', '5' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'E', 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare', '6' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'H+J+K+G+M', 'Servicii - total ', '7' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'G', 'Comert cu ridicata ', '8' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'H', 'Transport si depozitare ', '9' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'J', 'Informatii si comunicatii', '10' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, 'K', 'Activitati  financiare si asigurari', '11' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, '71', 'Activitati de arhitectura si inginerie', '12' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, '72', 'Activitati de cercetare dezvoltare', '13' FROM DUAL UNION  
      SELECT 1, 'CAEM2', NULL, NULL, '73', 'Publicitate si activitati de studiere a pietei', '14' FROM DUAL   
    ) TR
  WHERE
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)
    AND D.RIND IN ('1.12.1','1.12.2','1.12.3','1.12.4','1.12.5','1.12.6','1.12.7','1.12.8','1.12.9')
    AND D.CAEM2 NOT LIKE 'A%'
    AND (TR.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR TR.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
  GROUP BY TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND

  UNION ALL

  /* =====================
     BLOC 3: Regiuni de dezvoltare (agregare)
     ===================== */
  SELECT 
    3 AS NR_TABLE, 
    ' Regiuni de dezvoltare' AS TABLE_DENUMIRE,
    CC.NUME_ROW AS RIND_DENUMIRE,
    CC.NR_ROW   AS ORDINE,
    CC.RIND     AS RIND,
    CC.NR_ROW   AS COL_KEY,

    /* Sumam cele 27 de pozi?ii pe regiune */
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P01,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P02,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.1' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P03,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P04,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P05,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.2' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P06,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P07,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P08,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.3' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P09,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P10,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P11,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.4' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P12,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P13,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P14,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.5' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P15,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P16,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P17,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.6' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P18,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P19,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P20,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.7' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P21,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P22,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P23,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.8' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P24,

    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL1)=1 THEN D.CUIIO END) AS P25,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL2)=1 THEN D.CUIIO END) AS P26,
    COUNT(DISTINCT CASE WHEN D.RIND='1.12.9' AND NVAL(D.COL3)=1 THEN D.CUIIO END) AS P27

  FROM CIS2.VW_DATA_ALL D
    INNER JOIN CIS2.VW_CL_CUATM  CU ON CU.CODUL = D.CUATM
    CROSS JOIN (
       SELECT '01' AS NR_ROW, 'TOTAL'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total' AS RIND_DENUMIRE, '1'  AS ORDINE FROM  DUAL UNION  
      SELECT '02' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '2'  FROM  DUAL UNION
      SELECT '03' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '3'  FROM  DUAL UNION 
      SELECT '04' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '4'  FROM  DUAL UNION
      SELECT '05' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '5'  FROM  DUAL UNION
      SELECT '06' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '6'  FROM   DUAL UNION 
      SELECT '07' AS NR_ROW, 'Industrie - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Industrie - total', '7'  FROM  DUAL UNION  
      SELECT '08' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '8'  FROM  DUAL UNION
      SELECT '09' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '9'  FROM  DUAL UNION 
      SELECT '10' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '10' FROM  DUAL UNION
      SELECT '11' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '11' FROM  DUAL UNION
      SELECT '12' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'B+C+D+E' AS RIND, 'Total', '12' FROM   DUAL UNION
      SELECT '13' AS NR_ROW, 'Servicii - total'  AS NUME_ROW, '0000000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Servicii - total', '13' FROM  DUAL UNION  
      SELECT '14' AS NR_ROW, 'MUN.CHISINAU'  AS NUME_ROW, '0100000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '14' FROM  DUAL UNION
      SELECT '15' AS NR_ROW, 'NORD'  AS NUME_ROW, '1111111'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '15' FROM  DUAL UNION 
      SELECT '16' AS NR_ROW, 'CENTRU'  AS NUME_ROW, '2222222'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '16' FROM  DUAL UNION
      SELECT '17' AS NR_ROW, 'SUD'  AS NUME_ROW, '3333333'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '17' FROM  DUAL UNION
      SELECT '18' AS NR_ROW, 'UTA GAGAUZIA'  AS NUME_ROW, '9600000'  AS CS_CUATM, 'H+J+K+G46+M71+M72+M73' AS RIND, 'Total', '18' FROM   DUAL 

    ) CC
  WHERE
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)
    AND D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013
    AND D.RIND IN ('1.12.1','1.12.2','1.12.3','1.12.4','1.12.5','1.12.6','1.12.7','1.12.8','1.12.9')
    AND D.CAEM2 NOT LIKE 'A%'
    AND CU.FULL_CODE LIKE '%'||CC.RIND||'%'
    AND (CC.RIND LIKE '%'||SUBSTR(D.CAEM2,1,1)||'%' OR CC.RIND LIKE '%'||SUBSTR(D.CAEM2,2,2)||'%')
  GROUP BY CC.NR_ROW, CC.NUME_ROW, CC.RIND
) A
ORDER BY TO_NUMBER(A.NR_TABLE), TO_NUMBER(A.ORDINE);
