SELECT
     R.ORDINE,
     R.RIND,
     R.DENUMIRE,            
     SUM(D.COL4) AS COL1,
     SUM(D.COL5)  AS COL2,
     ROUND(SUM(D.COL18),2) AS COL3,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL4)),2) AS COL4,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL5)),2) AS COL5,
     SUM(D.COL9) AS COL6,
     SUM(D.COL10)  AS COL7,
     SUM(D.COL19)  AS COL8,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL9)),2) AS COL9,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL10)),2) AS COL10
     
     
      
    
   
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  
GROUP BY
  R.RIND,
  R.DENUMIRE,
  R.ORDINE