SELECT 
 FORMID,
  XML,
  STATUS,
  FORM_TYPE,
  DATA_REG,
  CHECK_CONFIRM,
  MESAJ,
  CUIIO,
    LENGTH(CUIIO) STR_CUIIO,
  SEND_REQUEST,
  SEND_ATTEMPTS,
  PROCESSING_MESSAGE 
        
        
          FROM  USER_EREPORTING.F_XML_FORMS
          
          
          WHERE

 
  -- FORM_TYPE IN  ('1-a-sc','1-tr-auto-new','asa-22','1-inf.rev')
  FORM_TYPE IN  ('1-a-sc')
-- AND STATUS <> '5' AND   STATUS <> '3'
--
--  AND DATA_REG > TO_DATE('1/19/2026 12:04:15 PM', 'MM/DD/YYYY HH24:MI:SS')
 --AND DATA_REG > TO_DATE('1/19/2026 18:00:49', 'MM/DD/YYYY HH24:MI:SS')
 AND DATA_REG >= TO_DATE('01/19/2026 08:00:49', 'MM/DD/YYYY HH24:MI:SS')
 


 ORDER BY 
 
 DATA_REG DESC;
 
 
 