SELECT     
DISTINCT 
D.CUIIO,
D.CUIIO_VERS,
D.USER_NAME  
 
    FROM CIS2.VW_DATA_ALL D
    WHERE 
    1=1
    AND D.FORM IN (45)
    AND D.PERIOADA  IN (1067)
    AND USER_NAME IN ('e-Reporting')
 -- AND D.CUIIO LIKE   :pCUIIO||'%'
  
   AND D.DATA_REG > TO_DATE('12/24/2025 17:00:49', 'MM/DD/YYYY HH24:MI:SS')