SELECT 
 FORMID,
  XML,
  STATUS,
  FORM_TYPE,
  DATA_REG,
  CHECK_CONFIRM,
  MESAJ,
  CUIIO,
    LENGTH(CUIIO) STR_CUIIO,
  SEND_REQUEST,
  SEND_ATTEMPTS,
  PROCESSING_MESSAGE 
        
        
          FROM  USER_EREPORTING.F_XML_FORMS
          
          
          WHERE

 
  FORM_TYPE IN  ('29_agr24')
-- AND STATUS <> '5' AND   STATUS <> '3'
--
 -- AND DATA_REG > TO_DATE('12/11/2025 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
 AND DATA_REG > TO_DATE('12/25/2025 17:00:49', 'MM/DD/YYYY HH24:MI:SS')
 
 --12/11/2025 5:22:49 PM
-- 
-- AND LENGTH(CUIIO) >= 8
-- 
 

--AND CUIIO IN (
--SELECT     
--DISTINCT CUIIO  
-- 
--    FROM CIS2.VW_DATA_ALL D
--    WHERE 
--    1=1
--    AND D.FORM IN (45)
--    AND D.PERIOADA  IN (1067)
--    -- AND USER_NAME IN ('e-Reporting')
--    AND R.CUIIO LIKE   40583135||'%'
--)

 ORDER BY 
 
 DATA_REG DESC