SELECT 
  L.FORMID,
  L.CUIIO,
  L.STATUS,
  L.FORM_TYPE,
  L.DATA_REG,
  L.CHECK_CONFIRM,
  L.MESAJ,
  L.PROCESSING_MESSAGE 
 
    FROM  USER_EREPORTING.F_XML_FORMS  L
          WHERE
          1=1  AND 
   FORM_TYPE  IN  ('1-tr-auto-new')

 ORDER BY 

DATA_REG DESC 