CREATE OR REPLACE FORCE VIEW USER_BANCU.F_XML_FORMS_M1_1067

AS

SELECT 
  L.FORMID,
  L.CUIIO,
  D.DESCRIPTION,
  L.STATUS,
  L.FORM_TYPE,
  L.DATA_REG,
  L.CHECK_CONFIRM,
  L.MESAJ,
  L.PROCESSING_MESSAGE 
 
    FROM  USER_EREPORTING.F_XML_FORMS L INNER JOIN USER_EREPORTING.F_XML_FORMS_STATUS D  ON L.STATUS = D.COD_STATUS
          WHERE
          1=1  AND 
   FORM_TYPE NOT IN  ('2-inv-anual','ind-ts','1-cc','consts','1-b-sc')
--FORM_TYPE IN  ('1-turism_23')
  
          AND   FORM_TYPE IN  ('m1') 

    AND DATA_REG >= TO_DATE('01/01/2026 08:00:49', 'MM/DD/YYYY HH24:MI:SS')


 ORDER BY 
-- 
DATA_REG DESC 