


SELECT L.CUIIO,
       L.CUATM,
       L.IDNO,
       R.DESCRIPTION,
       R.STATUS,
       R.FORM_TYPE
       
FROM M_1067 L LEFT JOIN  USER_BANCU.F_XML_FORMS_M1_1067 R ON R.CUIIO = L.CUIIO

WHERE 
R.CUIIO IS NOT NULL;