--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4
--)


SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '0002' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    COL1, COL2, COL3, COL4
FROM
(
  SELECT 
         RR.ORDINE AS ORDINE, 
         RR.RIND AS RIND,
         RR.DENUMIRE  DENUMIRE, 
       
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610')  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610')  THEN D.COL4 ELSE NULL END)) AS COL2,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610')  THEN D.COL7 ELSE NULL END)) AS COL3,
         ROUND(( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610')   THEN D.COL7 ELSE NULL END))/
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610')    THEN D.COL4 ELSE NULL END)))),3) AS COL4
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1113')  
    
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 --(D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)AND  D.RIND IN('210','220','230','240','310','320','330','340','350','360','400','401','600','610') AND D.CAPITOL IN ('1113')  
  AND  D.UNIT_CODE IN (
    SELECT 
      CUIIO UNIT_CODE  
      FROM   USER_BANCU.CMPA_1
 ) 
  
  
  GROUP BY 
  RR.ORDINE, 
  RR.RIND,
  RR.DENUMIRE 
  ORDER BY RR.ORDINE
  
)

UNION



SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '0003' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    COL1, COL2, COL3, COL4
FROM
(
  SELECT 
         4.5 AS ORDINE, 
         '250' AS RIND,
         'Total samîn?oase'AS  DENUMIRE, 
       
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '210'AND '240'  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '210'AND '240'  THEN D.COL4 ELSE NULL END)) AS COL2,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '210'AND '240'  THEN D.COL7 ELSE NULL END)) AS COL3,
         ROUND(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '210'AND '240'  THEN D.COL7 ELSE NULL END)) /
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '210'AND '240'  THEN D.COL4 ELSE NULL END))),3) AS COL4
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1113')  
    
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61) AND D.RIND BETWEEN '210'AND '240' AND D.CAPITOL IN ('1113')  
   AND  D.UNIT_CODE IN (
    SELECT 
      CUIIO UNIT_CODE  
      FROM   USER_BANCU.CMPA_1
 ) 
  

  )
  
  UNION
  
  SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '0003' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    COL1, COL2, COL3, COL4
FROM
(
  SELECT 
         10.5 AS ORDINE, 
         '370' AS RIND,
         'Total sîmburoase'AS  DENUMIRE, 
       
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '310'AND '360'  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '310'AND '360'  THEN D.COL4 ELSE NULL END)) AS COL2,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '310'AND '360'  THEN D.COL7 ELSE NULL END)) AS COL3,
         ROUND(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '310'AND '360'  THEN D.COL7 ELSE NULL END)) /
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '310'AND '360'  THEN D.COL4 ELSE NULL END))),3) AS COL4
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1113')  
    
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 --(D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61) AND D.RIND BETWEEN '310'AND '360' AND D.CAPITOL IN ('1113')  
   AND  D.UNIT_CODE IN (
    SELECT 
      CUIIO UNIT_CODE  
      FROM   USER_BANCU.CMPA_1
 ) 
  

  )
  
  ORDER BY 
  ORDINE