--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5, COL6
--)

SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
    RR.RIND, 
    -- ||'~'||ROWNUM AS  NR_ROW,     
    RR.ORDINE,
  --  '123332' AS DECIMAL_POS,
    RR.DENUMIRE AS NUME_ROW, 
    ROUND(D.COL1,1) AS COL1, 
    ROUND(D.COL2,2) AS COL2, 
    ROUND(D.COL3,3) AS COL3, 
    ROUND(D.COL4,3) AS COL4, 
    ROUND(D.COL5,3) AS COL5, 
    ROUND(D.COL6,2) AS COL6
    
FROM
(
  SELECT 
         MAX(RR.ORDINE) AS ORDINE, 
         RR.RIND AS RIND,
         MAX(RR.DENUMIRE) DENUMIRE, 
       
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL2 ELSE NULL END)) AS COL2,
         ROUND(( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL2 ELSE NULL END))/
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL1 ELSE NULL END))))*100,3) AS COL3,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL3 ELSE NULL END)) AS COL4,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL4 ELSE NULL END))/100 AS COL5,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL4 ELSE NULL END)/100)/ 
         CIS2.NOZERO( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '010' AND '030'  THEN D.COL3 ELSE NULL END))) AS COL6   
     
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1112')  
    
WHERE
 -- (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
-- (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)AND  D.RIND BETWEEN '010' AND '030' AND D.CAPITOL IN ('1112')  
  
 AND  D.UNIT_CODE IN (
    SELECT 
      CUIIO UNIT_CODE  
      FROM   USER_BANCU.CMPA_1
 ) 
  
  GROUP BY 
--  RR.ORDINE, 
  RR.RIND--,
--  RR.DENUMIRE  
UNION
  SELECT 
         MAX(RR.ORDINE) AS ORDINE, 
         RR.RIND AS RIND,
         MAX(RR.DENUMIRE) DENUMIRE, 
       
         NULL AS COL1,
                 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054' THEN D.COL2 ELSE NULL END)) AS COL2,
         
         ROUND(( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054'  THEN D.COL2 ELSE NULL END))/
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1111) AND D.NUM IN (2) AND D.RIND BETWEEN '040' AND '054'   THEN D.COL1 ELSE NULL END))))*100,3) AS COL3,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054'  THEN D.COL3 ELSE NULL END)) AS COL4,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054'  THEN D.COL4 ELSE NULL END))/100 AS COL5,
         ROUND(CIS2.NVAL((SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054'  THEN D.COL4 ELSE NULL END))/100)/ 
         CIS2.NOZERO( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1112) AND D.RIND BETWEEN '040' AND '054'   THEN D.COL3 ELSE NULL END))),2) AS COL6    
     
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD 
    
WHERE
 -- (D.PERIOADA IN (:pPERIOADA))  AND 
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 --(D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')  AND 
 D.CAPITOL IN (1112,1111)  AND
  D.FORM IN (61) AND D.RIND BETWEEN '040' AND '054'
  
  AND  D.UNIT_CODE IN (
    SELECT 
      CUIIO UNIT_CODE  
      FROM   USER_BANCU.CMPA_1
 ) 
  GROUP BY 
--  RR.ORDINE, 
  RR.RIND--,
--  RR.DENUMIRE 

  



UNION

  SELECT 
         MAX(RR.ORDINE) AS ORDINE, 
         RR.RIND AS RIND,
         MAX(RR.DENUMIRE) DENUMIRE, 
       
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL2 ELSE NULL END)) AS COL2,
         ROUND(( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL2 ELSE NULL END))/
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL1 ELSE NULL END))))*100,3) AS COL3,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL3 ELSE NULL END)) AS COL4,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL4 ELSE NULL END))/100 AS COL5,
         ROUND((CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL4 ELSE NULL END))/100)/ 
         CIS2.NOZERO( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND BETWEEN '060' AND '083'  THEN D.COL3 ELSE NULL END))),2) AS COL6   
     
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1112')  
    
WHERE
 -- (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)AND  D.RIND BETWEEN '060' AND '083' AND D.CAPITOL IN ('1112')  
  
  GROUP BY 
--  RR.ORDINE, 
  RR.RIND--,
--  RR.DENUMIRE 
 -- ORDER BY RR.ORDINE
  
)D
 
 -- INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1112')  
 RIGHT JOIN ( SELECT  RIND, DENUMIRE,ORDINE 
               FROM    CIS2.MD_RIND       
               WHERE   FORM= 61 AND CAPITOL = 1112 AND ORDINE <= 37 /*AND RIND NOT IN ('-')*/ ORDER BY ORDINE) RR 
               ON RR.RIND=D.RIND