SELECT  
'FILIALA='||D.FILIAL||':'||
CASE WHEN 
  ( SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL2) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL3) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL4) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL5) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL6) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL7) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL8) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL10) ELSE 0 END)) <>0
    
    AND 
    
    
   (SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL2) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL3) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL4) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL5) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL6) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL7) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL8) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL10) ELSE 0 END)
    ) =0 
    
THEN
 'CAEM principal lipsa, Rind 01-T' 
ELSE
 'CAEM principal si CAEM secundar prezente'
END

   AS REZULTAT

FROM
  VW_DATA_ALL D 

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (3)  AND
  D.CAPITOL in (301) AND
  D.RIND IN('00-T','01-T')
  
  AND D.CUIIO = 227293
GROUP BY
  D.FILIAL
HAVING


  ( SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL2) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL3) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL4) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL5) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL6) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL7) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL8) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.RIND IN('00-T') THEN   NVAL(D.COL10) ELSE 0 END) )<>0

AND 

  ( SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL2) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL3) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL4) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL5) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL6) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL7) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL8) ELSE 0 END)+ 
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.RIND IN('01-T') THEN  NVAL(D.COL10) ELSE 0 END))=0