SELECT 
    1 ORDINE,
     CII.NAME DENUMIRE,
     CII.ITEM_CODE,
     CII.SHOW_ORDER, 
     CII.ITEM_PATH FULL_CODE,
     SUM(CASE WHEN  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL1,
     SUM(CASE WHEN  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL2,
     SUM(CASE WHEN  D.CAPITOL IN (407)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL3,
     SUM(CASE WHEN  D.CAPITOL IN (407)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL4
     
  FROM CIS2.VW_DATA_ALL D 
        INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
        INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
        AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
      
      -------------------------------------------------------------------------------
        
        ------------------------------------------------------------------------------      
      
   
   WHERE 
(D.PERIOADA IN (:pPERIOADA)) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
 -- (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  D.CAPITOL IN (405,407)   
  
 -- AND CII.ITEM_CODE IN ('3.1.3')
  
      GROUP BY
 
      CII.NAME,
      CII.ITEM_CODE,
       CII.ITEM_PATH,
       CII.SHOW_ORDER 
       
       UNION 
       
       SELECT 
     2 ORDINE,
      TTT.A01  DENUMIRE,
      TTT.ITEM_CODE,
      TTT.SHOW_ORDER,
      TTT.ITEM_PATH FULL_CODE,
     SUM(CASE WHEN D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL1,
     SUM(CASE WHEN  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL2,
     SUM(CASE WHEN  D.CAPITOL IN (407)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL3,
     SUM(CASE WHEN  D.CAPITOL IN (407)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)  AS COL4
      
      FROM CIS2.VW_DATA_ALL D 
           INNER JOIN VW_CLS_CLASS_ITEM TT ON (TT.CLASS_CODE IN ('TARI_ISO') AND TT.ITEM_CODE=D.COL33) 
           
           
       INNER JOIN VW_CLS_CLASS_ITEM TTT ON (TTT.CLASS_CODE IN ('TARI_ISO') AND TT.ITEM_PATH LIKE '%'||TTT.ITEM_CODE||';%')
         INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
        INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
          
     
          AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
   WHERE 
(D.PERIOADA IN (:pPERIOADA)) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
 -- (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  D.CAPITOL IN (405,407)  
  
  AND TTT.ITEM_CODE NOT IN ('000')
  AND CII.ITEM_CODE NOT IN ('00.00.00')
   -- AND CII.ITEM_CODE IN ('3.1.3')
   -- AND D.CUIIO = 1129894
  
      GROUP BY
      TTT.A01,
      TTT.ITEM_CODE,
      TTT.SHOW_ORDER,
      TTT.ITEM_PATH
      
      ORDER BY
      
      SHOW_ORDER,
      ORDINE