SELECT
        D.CUIIO,
        D.CAEM2,
        SUM(CASE WHEN D.RIND = '1.3.1' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL1,
        SUM(CASE WHEN D.RIND = '1.3.2' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL2,
        SUM(CASE WHEN D.RIND = '1.3.3' AND NVAL(D.COL1)>=1 THEN NVAL(D.COL1)  ELSE NULL  END)  AS COL3
     FROM 
        CIS2.VW_DATA_ALL D
      WHERE
        D.PERIOADA IN (:pPERIOADA) AND
        D.FORM     IN (:pFORM) AND 
        D.CAPITOL = 1040 AND D.CAPITOL_VERS = 2013 AND 
        D.RIND IN ('1.3.1','1.3.2','1.3.3') AND
        D.CAEM2 NOT LIKE 'A%'
        AND D.CUIIO = 40585950

GROUP BY 
D.CUIIO,
D.CAEM2
 
 