SELECT
    TR.NR_TABLE,
    TR.TABLE_DENUMIRE,
    TR.RIND_DENUMIRE,
    TR.ORDINE,
    TR.RIND,
    '1' AS COL_KEY,

    /* 1.12.1 -> COL1..COL3 ; 1.12.2 -> COL4..COL6 ; ... ; 1.12.9 -> COL25..COL27 */
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL1,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL2,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.1' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL3,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL4,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL5,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.2' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL6,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL7,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL8,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.3' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL9,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL10,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL11,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.4' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL12,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL13,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL14,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.5' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL15,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL16,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL17,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.6' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL18,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL19,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL20,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.7' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL21,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL22,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL23,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.8' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL24,

    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL1)=1 THEN A.CUIIO END) AS COL25,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL2)=1 THEN A.CUIIO END) AS COL26,
    COUNT(DISTINCT CASE WHEN A.RIND='1.12.9' AND NVAL(A.COL3)=1 THEN A.CUIIO END) AS COL27,
    
    COUNT(DISTINCT CASE WHEN A.RIND LIKE '1.12%' THEN A.CUIIO END) AS COL28

  FROM
  (
    SELECT
      D.ANUL,
      D.CUIIO,
      D.CUATM,
      D.CAEM2,
      D.CAPITOL,
      D.RIND,
      D.COL1,
      D.COL2,
      D.COL3
    FROM CIS2.VW_DATA_ALL D
    WHERE
      D.PERIOADA IN (:pPERIOADA) AND
      D.FORM IN (:pFORM) AND 
      D.CAPITOL=1040 AND D.CAPITOL_VERS=2013 AND 
      D.RIND IN ('1.12.1','1.12.2','1.12.3','1.12.4','1.12.5','1.12.6','1.12.7','1.12.8','1.12.9') AND
      D.CAEM2 NOT LIKE 'A%'
  ) A
  LEFT JOIN CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  INNER JOIN (
    SELECT CODUL, FULL_CODE 
    FROM CIS2.VW_CL_CAEM2
    WHERE SUBSTR(CODUL,1,1) IN ('B','C','D','E','H','J','K') 
       OR SUBSTR(CODUL,1,3) IN ('G46','M71','M72','M73')
  ) C ON C.CODUL = A.CAEM2
  CROSS JOIN 
  (
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE, 'B+C+D+E+H+J+K+G46+M71+M72+M73' AS RIND_C FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',        '2',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',       '3',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',      '4',  'B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','5','B+C+D+E+H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Industrie - total','6',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '7',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',     '8',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '9',  'B+C+D+E' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati', '10','B+C+D+E' FROM DUAL UNION 
    SELECT 2, 'Clasa de marime', 0, 999999, NULL, 'Servicii - total', '11','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 0, 9,   NULL, '0-9 salariati',       '12','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 10, 49, NULL, '10-49 salariati',     '13','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 50, 249,NULL, '50-249 salariati',    '14','H+J+K+G46+M71+M72+M73' FROM DUAL UNION
    SELECT 2, 'Clasa de marime', 250, 999999, NULL, '250 si peste salariati','15','H+J+K+G46+M71+M72+M73' FROM DUAL
  ) TR
  WHERE
    ((ROUND(BS.PERS_IT) BETWEEN TR.PERS_INIT AND TR.PERS_FINAL) OR ROUND(BS.PERS_IT) IS NULL)
    AND ((TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%') OR (TR.RIND_C LIKE '%'|| SUBSTR(A.CAEM2,2,2) ||'%'))
  GROUP BY
    TR.NR_TABLE, TR.TABLE_DENUMIRE, TR.RIND_DENUMIRE, TR.ORDINE, TR.RIND
    
    ORDER BY
    TO_NUMBER(TR.ORDINE)
