SELECT
D.CUIIO,
D.CUATM,
C.FULL_CODE,
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.4.1') AND   NVAL(D.COL1) = 1 THEN D.CUIIO END) AS COL1

FROM 
  CIS2.VW_DATA_ALL D INNER JOIN CIS2.VW_CL_CUATM  C ON C.CODUL = D.CUATM
  
  WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=1040 AND  capitol_vers=2013 AND 
  D.RIND IN ('1.4.1','1.4.2','1.4.3','1.4.4')
  AND D.CAEM2 NOT LIKE 'A%'
--  AND D.CUIIO = 458963
  

GROUP BY 
D.CUIIO,
D.CUATM,
C.FULL_CODE 



HAVING 
COUNT(DISTINCT CASE WHEN D.RIND IN ('1.4.1') AND   NVAL(D.COL1) = 1 THEN D.CUIIO END) = 1 

ORDER BY
C.FULL_CODE
