 
 SELECT 
        D.ANUL,
        D.CUIIO,
        R.DENUMIRE,
        R.CUATM,
        R.CFP,
        R.N85_NTIIP NTIIP,
        SUM(CASE WHEN D.CAPITOL IN (1001) AND D.RIND IN ('010') THEN D.COL1 ELSE NULL END ) AS COL1,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL1 ELSE NULL END ) AS COL2,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL2 ELSE NULL END ) AS COL3,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL3 ELSE NULL END ) AS COL4,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL4 ELSE NULL END ) AS COL5,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL5 ELSE NULL END ) AS COL6,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL6 ELSE NULL END ) AS COL7,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL7 ELSE NULL END ) AS COL8,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL8 ELSE NULL END ) AS COL9,
        SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010') THEN D.COL8 ELSE NULL END ) AS COL10
 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                
               
WHERE
  D.FORM IN (17)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (1001,1002)                         AND 
  D.PERIOADA IN (2014,2013)  
  
  
  GROUP BY 
          D.ANUL,
        D.CUIIO,
        R.DENUMIRE,
        R.CUATM,
        R.CFP,
        R.N85_NTIIP
        
        ORDER BY 
           D.ANUL,
           D.CUIIO,
           R.CUATM